versions:
  - version: 2023-10-01-preview
    source: typespec
    swagger-files:
      - preview/2023-10-01-preview/pipelineGroups.json
  - version: 2024-10-01-preview
    source: typespec
    swagger-files:
      - preview/2024-10-01-preview/pipelineGroups.json
  - version: 2025-03-01-preview
    source: typespec
    swagger-files:
      - preview/2025-03-01-preview/pipelineGroups.json
  - version: 2026-04-01
    source: typespec
    swagger-files:
      - stable/2026-04-01/pipelineGroups.json
