// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package typespec-go

import (
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/arm"
)

// ContainerStorageClient - Azure Container Storage Resource Provider API.
// Don't use this type directly, use NewContainerStorageClient() instead.
type ContainerStorageClient struct {
	internal *arm.Client
}

// NewContainerStorageClient creates a new instance of ContainerStorageClient with the specified values.
//   - credential - used to authorize requests. Usually a credential from azidentity.
//   - options - pass nil to accept the default values.
func NewContainerStorageClient(credential azcore.TokenCredential, options *arm.ClientOptions) (*ContainerStorageClient, error) {
	cl, err := arm.NewClient(moduleName, moduleVersion, credential, options)
	if err != nil {
		return nil, err
	}
	client := &ContainerStorageClient{
	internal: cl,
	}
	return client, nil
}

// NewOperationsClient creates a new instance of [OperationsClient].
func (client *ContainerStorageClient) NewOperationsClient() *OperationsClient {
	return &OperationsClient{
		internal: client.internal,
	}
}

// NewPoolsClient creates a new instance of [PoolsClient].
func (client *ContainerStorageClient) NewPoolsClient() *PoolsClient {
	return &PoolsClient{
		internal: client.internal,
	}
}

// NewSnapshotsClient creates a new instance of [SnapshotsClient].
func (client *ContainerStorageClient) NewSnapshotsClient() *SnapshotsClient {
	return &SnapshotsClient{
		internal: client.internal,
	}
}

// NewVolumesClient creates a new instance of [VolumesClient].
func (client *ContainerStorageClient) NewVolumesClient() *VolumesClient {
	return &VolumesClient{
		internal: client.internal,
	}
}

