// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.datamigration.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * The state of the command. This is ignored if submitted.
 */
public final class CommandState extends ExpandableStringEnum<CommandState> {
    /**
     * Unknown.
     */
    public static final CommandState UNKNOWN = fromString("Unknown");

    /**
     * Accepted.
     */
    public static final CommandState ACCEPTED = fromString("Accepted");

    /**
     * Running.
     */
    public static final CommandState RUNNING = fromString("Running");

    /**
     * Succeeded.
     */
    public static final CommandState SUCCEEDED = fromString("Succeeded");

    /**
     * Failed.
     */
    public static final CommandState FAILED = fromString("Failed");

    /**
     * Creates a new instance of CommandState value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public CommandState() {
    }

    /**
     * Creates or finds a CommandState from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding CommandState.
     */
    public static CommandState fromString(String name) {
        return fromString(name, CommandState.class);
    }

    /**
     * Gets known CommandState values.
     * 
     * @return known CommandState values.
     */
    public static Collection<CommandState> values() {
        return values(CommandState.class);
    }
}
