// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.datamigration.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * Information for connecting to PostgreSQL server.
 */
@Fluent
public final class PostgreSqlConnectionInfo extends ConnectionInfo {
    /*
     * Type of connection info
     */
    private String type = "PostgreSqlConnectionInfo";

    /*
     * Name of the server
     */
    private String serverName;

    /*
     * Data source
     */
    private String dataSource;

    /*
     * server version
     */
    private String serverVersion;

    /*
     * Name of the database
     */
    private String databaseName;

    /*
     * Port for Server
     */
    private int port;

    /*
     * Whether to encrypt the connection
     */
    private Boolean encryptConnection;

    /*
     * Whether to trust the server certificate
     */
    private Boolean trustServerCertificate;

    /*
     * Additional connection settings
     */
    private String additionalSettings;

    /*
     * server brand version
     */
    private String serverBrandVersion;

    /*
     * Authentication type to use for connection
     */
    private AuthenticationType authentication;

    /**
     * Creates an instance of PostgreSqlConnectionInfo class.
     */
    public PostgreSqlConnectionInfo() {
    }

    /**
     * Get the type property: Type of connection info.
     * 
     * @return the type value.
     */
    @Override
    public String type() {
        return this.type;
    }

    /**
     * Get the serverName property: Name of the server.
     * 
     * @return the serverName value.
     */
    public String serverName() {
        return this.serverName;
    }

    /**
     * Set the serverName property: Name of the server.
     * 
     * @param serverName the serverName value to set.
     * @return the PostgreSqlConnectionInfo object itself.
     */
    public PostgreSqlConnectionInfo withServerName(String serverName) {
        this.serverName = serverName;
        return this;
    }

    /**
     * Get the dataSource property: Data source.
     * 
     * @return the dataSource value.
     */
    public String dataSource() {
        return this.dataSource;
    }

    /**
     * Set the dataSource property: Data source.
     * 
     * @param dataSource the dataSource value to set.
     * @return the PostgreSqlConnectionInfo object itself.
     */
    public PostgreSqlConnectionInfo withDataSource(String dataSource) {
        this.dataSource = dataSource;
        return this;
    }

    /**
     * Get the serverVersion property: server version.
     * 
     * @return the serverVersion value.
     */
    public String serverVersion() {
        return this.serverVersion;
    }

    /**
     * Set the serverVersion property: server version.
     * 
     * @param serverVersion the serverVersion value to set.
     * @return the PostgreSqlConnectionInfo object itself.
     */
    public PostgreSqlConnectionInfo withServerVersion(String serverVersion) {
        this.serverVersion = serverVersion;
        return this;
    }

    /**
     * Get the databaseName property: Name of the database.
     * 
     * @return the databaseName value.
     */
    public String databaseName() {
        return this.databaseName;
    }

    /**
     * Set the databaseName property: Name of the database.
     * 
     * @param databaseName the databaseName value to set.
     * @return the PostgreSqlConnectionInfo object itself.
     */
    public PostgreSqlConnectionInfo withDatabaseName(String databaseName) {
        this.databaseName = databaseName;
        return this;
    }

    /**
     * Get the port property: Port for Server.
     * 
     * @return the port value.
     */
    public int port() {
        return this.port;
    }

    /**
     * Set the port property: Port for Server.
     * 
     * @param port the port value to set.
     * @return the PostgreSqlConnectionInfo object itself.
     */
    public PostgreSqlConnectionInfo withPort(int port) {
        this.port = port;
        return this;
    }

    /**
     * Get the encryptConnection property: Whether to encrypt the connection.
     * 
     * @return the encryptConnection value.
     */
    public Boolean encryptConnection() {
        return this.encryptConnection;
    }

    /**
     * Set the encryptConnection property: Whether to encrypt the connection.
     * 
     * @param encryptConnection the encryptConnection value to set.
     * @return the PostgreSqlConnectionInfo object itself.
     */
    public PostgreSqlConnectionInfo withEncryptConnection(Boolean encryptConnection) {
        this.encryptConnection = encryptConnection;
        return this;
    }

    /**
     * Get the trustServerCertificate property: Whether to trust the server certificate.
     * 
     * @return the trustServerCertificate value.
     */
    public Boolean trustServerCertificate() {
        return this.trustServerCertificate;
    }

    /**
     * Set the trustServerCertificate property: Whether to trust the server certificate.
     * 
     * @param trustServerCertificate the trustServerCertificate value to set.
     * @return the PostgreSqlConnectionInfo object itself.
     */
    public PostgreSqlConnectionInfo withTrustServerCertificate(Boolean trustServerCertificate) {
        this.trustServerCertificate = trustServerCertificate;
        return this;
    }

    /**
     * Get the additionalSettings property: Additional connection settings.
     * 
     * @return the additionalSettings value.
     */
    public String additionalSettings() {
        return this.additionalSettings;
    }

    /**
     * Set the additionalSettings property: Additional connection settings.
     * 
     * @param additionalSettings the additionalSettings value to set.
     * @return the PostgreSqlConnectionInfo object itself.
     */
    public PostgreSqlConnectionInfo withAdditionalSettings(String additionalSettings) {
        this.additionalSettings = additionalSettings;
        return this;
    }

    /**
     * Get the serverBrandVersion property: server brand version.
     * 
     * @return the serverBrandVersion value.
     */
    public String serverBrandVersion() {
        return this.serverBrandVersion;
    }

    /**
     * Set the serverBrandVersion property: server brand version.
     * 
     * @param serverBrandVersion the serverBrandVersion value to set.
     * @return the PostgreSqlConnectionInfo object itself.
     */
    public PostgreSqlConnectionInfo withServerBrandVersion(String serverBrandVersion) {
        this.serverBrandVersion = serverBrandVersion;
        return this;
    }

    /**
     * Get the authentication property: Authentication type to use for connection.
     * 
     * @return the authentication value.
     */
    public AuthenticationType authentication() {
        return this.authentication;
    }

    /**
     * Set the authentication property: Authentication type to use for connection.
     * 
     * @param authentication the authentication value to set.
     * @return the PostgreSqlConnectionInfo object itself.
     */
    public PostgreSqlConnectionInfo withAuthentication(AuthenticationType authentication) {
        this.authentication = authentication;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostgreSqlConnectionInfo withUserName(String userName) {
        super.withUserName(userName);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PostgreSqlConnectionInfo withPassword(String password) {
        super.withPassword(password);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("userName", userName());
        jsonWriter.writeStringField("password", password());
        jsonWriter.writeStringField("serverName", this.serverName);
        jsonWriter.writeIntField("port", this.port);
        jsonWriter.writeStringField("type", this.type);
        jsonWriter.writeStringField("dataSource", this.dataSource);
        jsonWriter.writeStringField("serverVersion", this.serverVersion);
        jsonWriter.writeStringField("databaseName", this.databaseName);
        jsonWriter.writeBooleanField("encryptConnection", this.encryptConnection);
        jsonWriter.writeBooleanField("trustServerCertificate", this.trustServerCertificate);
        jsonWriter.writeStringField("additionalSettings", this.additionalSettings);
        jsonWriter.writeStringField("serverBrandVersion", this.serverBrandVersion);
        jsonWriter.writeStringField("authentication",
            this.authentication == null ? null : this.authentication.toString());
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of PostgreSqlConnectionInfo from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of PostgreSqlConnectionInfo if the JsonReader was pointing to an instance of it, or null if
     * it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the PostgreSqlConnectionInfo.
     */
    public static PostgreSqlConnectionInfo fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            PostgreSqlConnectionInfo deserializedPostgreSqlConnectionInfo = new PostgreSqlConnectionInfo();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("userName".equals(fieldName)) {
                    deserializedPostgreSqlConnectionInfo.withUserName(reader.getString());
                } else if ("password".equals(fieldName)) {
                    deserializedPostgreSqlConnectionInfo.withPassword(reader.getString());
                } else if ("serverName".equals(fieldName)) {
                    deserializedPostgreSqlConnectionInfo.serverName = reader.getString();
                } else if ("port".equals(fieldName)) {
                    deserializedPostgreSqlConnectionInfo.port = reader.getInt();
                } else if ("type".equals(fieldName)) {
                    deserializedPostgreSqlConnectionInfo.type = reader.getString();
                } else if ("dataSource".equals(fieldName)) {
                    deserializedPostgreSqlConnectionInfo.dataSource = reader.getString();
                } else if ("serverVersion".equals(fieldName)) {
                    deserializedPostgreSqlConnectionInfo.serverVersion = reader.getString();
                } else if ("databaseName".equals(fieldName)) {
                    deserializedPostgreSqlConnectionInfo.databaseName = reader.getString();
                } else if ("encryptConnection".equals(fieldName)) {
                    deserializedPostgreSqlConnectionInfo.encryptConnection = reader.getNullable(JsonReader::getBoolean);
                } else if ("trustServerCertificate".equals(fieldName)) {
                    deserializedPostgreSqlConnectionInfo.trustServerCertificate
                        = reader.getNullable(JsonReader::getBoolean);
                } else if ("additionalSettings".equals(fieldName)) {
                    deserializedPostgreSqlConnectionInfo.additionalSettings = reader.getString();
                } else if ("serverBrandVersion".equals(fieldName)) {
                    deserializedPostgreSqlConnectionInfo.serverBrandVersion = reader.getString();
                } else if ("authentication".equals(fieldName)) {
                    deserializedPostgreSqlConnectionInfo.authentication
                        = AuthenticationType.fromString(reader.getString());
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedPostgreSqlConnectionInfo;
        });
    }
}
