versions:
  - version: 2025-06-01
    source: typespec
    swagger-files:
      - stable/2025-06-01/netapp.json
  - version: 2025-08-01
    source: typespec
    swagger-files:
      - stable/2025-08-01/netapp.json
  - version: 2025-09-01
    source: typespec
    swagger-files:
      - stable/2025-09-01/netapp.json
  - version: 2025-12-01
    source: typespec
    swagger-files:
      - stable/2025-12-01/netapp.json
  - version: 2025-12-15-preview
    source: typespec
    swagger-files:
      - preview/2025-12-15-preview/netapp.json
  - version: 2026-01-01
    source: typespec
    swagger-files:
      - stable/2026-01-01/netapp.json
  - version: 2026-01-15-preview
    source: typespec
    swagger-files:
      - preview/2026-01-15-preview/netapp.json
  - version: 2026-03-01
    source: typespec
    swagger-files:
      - stable/2026-03-01/netapp.json
  - version: 2026-03-15-preview
    source: typespec
    swagger-files:
      - preview/2026-03-15-preview/netapp.json
  - version: 2026-04-01
    source: typespec
    swagger-files:
      - stable/2026-04-01/netapp.json
  - version: 2026-04-15-preview
    source: typespec
    swagger-files:
      - preview/2026-04-15-preview/netapp.json
