versions:
  - version: 2017-09-01
    source: swagger
    swagger-files:
      - ../stable/2017-09-01/skus.json
  - version: 2019-04-01
    source: swagger
    swagger-files:
      - ../stable/2019-04-01/skus.json
  - version: 2021-07-01
    source: typespec
    swagger-files:
      - ../stable/2021-07-01/skus.json
