versions:
  - version: 2023-11-15-preview
    source: swagger
    swagger-files:
      - preview/2023-11-15-preview/provisionedClusterInstances.json
      - preview/2023-11-15-preview/virtualNetworks.json
  - version: 2024-01-01
    source: swagger
    swagger-files:
      - stable/2024-01-01/provisionedClusterInstances.json
      - stable/2024-01-01/virtualNetworks.json
  - version: 2026-04-01-preview
    source: typespec
    swagger-files:
      - preview/2026-04-01-preview/openapi.json
