// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armquantum

// JobsClientCancelOptions contains the optional parameters for the JobsClient.Cancel method.
type JobsClientCancelOptions struct {
	// placeholder for future optional parameters
}

// JobsClientCreateOptions contains the optional parameters for the JobsClient.Create method.
type JobsClientCreateOptions struct {
	// placeholder for future optional parameters
}

// JobsClientGetOptions contains the optional parameters for the JobsClient.Get method.
type JobsClientGetOptions struct {
	// placeholder for future optional parameters
}

// JobsClientListOptions contains the optional parameters for the JobsClient.NewListPager method.
type JobsClientListOptions struct {
	// placeholder for future optional parameters
}

// JobsClientUpdateOptions contains the optional parameters for the JobsClient.Update method.
type JobsClientUpdateOptions struct {
	// placeholder for future optional parameters
}

// ProvidersClientListOptions contains the optional parameters for the ProvidersClient.NewListPager method.
type ProvidersClientListOptions struct {
	// placeholder for future optional parameters
}

// QuotasClientListOptions contains the optional parameters for the QuotasClient.NewListPager method.
type QuotasClientListOptions struct {
	// placeholder for future optional parameters
}

// SessionsClientCloseOptions contains the optional parameters for the SessionsClient.Close method.
type SessionsClientCloseOptions struct {
	// placeholder for future optional parameters
}

// SessionsClientGetOptions contains the optional parameters for the SessionsClient.Get method.
type SessionsClientGetOptions struct {
	// placeholder for future optional parameters
}

// SessionsClientJobsListOptions contains the optional parameters for the SessionsClient.NewJobsListPager method.
type SessionsClientJobsListOptions struct {
	// placeholder for future optional parameters
}

// SessionsClientListOptions contains the optional parameters for the SessionsClient.NewListPager method.
type SessionsClientListOptions struct {
	// placeholder for future optional parameters
}

// SessionsClientOpenOptions contains the optional parameters for the SessionsClient.Open method.
type SessionsClientOpenOptions struct {
	// placeholder for future optional parameters
}

// StorageClientGetSasURIOptions contains the optional parameters for the StorageClient.GetSasURI method.
type StorageClientGetSasURIOptions struct {
	// placeholder for future optional parameters
}

// TopLevelItemsClientListOptions contains the optional parameters for the TopLevelItemsClient.NewListPager method.
type TopLevelItemsClientListOptions struct {
	// placeholder for future optional parameters
}

