id: service-label
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
    - if:
      - payloadType: Pull_Request
      # If a PR changes no files, "includesModifiedFiles()" incorrectly returns "true" instead of "false",
      # which adds all labels to the PR.
      # Workaround by first checking "filesMatchPattern()", which correctly returns "false".
      - filesMatchPattern:
          pattern: ".*"
          matchAny: true
      then:
      - if:
        - includesModifiedFiles:
            files:
            - specification/apimanagement/resource-manager
        then:
        - addLabel:
            label: API Management
      - if:
        - includesModifiedFiles:
            files:
            - specification/compute/resource-manager
        then:
        - addLabel:
            label: Compute
      - if:
        - includesModifiedFiles:
            files:
            - specification/network/resource-manager
        then:
        - addLabel:
            label: Network
      - if:
        - includesModifiedFiles:
            files:
            - specification/sql/resource-manager
        then:
        - addLabel:
            label: SQL
      - if:
        - includesModifiedFiles:
            files:
            - specification/storage/resource-manager
        then:
        - addLabel:
            label: Storage
      - if:
        - includesModifiedFiles:
            files:
            - specification/synapse
        then:
        - addLabel:
            label: Synapses
      description: 
    - if:
      - payloadType: Pull_Request
      # If a PR changes no files, "includesModifiedFiles()" incorrectly returns "true" instead of "false",
      # which adds all labels to the PR.
      # Workaround by first checking "filesMatchPattern()", which correctly returns "false".
      - filesMatchPattern:
          pattern: ".*"
          matchAny: true
      then:
      - if:
        - includesModifiedFiles:
            files:
            - dev/cognitiveservices/data-plane/Language/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Cognitive Services
      - if:
        - includesModifiedFiles:
            files:
            - specification/analysisservices/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Analysis Services
      - if:
        - includesModifiedFiles:
            files:
            - specification/alertsmanagement/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Alerts Management
      - if:
        - includesModifiedFiles:
            files:
            - specification/apimanagement/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: API Management
      - if:
        - includesModifiedFiles:
            files:
            - specification/applicationinsights/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Insights
      - if:
        - includesModifiedFiles:
            files:
            - specification/applicationinsights/data-plane/Monitor.Exporters/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Monitor - Exporter
      - if:
        - includesModifiedFiles:
            files:
            - specification/authorization/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Authorization
      - if:
        - includesModifiedFiles:
            files:
            - specification/automation/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Automation
      - if:
        - includesModifiedFiles:
            files:
            - specification/batch/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Batch
      - if:
        - includesModifiedFiles:
            files:
            - specification/billing/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Billing
      - if:
        - includesModifiedFiles:
            files:
            - specification/cdn/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Network - CDN
      - if:
        - includesModifiedFiles:
            files:
            - specification/cognitiveservices/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Cognitive Services
      - if:
        - includesModifiedFiles:
            files:
            - specification/cognitiveservices/data-plane/Language/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Cognitive - Language
      - if:
        - includesModifiedFiles:
            files:
            - specification/compute/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Compute
      - if:
        - includesModifiedFiles:
            files:
            - specification/containerinstance/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Container Instances
      - if:
        - includesModifiedFiles:
            files:
            - specification/containerregistry/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Container Registry
      - if:
        - includesModifiedFiles:
            files:
            - specification/containerservice/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Container Service
      - if:
        - includesModifiedFiles:
            files:
            - specification/containerservice/Fleet.Management
            - specification/containerservice/fleet
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Container Service Fleet
      - if:
        - includesModifiedFiles:
            files:
            - specification/cosmos-db/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Cosmos
      - if:
        - includesModifiedFiles:
            files:
            - specification/customer-insights/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Customer Insights
      - if:
        - includesModifiedFiles:
            files:
            - specification/datafactory/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Data Factory
      - if:
        - includesModifiedFiles:
            files:
            - specification/datalake-analytics/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Data Lake Analytics
      - if:
        - includesModifiedFiles:
            files:
            - specification/datalake-store/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Data Lake Store
      - if:
        - includesModifiedFiles:
            files:
            - specification/datamigration/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Data Migration
      - if:
        - includesModifiedFiles:
            files:
            - specification/deviceupdate/data-plane/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Device Update
      - if:
        - includesModifiedFiles:
            files:
            - specification/devtestlabs/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Devtestlab
      - if:
        - includesModifiedFiles:
            files:
            - specification/dns/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Network - DNS
      - if:
        - includesModifiedFiles:
            files:
            - specification/eventgrid/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Event Grid
      - if:
        - includesModifiedFiles:
            files:
            - specification/eventhub/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Event Hubs
      - if:
        - includesModifiedFiles:
            files:
            - specification/hdinsight/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: HDInsight
      - if:
        - includesModifiedFiles:
            files:
            - specification/intune/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Intune
      - if:
        - includesModifiedFiles:
            files:
            - specification/iothub/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: IotHub
      - if:
        - includesModifiedFiles:
            files:
            - specification/keyvault/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: KeyVault
      - if:
        - includesModifiedFiles:
            files:
            - specification/logic/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Logic App
      - if:
        - includesModifiedFiles:
            files:
            - specification/machinelearning/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Machine Learning
      - if:
        - includesModifiedFiles:
            files:
            - specification/machinelearningcompute/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Machine Learning Compute
      - if:
        - includesModifiedFiles:
            files:
            - specification/mediaservices/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Media Services
      - if:
        - includesModifiedFiles:
            files:
            - specification/monitor/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Monitor
      - if:
        - includesModifiedFiles:
            files:
            - specification/mysql/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: MySQL
      - if:
        - includesModifiedFiles:
            files:
            - specification/network/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Network
      - if:
        - includesModifiedFiles:
            files:
            - specification/notificationhubs/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Notification Hub
      - if:
        - includesModifiedFiles:
            files:
            - specification/operationalinsights/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Monitor - Operational Insights
      - if:
        - includesModifiedFiles:
            files:
            - specification/operationsmanagement/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Operations Management
      - if:
        - includesModifiedFiles:
            files:
            - specification/peering/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Peering
      - if:
        - includesModifiedFiles:
            files:
            - specification/policyinsights/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Policy Insights
      - if:
        - includesModifiedFiles:
            files:
            - specification/postgresql/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: PostgreSQL
      - if:
        - includesModifiedFiles:
            files:
            - specification/provisioningservices/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: PostgreSQL
      - if:
        - includesModifiedFiles:
            files:
            - specification/recoveryservices/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: RecoveryServices
      - if:
        - includesModifiedFiles:
            files:
            - specification/recoveryservicesbackup/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Recovery Services Backup
      - if:
        - includesModifiedFiles:
            files:
            - specification/recoveryservicessiterecovery/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Recovery Services Site-Recovery
      - if:
        - includesModifiedFiles:
            files:
            - specification/redis/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Redis Cache
      - if:
        - includesModifiedFiles:
            files:
            - specification/relay/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Relay
      - if:
        - includesModifiedFiles:
            files:
            - specification/scheduler/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Scheduler
      - if:
        - includesModifiedFiles:
            files:
            - specification/search/data-plane/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Search
      - if:
        - includesModifiedFiles:
            files:
            - specification/search/resource-manager/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Search
      - if:
        - includesModifiedFiles:
            files:
            - specification/service-map/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Service Map
      - if:
        - includesModifiedFiles:
            files:
            - specification/servicebus/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Service Bus
      - if:
        - includesModifiedFiles:
            files:
            - specification/servicefabric/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Service Fabric
      - if:
        - includesModifiedFiles:
            files:
            - specification/sql/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: SQL
      - if:
        - includesModifiedFiles:
            files:
            - specification/storage/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Storage
      - if:
        - includesModifiedFiles:
            files:
            - specification/storageimportexport/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Import Export
      - if:
        - includesModifiedFiles:
            files:
            - specification/storagesync/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: StorageSync
      - if:
        - includesModifiedFiles:
            files:
            - specification/storsimple8000series/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Storsimple
      - if:
        - includesModifiedFiles:
            files:
            - specification/streamanalytics/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Stream Analytics
      - if:
        - includesModifiedFiles:
            files:
            - specification/subscriptions/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Subscription
      - if:
        - includesModifiedFiles:
            files:
            - specification/synapse/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Synapses
      - if:
        - includesModifiedFiles:
            files:
            - specification/loadtestservice/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Load Test Service
      - if:
        - includesModifiedFiles:
            files:
            - specification/maps/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Maps
      - if:
        - includesModifiedFiles:
            files:
            - specification/purview/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Purview
      - if:
        - includesModifiedFiles:
            files:
            - specification/timeseriesinsights/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: TimeseriesInsights
      - if:
        - includesModifiedFiles:
            files:
            - specification/trafficmanager/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Network - Traffic Manager
      - if:
        - includesModifiedFiles:
            files:
            - specification/web/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Web Apps
      - if:
        - includesModifiedFiles:
            files:
            - profile/
            excludedFiles:
            - ''
        then:
        - addLabel:
            label: Profile
      description: 
onFailure: 
onSuccess: 
