versions:
  - version: 2022-10-01-preview
    source: swagger
    swagger-files:
      - preview/2022-10-01-preview/TrafficController.json
  - version: 2023-11-01
    source: typespec
    swagger-files:
      - stable/2023-11-01/TrafficController.json
  - version: 2024-05-01-preview
    source: typespec
    swagger-files:
      - preview/2024-05-01-preview/TrafficController.json
  - version: 2025-01-01
    source: typespec
    swagger-files:
      - stable/2025-01-01/TrafficController.json
  - version: 2025-03-01-preview
    source: typespec
    swagger-files:
      - preview/2025-03-01-preview/TrafficController.json
