versions:
  - version: "1.0"
    source: swagger
    swagger-files:
      - stable/1.0/appconfiguration.json
  - version: 2022-11-01-preview
    source: swagger
    swagger-files:
      - preview/2022-11-01-preview/appconfiguration.json
  - version: 2023-05-01-preview
    source: swagger
    swagger-files:
      - preview/2023-05-01-preview/appconfiguration.json
  - version: 2023-10-01
    source: swagger
    swagger-files:
      - stable/2023-10-01/appconfiguration.json
  - version: 2023-11-01
    source: typespec
    swagger-files:
      - stable/2023-11-01/appconfiguration.json
  - version: 2024-09-01
    source: typespec
    swagger-files:
      - stable/2024-09-01/appconfiguration.json
  - version: 2026-04-01
    source: typespec
    swagger-files:
      - stable/2026-04-01/appconfiguration.json
