Set-Location "E:\AzureWork\mcgallan\azure-rest-api-specs"

npx tsmv "E:\AzureWork\mcgallan\azure-rest-api-specs\sparse-spec\specification\monitor original Swagger\stable\ActivityLogs" "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\resource-manager\Microsoft.Insights\Insights\stable\2015-04-01\activityLogs.json" --outputFolder "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\outputFolder\activitylogs" --ignoreDescription false
npx tsmv "E:\AzureWork\mcgallan\azure-rest-api-specs\sparse-spec\specification\monitor original Swagger\stable\AlertRulesIncidents" "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\resource-manager\Microsoft.Insights\Insights\stable\2016-03-01\alertRulesIncidents.json" --outputFolder "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\outputFolder\alertrulesincidents" --ignoreDescription false
npx tsmv "E:\AzureWork\mcgallan\azure-rest-api-specs\sparse-spec\specification\monitor original Swagger\stable\AutoScale" "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\resource-manager\Microsoft.Insights\Insights\stable\2022-10-01\autoScale.json" --outputFolder "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\outputFolder\autoscale" --ignoreDescription false
npx tsmv "E:\AzureWork\mcgallan\azure-rest-api-specs\sparse-spec\specification\monitor original Swagger\stable\DataCollection" "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\resource-manager\Microsoft.Insights\Insights\stable\2024-03-11\dataCollection.json" --outputFolder "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\outputFolder\datacollection" --ignoreDescription false
npx tsmv "E:\AzureWork\mcgallan\azure-rest-api-specs\sparse-spec\specification\monitor original Swagger\stable\LogProfiles" "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\resource-manager\Microsoft.Insights\Insights\stable\2016-03-01\logProfiles.json" --outputFolder "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\outputFolder\logprofiles" --ignoreDescription false
npx tsmv "E:\AzureWork\mcgallan\azure-rest-api-specs\sparse-spec\specification\monitor original Swagger\stable\MetricBaselines" "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\resource-manager\Microsoft.Insights\Insights\stable\2019-03-01\metricBaselines.json" --outputFolder "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\outputFolder\metricbaselines" --ignoreDescription false
npx tsmv "E:\AzureWork\mcgallan\azure-rest-api-specs\sparse-spec\specification\monitor original Swagger\stable\Metrics" "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\resource-manager\Microsoft.Insights\Insights\stable\2024-02-01\metrics.json" --outputFolder "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\outputFolder\metrics" --ignoreDescription false
npx tsmv "E:\AzureWork\mcgallan\azure-rest-api-specs\sparse-spec\specification\monitor original Swagger\stable\NetworkSecurityPerimeter" "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\resource-manager\Microsoft.Insights\Insights\stable\2021-10-01\networkSecurityPerimeter.json" --outputFolder "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\outputFolder\networksecurityperimeter" --ignoreDescription false
npx tsmv "E:\AzureWork\mcgallan\azure-rest-api-specs\sparse-spec\specification\monitor original Swagger\stable\ServiceDiagnosticSetting" "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\resource-manager\Microsoft.Insights\Insights\stable\2016-09-01\serviceDiagnosticsSettings.json" --outputFolder "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\outputFolder\servicediagnosticsetting" --ignoreDescription false
npx tsmv "E:\AzureWork\mcgallan\azure-rest-api-specs\sparse-spec\specification\monitor original Swagger\preview\ActionGroups" "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\resource-manager\Microsoft.Insights\Insights\preview\2024-10-01-preview\actionGroups.json" --outputFolder "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\outputFolder\actiongroups" --ignoreDescription false
npx tsmv "E:\AzureWork\mcgallan\azure-rest-api-specs\sparse-spec\specification\monitor original Swagger\preview\ActivityLogAlerts" "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\resource-manager\Microsoft.Insights\Insights\preview\2023-01-01-preview\activityLogAlerts.json" --outputFolder "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\outputFolder\activitylogalerts" --ignoreDescription false
npx tsmv "E:\AzureWork\mcgallan\azure-rest-api-specs\sparse-spec\specification\monitor original Swagger\preview\MetricAlert" "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\resource-manager\Microsoft.Insights\Insights\preview\2024-03-01-preview\metricAlert.json" --outputFolder "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\outputFolder\metricalert" --ignoreDescription false
npx tsmv "E:\AzureWork\mcgallan\azure-rest-api-specs\sparse-spec\specification\monitor original Swagger\preview\PrivateLinkScopes" "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\resource-manager\Microsoft.Insights\Insights\preview\2023-06-01-preview\privateLinkScopes.json" --outputFolder "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\outputFolder\privatelinkscopes" --ignoreDescription false
npx tsmv "E:\AzureWork\mcgallan\azure-rest-api-specs\sparse-spec\specification\monitor original Swagger\preview\ScheduledQueryRule" "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\resource-manager\Microsoft.Insights\Insights\preview\2025-01-01-preview\scheduledQueryRule.json" --outputFolder "E:\AzureWork\mcgallan\azure-rest-api-specs\specification\monitor\outputFolder\scheduledqueryrule" --ignoreDescription false
