versions:
  - version: 2018-05-01-preview
    source: swagger
    swagger-files:
      - ../preview/2018-05-01-preview/authorization-AccessReviewCalls.json
  - version: 2021-03-01-preview
    source: swagger
    swagger-files:
      - ../preview/2021-03-01-preview/authorization-AccessReviewCalls.json
  - version: 2021-07-01-preview
    source: swagger
    swagger-files:
      - ../preview/2021-07-01-preview/authorization-AccessReviewCalls.json
  - version: 2021-11-16-preview
    source: swagger
    swagger-files:
      - ../preview/2021-11-16-preview/authorization-AccessReviewCalls.json
  - version: 2021-12-01-preview
    source: typespec
    swagger-files:
      - ../preview/2021-12-01-preview/authorization-AccessReviewCalls.json
