versions:
  - version: 2025-06-01-preview
    source: typespec
    swagger-files:
      - preview/2025-06-01-preview/keys.json
  - version: 2025-07-01
    source: typespec
    swagger-files:
      - stable/2025-07-01/keys.json
  - version: 2026-01-01-preview
    source: typespec
    swagger-files:
      - preview/2026-01-01-preview/keys.json
  - version: 2026-03-01-preview
    source: typespec
    swagger-files:
      - preview/2026-03-01-preview/keys.json
  - version: 2026-05-01-preview
    source: typespec
    swagger-files:
      - preview/2026-05-01-preview/keys.json
  - version: "7.5"
    source: typespec
    swagger-files:
      - stable/7.5/keys.json
  - version: "7.6"
    source: typespec
    swagger-files:
      - stable/7.6/keys.json
  - version: 7.6-preview.2
    source: typespec
    swagger-files:
      - preview/7.6-preview.2/keys.json
