export { canonicalizeOperations, } from "./canonicalize.js";
export { formatResult, main, parseArgs } from "./cli.js";
export { createApproveBreakingChangeCodeFix } from "./codefixes.js";
export { compileService } from "./compile.js";
export { $approvedBreakingChange, $approvedUnversionedChange, findSuppressions, findUnversionedSuppressions, getSuppressions, getUnversionedSuppressions, } from "./decorators.js";
export { emitFindingDiagnostics } from "./diagnostics.js";
export * from "./diff-engine.js";
export * from "./diff-operations.js";
export * from "./diff-types.js";
export { $lib, BreakingChangeStateKeys } from "./lib.js";
export { matchOperations } from "./match.js";
export { getOperationIdentity, identityKey, normalizePath, resolveOperationIdentities, } from "./operation-identity.js";
export { resolveOrigin } from "./origin.js";
export * from "./orchestrator.js";
export * from "./policy.js";
export { resolveFindingLocation } from "./resolve-location.js";
export * from "./reporter-console.js";
export * from "./reporter-github.js";
export * from "./reporter-json.js";
export * from "./reporter-markdown.js";
export * from "./suppression-guidance.js";
export * from "./suppression.js";
export { isOperationIdentity, isServiceIdentity } from "./types.js";
export { buildComparisonPairs, buildPhaseAPairs, buildPhaseBPairs, createVersionedView, defaultVersionClassifier, enumerateVersions, } from "./versions.js";
//# sourceMappingURL=index.js.map