versions:
  - version: 2025-05-01
    source: typespec
    swagger-files:
      - ../stable/2025-05-01/applicationGateway.json
      - ../stable/2025-05-01/expressRoute.json
      - ../stable/2025-05-01/firewall.json
      - ../stable/2025-05-01/loadBalancer.json
      - ../stable/2025-05-01/networkGateway.json
      - ../stable/2025-05-01/networkManager.json
      - ../stable/2025-05-01/networkSecurityPerimeter.json
      - ../stable/2025-05-01/networkWatcher.json
      - ../stable/2025-05-01/networkingOperations.json
      - ../stable/2025-05-01/virtualNetwork.json
      - ../stable/2025-05-01/virtualWan.json
      - ../stable/2025-05-01/firewallPolicy.json
      - ../stable/2025-05-01/azureWebCategory.json
      - ../stable/2025-05-01/serviceGateway.json
      - ../stable/2025-05-01/virtualNetworkAppliance.json
      - ../stable/2025-05-01/common.json
  - version: 2025-07-01
    source: typespec
    swagger-files:
      - ../stable/2025-07-01/applicationGateway.json
      - ../stable/2025-07-01/expressRoute.json
      - ../stable/2025-07-01/firewall.json
      - ../stable/2025-07-01/loadBalancer.json
      - ../stable/2025-07-01/networkGateway.json
      - ../stable/2025-07-01/networkManager.json
      - ../stable/2025-07-01/networkSecurityPerimeter.json
      - ../stable/2025-07-01/networkWatcher.json
      - ../stable/2025-07-01/networkingOperations.json
      - ../stable/2025-07-01/virtualNetwork.json
      - ../stable/2025-07-01/virtualWan.json
      - ../stable/2025-07-01/firewallPolicy.json
      - ../stable/2025-07-01/azureWebCategory.json
      - ../stable/2025-07-01/serviceGateway.json
      - ../stable/2025-07-01/virtualNetworkAppliance.json
      - ../stable/2025-07-01/interconnectGroup.json
      - ../stable/2025-07-01/common.json
