versions:
  - version: 2015-10-01-preview
    source: swagger
    swagger-files:
      - preview/2015-10-01-preview/policy.json
  - version: 2016-04-01
    source: swagger
    swagger-files:
      - stable/2016-04-01/policy.json
  - version: 2016-12-01
    source: swagger
    swagger-files:
      - stable/2016-12-01/policyAssignments.json
      - stable/2016-12-01/policyDefinitions.json
  - version: 2017-06-01-preview
    source: swagger
    swagger-files:
      - preview/2017-06-01-preview/policyAssignments.json
      - preview/2017-06-01-preview/policySetDefinitions.json
  - version: 2018-03-01
    source: swagger
    swagger-files:
      - stable/2018-03-01/policyAssignments.json
      - stable/2018-03-01/policyDefinitions.json
      - stable/2018-03-01/policySetDefinitions.json
  - version: 2018-05-01
    source: swagger
    swagger-files:
      - stable/2018-05-01/policyAssignments.json
      - stable/2018-05-01/policyDefinitions.json
      - stable/2018-05-01/policySetDefinitions.json
  - version: 2019-01-01
    source: swagger
    swagger-files:
      - stable/2019-01-01/policyAssignments.json
      - stable/2019-01-01/policyDefinitions.json
      - stable/2019-01-01/policySetDefinitions.json
  - version: 2019-06-01
    source: swagger
    swagger-files:
      - stable/2019-06-01/policyAssignments.json
      - stable/2019-06-01/policyDefinitions.json
      - stable/2019-06-01/policySetDefinitions.json
  - version: 2019-09-01
    source: swagger
    swagger-files:
      - stable/2019-09-01/policyAssignments.json
      - stable/2019-09-01/policyDefinitions.json
      - stable/2019-09-01/policySetDefinitions.json
  - version: 2020-03-01
    source: swagger
    swagger-files:
      - stable/2020-03-01/policyAssignments.json
      - stable/2020-03-01/policyDefinitions.json
      - stable/2020-03-01/policySetDefinitions.json
  - version: 2020-07-01-preview
    source: swagger
    swagger-files:
      - preview/2020-07-01-preview/policyExemptions.json
  - version: 2020-09-01
    source: swagger
    swagger-files:
      - stable/2020-09-01/dataPolicyManifests.json
      - stable/2020-09-01/policyAssignments.json
      - stable/2020-09-01/policyDefinitions.json
      - stable/2020-09-01/policySetDefinitions.json
  - version: 2021-06-01
    source: swagger
    swagger-files:
      - stable/2021-06-01/policyAssignments.json
      - stable/2021-06-01/policyDefinitions.json
      - stable/2021-06-01/policySetDefinitions.json
  - version: 2022-06-01
    source: swagger
    swagger-files:
      - stable/2022-06-01/policyAssignments.json
  - version: 2022-07-01-preview
    source: swagger
    swagger-files:
      - preview/2022-07-01-preview/policyExemptions.json
  - version: 2022-08-01-preview
    source: swagger
    swagger-files:
      - preview/2022-08-01-preview/policyVariableValues.json
      - preview/2022-08-01-preview/policyVariables.json
  - version: 2023-04-01
    source: swagger
    swagger-files:
      - stable/2023-04-01/policyAssignments.json
      - stable/2023-04-01/policyDefinitionVersions.json
      - stable/2023-04-01/policyDefinitions.json
      - stable/2023-04-01/policySetDefinitionVersions.json
      - stable/2023-04-01/policySetDefinitions.json
  - version: 2024-04-01
    source: swagger
    swagger-files:
      - stable/2024-04-01/policyAssignments.json
  - version: 2024-05-01
    source: swagger
    swagger-files:
      - stable/2024-05-01/policyAssignments.json
      - stable/2024-05-01/policyDefinitionVersions.json
      - stable/2024-05-01/policyDefinitions.json
      - stable/2024-05-01/policySetDefinitionVersions.json
      - stable/2024-05-01/policySetDefinitions.json
  - version: 2024-12-01-preview
    source: swagger
    swagger-files:
      - preview/2024-12-01-preview/policyExemptions.json
      - preview/2024-12-01-preview/policyVariableValues.json
      - preview/2024-12-01-preview/policyVariables.json
  - version: 2025-01-01
    source: swagger
    swagger-files:
      - stable/2025-01-01/policyAssignments.json
      - stable/2025-01-01/policyDefinitionVersions.json
      - stable/2025-01-01/policyDefinitions.json
      - stable/2025-01-01/policySetDefinitionVersions.json
      - stable/2025-01-01/policySetDefinitions.json
  - version: 2025-03-01
    source: typespec
    swagger-files:
      - stable/2025-03-01/openapi.json
  - version: 2025-11-01
    source: typespec
    swagger-files:
      - stable/2025-11-01/openapi.json
  - version: 2025-12-01-preview
    source: typespec
    swagger-files:
      - preview/2025-12-01-preview/openapi.json
  - version: 2026-01-01-preview
    source: typespec
    swagger-files:
      - preview/2026-01-01-preview/openapi.json
  - version: 2026-06-01
    source: typespec
    swagger-files:
      - stable/2026-06-01/openapi.json
  - version: 2026-07-01
    source: typespec
    swagger-files:
      - stable/2026-07-01/openapi.json
