versions:
  - version: 2025-03-01
    source: typespec
    swagger-files:
      - stable/2025-03-01/openapi.json
  - version: 2025-11-01
    source: typespec
    swagger-files:
      - stable/2025-11-01/openapi.json
  - version: 2025-12-01-preview
    source: typespec
    swagger-files:
      - preview/2025-12-01-preview/openapi.json
  - version: 2026-01-01-preview
    source: typespec
    swagger-files:
      - preview/2026-01-01-preview/openapi.json
  - version: 2026-06-01
    source: typespec
    swagger-files:
      - stable/2026-06-01/openapi.json
