versions:
  - version: "1.0"
    source: swagger
    swagger-files:
      - stable/1.0/route.json
  - version: 2023-10-01-preview
    source: swagger
    swagger-files:
      - preview/2023-10-01-preview/route.json
  - version: 2024-04-01-preview
    source: swagger
    swagger-files:
      - preview/2024-04-01-preview/route.json
  - version: 2024-07-01-preview
    source: swagger
    swagger-files:
      - preview/2024-07-01-preview/route.json
  - version: 2025-01-01
    source: typespec
    swagger-files:
      - stable/2025-01-01/route.json
