// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.datamigration.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Enum mapping of SMO LoginType.
 */
public final class LoginType extends ExpandableStringEnum<LoginType> {
    /**
     * WindowsUser.
     */
    public static final LoginType WINDOWS_USER = fromString("WindowsUser");

    /**
     * WindowsGroup.
     */
    public static final LoginType WINDOWS_GROUP = fromString("WindowsGroup");

    /**
     * SqlLogin.
     */
    public static final LoginType SQL_LOGIN = fromString("SqlLogin");

    /**
     * Certificate.
     */
    public static final LoginType CERTIFICATE = fromString("Certificate");

    /**
     * AsymmetricKey.
     */
    public static final LoginType ASYMMETRIC_KEY = fromString("AsymmetricKey");

    /**
     * ExternalUser.
     */
    public static final LoginType EXTERNAL_USER = fromString("ExternalUser");

    /**
     * ExternalGroup.
     */
    public static final LoginType EXTERNAL_GROUP = fromString("ExternalGroup");

    /**
     * Creates a new instance of LoginType value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public LoginType() {
    }

    /**
     * Creates or finds a LoginType from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding LoginType.
     */
    public static LoginType fromString(String name) {
        return fromString(name, LoginType.class);
    }

    /**
     * Gets known LoginType values.
     * 
     * @return known LoginType values.
     */
    public static Collection<LoginType> values() {
        return values(LoginType.class);
    }
}
