// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.datamigration.models;

import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * The name of the quota.
 */
@Immutable
public final class QuotaName implements JsonSerializable<QuotaName> {
    /*
     * The localized name of the quota
     */
    private String localizedValue;

    /*
     * The unlocalized name (or ID) of the quota
     */
    private String value;

    /**
     * Creates an instance of QuotaName class.
     */
    private QuotaName() {
    }

    /**
     * Get the localizedValue property: The localized name of the quota.
     * 
     * @return the localizedValue value.
     */
    public String localizedValue() {
        return this.localizedValue;
    }

    /**
     * Get the value property: The unlocalized name (or ID) of the quota.
     * 
     * @return the value value.
     */
    public String value() {
        return this.value;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("localizedValue", this.localizedValue);
        jsonWriter.writeStringField("value", this.value);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of QuotaName from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of QuotaName if the JsonReader was pointing to an instance of it, or null if it was pointing
     * to JSON null.
     * @throws IOException If an error occurs while reading the QuotaName.
     */
    public static QuotaName fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            QuotaName deserializedQuotaName = new QuotaName();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("localizedValue".equals(fieldName)) {
                    deserializedQuotaName.localizedValue = reader.getString();
                } else if ("value".equals(fieldName)) {
                    deserializedQuotaName.value = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedQuotaName;
        });
    }
}
