// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.datamigration.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Defines values for ResourceType.
 */
public final class ResourceType extends ExpandableStringEnum<ResourceType> {
    /**
     * SqlMi.
     */
    public static final ResourceType SQL_MI = fromString("SqlMi");

    /**
     * SqlVm.
     */
    public static final ResourceType SQL_VM = fromString("SqlVm");

    /**
     * SqlDb.
     */
    public static final ResourceType SQL_DB = fromString("SqlDb");

    /**
     * MongoToCosmosDbMongo.
     */
    public static final ResourceType MONGO_TO_COSMOS_DB_MONGO = fromString("MongoToCosmosDbMongo");

    /**
     * Creates a new instance of ResourceType value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public ResourceType() {
    }

    /**
     * Creates or finds a ResourceType from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding ResourceType.
     */
    public static ResourceType fromString(String name) {
        return fromString(name, ResourceType.class);
    }

    /**
     * Gets known ResourceType values.
     * 
     * @return known ResourceType values.
     */
    public static Collection<ResourceType> values() {
        return values(ResourceType.class);
    }
}
