versions:
  - version: 2023-08-24-preview
    source: swagger
    swagger-files:
      - ../data-plane/Messages/preview/2023-08-24-preview/CommunicationServicesMessages.json
  - version: 2024-02-01
    source: typespec
    swagger-files:
      - ../data-plane/Messages/stable/2024-02-01/communicationservicesmessages.json
  - version: 2024-08-30
    source: typespec
    swagger-files:
      - ../data-plane/Messages/stable/2024-08-30/communicationservicesmessages.json
  - version: 2025-01-15-preview
    source: typespec
    swagger-files:
      - ../data-plane/Messages/preview/2025-01-15-preview/communicationservicesmessages.json
  - version: 2025-04-01-preview
    source: typespec
    swagger-files:
      - ../data-plane/Messages/preview/2025-04-01-preview/communicationservicesmessages.json
  - version: 2025-09-01-preview
    source: typespec
    swagger-files:
      - ../data-plane/Messages/preview/2025-09-01-preview/communicationservicesmessages.json
