/**
 * PLACEHOLDER
 * Add readme and sample
 */
import "./main.tsp";
import "@azure-tools/typespec-client-generator-core";

using Azure.ClientGenerator.Core;
using PurviewUnifiedCatalog;

namespace Customizations;

// @@clientName(ListCriticalDataElementAsync, "ListCriticalDataElement");
// @@clientName(CreateCriticalDataElementAsync, "CreateCriticalDataElement");
// @@clientName(GetCriticalDataElementByIdAsync, "GetCriticalDataElementById");
// @@clientName(UpdateCriticalDataElementAsync, "UpdateCriticalDataElement");
// @@clientName(DeleteCriticalDataElementByIdAsync,
//   "DeleteCriticalDataElementById"
// );
// @@clientName(ListCriticalDataElementRelationshipsAsync,
//   "ListCriticalDataElementRelationships"
// );
// @@clientName(CreateCriticalDataElementRelationshipAsync,
//   "CreateCriticalDataElementRelationship"
// );
// @@clientName(DeleteCriticalDataElementRelationshipAsync,
//   "DeleteCriticalDataElementRelationship"
// );
// @@clientName(GetCriticalDataElementFacetsAsync, "GetCriticalDataElementFacets");
// @@clientName(CreateCriticalDataColumnAsync, "CreateCriticalDataColumn");
// @@clientName(ListCriticalDataColumnAsync, "ListCriticalDataColumn");
// @@clientName(GetCriticalDataColumnByIdAsync, "GetCriticalDataColumnById");
// @@clientName(CreateCriticalDataColumnRelationshipAsync,
//   "CreateCriticalDataColumnRelationship"
// );
// @@clientName(ListCriticalDataColumnRelationshipsAsync,
//   "ListCriticalDataColumnRelationships"
// );
// @@clientName(DeleteCriticalDataColumnRelationshipAsync,
//   "DeleteCriticalDataColumnRelationship"
// );
// @@clientName(ListDataAssetsAsync, "ListDataAssets");
// @@clientName(CreateDataAssetAsync, "CreateDataAsset");
// @@clientName(QueryDataAssetsAsync, "QueryDataAssets");
// @@clientName(GetDataAssetByIdAsync, "GetDataAssetById");
// @@clientName(UpdateDataAssetAsync, "UpdateDataAsset");
// @@clientName(DeleteDataAssetByIdAsync, "DeleteDataAssetById");
// @@clientName(ListDataAssetRelationshipsAsync, "ListDataAssetRelationships");
// @@clientName(CreateDataAssetRelationshipAsync, "CreateDataAssetRelationship");
// @@clientName(DeleteDataAssetRelationshipAsync, "DeleteDataAssetRelationship");
// @@clientName(ListDataProductsAsync, "ListDataProducts");
// @@clientName(CreateDataProductAsync, "CreateDataProduct");
// @@clientName(QueryDataProductsAsync, "QueryDataProducts");
// @@clientName(GetDataProductFacetsAsync, "GetDataProductFacets");
// @@clientName(GetDataProductByIdAsync, "GetDataProductById");
// @@clientName(UpdateDataProductAsync, "UpdateDataProduct");
// @@clientName(DeleteDataProductByIdAsync, "DeleteDataProductById");
// @@clientName(ListDataProductRelationshipsAsync, "ListDataProductRelationships");
// @@clientName(CreateDataProductRelationshipAsync,
//   "CreateDataProductRelationship"
// );
// @@clientName(DeleteDataProductRelationshipAsync,
//   "DeleteDataProductRelationship"
// );
// @@clientName(EnumerateDomainsAsync, "EnumerateDomains");
// @@clientName(CreateDomainAsync, "CreateDomain");
// @@clientName(UpdateDomainAsync, "UpdateDomain");
// @@clientName(GetDomainByIdAsync, "GetDomainById");
// @@clientName(DeleteDomainByIdAsync, "DeleteDomainById");
// @@clientName(CreateTermAsync, "CreateTerm");
// @@clientName(ListTermAsync, "ListTerm");
// @@clientName(UpdateTermAsync, "UpdateTerm");
// @@clientName(GetTermAsync, "GetTerm");
// @@clientName(DeleteTermAsync, "DeleteTerm");
// @@clientName(QueryTermsAsync, "QueryTerms");
// @@clientName(GetTermFacetsAsync, "GetTermFacets");
// @@clientName(ListHierarchyTermsAsync, "ListHierarchyTerms");
// @@clientName(AddRelatedEntityAsync, "AddRelatedEntity");
// @@clientName(DeleteRelatedTermAsync, "DeleteRelatedTerm");
// @@clientName(ListRelatedEntitiesAsync, "ListRelatedEntities");
// @@clientName(ListObjectivesAsync, "ListObjectives");
// @@clientName(CreateObjectiveAsync, "CreateObjective");
// @@clientName(QueryObjectivesAsync, "QueryObjectives");
// @@clientName(GetObjectiveFacetsAsync, "GetObjectiveFacets");
// @@clientName(UpdateObjectiveAsync, "UpdateObjective");
// @@clientName(DeleteObjectiveByIdAsync, "DeleteObjectiveById");
// @@clientName(GetObjectiveByIdAsync, "GetObjectiveById");
// @@clientName(ListKeyResultsAsync, "ListKeyResults");
// @@clientName(CreateKeyResultAsync, "CreateKeyResult");
// @@clientName(GetKeyResultByIdAsync, "GetKeyResultById");
// @@clientName(UpdateKeyResultAsync, "UpdateKeyResult");
// @@clientName(DeleteKeyResultByIdAsync, "DeleteKeyResultById");
@@clientName(AudienceEnum, "PurviewUnifiedCatalogRole");
