versions:
  - version: "1.0"
    source: swagger
    swagger-files:
      - stable/1.0/search.json
  - version: 2021-11-01-preview
    source: swagger
    swagger-files:
      - preview/2021-11-01-preview/geocoding.json
  - version: 2022-02-01-preview
    source: swagger
    swagger-files:
      - preview/2022-02-01-preview/geocoding.json
  - version: 2022-09-01-preview
    source: swagger
    swagger-files:
      - preview/2022-09-01-preview/search.json
  - version: 2022-12-01-preview
    source: swagger
    swagger-files:
      - preview/2022-12-01-preview/search.json
  - version: 2023-06-01
    source: swagger
    swagger-files:
      - stable/2023-06-01/search.json
  - version: 2024-04-01-preview
    source: swagger
    swagger-files:
      - preview/2024-04-01-preview/search.json
  - version: 2025-01-01
    source: swagger
    swagger-files:
      - stable/2025-01-01/search.json
  - version: 2025-06-01-preview
    source: swagger
    swagger-files:
      - preview/2025-06-01-preview/search.json
  - version: 2026-01-01
    source: typespec
    swagger-files:
      - stable/2026-01-01/search.json
