versions:
  - version: 2024-08-15-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ComputeSchedule/preview/2024-08-15-preview/computeschedule.json
  - version: 2024-10-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ComputeSchedule/stable/2024-10-01/computeschedule.json
  - version: 2025-05-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ComputeSchedule/stable/2025-05-01/computeschedule.json
  - version: 2025-04-15-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ComputeSchedule/preview/2025-04-15-preview/computeschedule.json
  - version: 2026-01-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ComputeSchedule/preview/2026-01-01-preview/computeschedule.json
  - version: 2026-03-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ComputeSchedule/preview/2026-03-01-preview/computeschedule.json
  - version: 2026-04-15-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ComputeSchedule/preview/2026-04-15-preview/computeschedule.json
