// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armnetworkanalytics

// DataProductsCatalogsClientGetResponse contains the response from method DataProductsCatalogsClient.Get.
type DataProductsCatalogsClientGetResponse struct {
	// The data catalog resource.
	DataProductsCatalog
}

// DataProductsCatalogsClientListByResourceGroupResponse contains the response from method DataProductsCatalogsClient.NewListByResourceGroupPager.
type DataProductsCatalogsClientListByResourceGroupResponse struct {
	// The response of a DataProductsCatalog list operation.
	DataProductsCatalogListResult
}

// DataProductsCatalogsClientListBySubscriptionResponse contains the response from method DataProductsCatalogsClient.NewListBySubscriptionPager.
type DataProductsCatalogsClientListBySubscriptionResponse struct {
	// The response of a DataProductsCatalog list operation.
	DataProductsCatalogListResult
}

// DataProductsClientAddUserRoleResponse contains the response from method DataProductsClient.AddUserRole.
type DataProductsClientAddUserRoleResponse struct {
	// The details for role assignment response.
	RoleAssignmentDetail
}

// DataProductsClientCreateResponse contains the response from method DataProductsClient.Create.
type DataProductsClientCreateResponse struct {
	// The data product resource.
	DataProduct
}

// DataProductsClientDeleteResponse contains the response from method DataProductsClient.Delete.
type DataProductsClientDeleteResponse struct {
	// placeholder for future response values
}

// DataProductsClientGenerateStorageAccountSasTokenResponse contains the response from method DataProductsClient.GenerateStorageAccountSasToken.
type DataProductsClientGenerateStorageAccountSasTokenResponse struct {
	// Details of storage account sas token .
	AccountSasToken
}

// DataProductsClientGetResponse contains the response from method DataProductsClient.Get.
type DataProductsClientGetResponse struct {
	// The data product resource.
	DataProduct
}

// DataProductsClientListByResourceGroupResponse contains the response from method DataProductsClient.NewListByResourceGroupPager.
type DataProductsClientListByResourceGroupResponse struct {
	// The response of a DataProduct list operation.
	DataProductListResult
}

// DataProductsClientListBySubscriptionResponse contains the response from method DataProductsClient.NewListBySubscriptionPager.
type DataProductsClientListBySubscriptionResponse struct {
	// The response of a DataProduct list operation.
	DataProductListResult
}

// DataProductsClientListRolesAssignmentsResponse contains the response from method DataProductsClient.ListRolesAssignments.
type DataProductsClientListRolesAssignmentsResponse struct {
	// list role assignments.
	ListRoleAssignments
}

// DataProductsClientRemoveUserRoleResponse contains the response from method DataProductsClient.RemoveUserRole.
type DataProductsClientRemoveUserRoleResponse struct {
	// placeholder for future response values
}

// DataProductsClientRotateKeyResponse contains the response from method DataProductsClient.RotateKey.
type DataProductsClientRotateKeyResponse struct {
	// placeholder for future response values
}

// DataProductsClientUpdateResponse contains the response from method DataProductsClient.Update.
type DataProductsClientUpdateResponse struct {
	// The data product resource.
	DataProduct
}

// DataTypesClientCreateResponse contains the response from method DataTypesClient.Create.
type DataTypesClientCreateResponse struct {
	// The data type resource.
	DataType
}

// DataTypesClientDeleteDataResponse contains the response from method DataTypesClient.DeleteData.
type DataTypesClientDeleteDataResponse struct {
	// placeholder for future response values
}

// DataTypesClientDeleteResponse contains the response from method DataTypesClient.Delete.
type DataTypesClientDeleteResponse struct {
	// placeholder for future response values
}

// DataTypesClientGenerateStorageContainerSasTokenResponse contains the response from method DataTypesClient.GenerateStorageContainerSasToken.
type DataTypesClientGenerateStorageContainerSasTokenResponse struct {
	// Details of storage container account sas token .
	ContainerSasToken
}

// DataTypesClientGetResponse contains the response from method DataTypesClient.Get.
type DataTypesClientGetResponse struct {
	// The data type resource.
	DataType
}

// DataTypesClientListByDataProductResponse contains the response from method DataTypesClient.NewListByDataProductPager.
type DataTypesClientListByDataProductResponse struct {
	// The response of a DataType list operation.
	DataTypeListResult
}

// DataTypesClientUpdateResponse contains the response from method DataTypesClient.Update.
type DataTypesClientUpdateResponse struct {
	// The data type resource.
	DataType
}

// OperationsClientListResponse contains the response from method OperationsClient.NewListPager.
type OperationsClientListResponse struct {
	// A list of REST API operations supported by an Azure Resource Provider. It contains an URL link to get the next set of results.
	PagedOperation
}

