versions:
  - version: 2017-11-03-preview
    source: swagger
    swagger-files:
      - preview/2017-11-03-preview/hanaonazure.json
  - version: 2020-02-07-preview
    source: typespec
    swagger-files:
      - preview/2020-02-07-preview/hanaonazure.json
