versions:
  - version: 2015-05-01
    source: swagger
    swagger-files:
      - ../stable/2015-05-01/webTests_API.json
  - version: 2018-05-01-preview
    source: swagger
    swagger-files:
      - ../preview/2018-05-01-preview/webTests_API.json
  - version: 2020-10-05-preview
    source: swagger
    swagger-files:
      - ../preview/2020-10-05-preview/webTests_API.json
  - version: 2022-06-15
    source: typespec
    swagger-files:
      - ../stable/2022-06-15/webTests_API.json
