versions:
  - version: 2025-01-01
    source: typespec
    swagger-files:
      - stable/2025-01-01/backupShortTermRetentionPolicies.json
      - stable/2025-01-01/blobAuditing.json
      - stable/2025-01-01/databaseAdvancedThreatProtectionSettings.json
      - stable/2025-01-01/databaseAdvisors.json
      - stable/2025-01-01/databaseAutomaticTuning.json
      - stable/2025-01-01/databaseColumns.json
      - stable/2025-01-01/databaseEncryptionProtectorRevalidate.json
      - stable/2025-01-01/databaseEncryptionProtectorRevert.json
      - stable/2025-01-01/databaseExtensions.json
      - stable/2025-01-01/databaseOperations.json
      - stable/2025-01-01/databaseRecommendedActions.json
      - stable/2025-01-01/databases.json
      - stable/2025-01-01/databaseSchemas.json
      - stable/2025-01-01/databaseSecurityAlertPolicies.json
      - stable/2025-01-01/databaseSqlVulnerabilityAssessmentBaselines.json
      - stable/2025-01-01/databaseSqlVulnerabilityAssessmentExecuteScan.json
      - stable/2025-01-01/databaseSqlVulnerabilityAssessmentRuleBaselines.json
      - stable/2025-01-01/databaseSqlVulnerabilityAssessmentScanResult.json
      - stable/2025-01-01/databaseSqlVulnerabilityAssessmentScans.json
      - stable/2025-01-01/databaseSqlVulnerabilityAssessmentsSettings.json
      - stable/2025-01-01/databaseTables.json
      - stable/2025-01-01/databaseUsages.json
      - stable/2025-01-01/databaseVulnerabilityAssessmentRuleBaselines.json
      - stable/2025-01-01/databaseVulnerabilityAssessments.json
      - stable/2025-01-01/databaseVulnerabilityAssessmentScans.json
      - stable/2025-01-01/dataMaskingPolicies.json
      - stable/2025-01-01/dataMaskingRules.json
      - stable/2025-01-01/dataWarehouseUserActivities.json
      - stable/2025-01-01/deletedServers.json
      - stable/2025-01-01/distributedAvailabilityGroups.json
      - stable/2025-01-01/elasticPoolOperations.json
      - stable/2025-01-01/elasticPools.json
      - stable/2025-01-01/encryptionProtectors.json
      - stable/2025-01-01/endpointCertificates.json
      - stable/2025-01-01/failoverGroups.json
      - stable/2025-01-01/firewallRules.json
      - stable/2025-01-01/geoBackupPolicies.json
      - stable/2025-01-01/instanceFailoverGroups.json
      - stable/2025-01-01/instancePoolOperations.json
      - stable/2025-01-01/instancePools.json
      - stable/2025-01-01/iPv6FirewallRules.json
      - stable/2025-01-01/jobAgents.json
      - stable/2025-01-01/jobCredentials.json
      - stable/2025-01-01/jobExecutions.json
      - stable/2025-01-01/jobPrivateEndpoints.json
      - stable/2025-01-01/jobs.json
      - stable/2025-01-01/jobStepExecutions.json
      - stable/2025-01-01/jobSteps.json
      - stable/2025-01-01/jobTargetExecutions.json
      - stable/2025-01-01/jobTargetGroups.json
      - stable/2025-01-01/jobVersions.json
      - stable/2025-01-01/ledgerDigestUploads.json
      - stable/2025-01-01/locationCapabilities.json
      - stable/2025-01-01/longTermRetentionBackups.json
      - stable/2025-01-01/longTermRetentionManagedInstanceBackups.json
      - stable/2025-01-01/longTermRetentionPolicies.json
      - stable/2025-01-01/maintenanceWindowOptions.json
      - stable/2025-01-01/maintenanceWindows.json
      - stable/2025-01-01/managedBackupShortTermRetentionPolicies.json
      - stable/2025-01-01/managedDatabaseAdvancedThreatProtectionSettings.json
      - stable/2025-01-01/managedDatabaseColumns.json
      - stable/2025-01-01/managedDatabaseMoveOperations.json
      - stable/2025-01-01/managedDatabaseQueries.json
      - stable/2025-01-01/managedDatabaseRestoreDetails.json
      - stable/2025-01-01/managedDatabases.json
      - stable/2025-01-01/managedDatabaseSchemas.json
      - stable/2025-01-01/managedDatabaseSecurityAlertPolicies.json
      - stable/2025-01-01/managedDatabaseSecurityEvents.json
      - stable/2025-01-01/managedDatabaseSensitivityLabels.json
      - stable/2025-01-01/managedDatabaseTables.json
      - stable/2025-01-01/managedDatabaseTransparentDataEncryption.json
      - stable/2025-01-01/managedDatabaseVulnerabilityAssessmentRuleBaselines.json
      - stable/2025-01-01/managedDatabaseVulnerabilityAssessments.json
      - stable/2025-01-01/managedDatabaseVulnerabilityAssessmentScans.json
      - stable/2025-01-01/managedInstanceAdministrators.json
      - stable/2025-01-01/managedInstanceAdvancedThreatProtectionSettings.json
      - stable/2025-01-01/managedInstanceAzureAdOnlyAuthentications.json
      - stable/2025-01-01/managedInstanceDtcs.json
      - stable/2025-01-01/managedInstanceEncryptionProtectors.json
      - stable/2025-01-01/managedInstanceKeys.json
      - stable/2025-01-01/managedInstanceLongTermRetentionPolicies.json
      - stable/2025-01-01/managedInstanceOperations.json
      - stable/2025-01-01/managedInstancePrivateEndpointConnections.json
      - stable/2025-01-01/managedInstancePrivateLinkResources.json
      - stable/2025-01-01/managedInstances.json
      - stable/2025-01-01/managedInstanceTdeCertificates.json
      - stable/2025-01-01/managedInstanceVulnerabilityAssessments.json
      - stable/2025-01-01/managedLedgerDigestUploads.json
      - stable/2025-01-01/managedRestorableDroppedDatabaseBackupShortTermRetentionPolicies.json
      - stable/2025-01-01/managedServerDnsAliases.json
      - stable/2025-01-01/managedServerSecurityAlertPolicies.json
      - stable/2025-01-01/networkSecurityPerimeterConfigurations.json
      - stable/2025-01-01/operations.json
      - stable/2025-01-01/outboundFirewallRules.json
      - stable/2025-01-01/privateEndpointConnections.json
      - stable/2025-01-01/privateLinkResources.json
      - stable/2025-01-01/recoverableDatabases.json
      - stable/2025-01-01/recoverableManagedDatabases.json
      - stable/2025-01-01/replicationLinks.json
      - stable/2025-01-01/restorableDroppedDatabases.json
      - stable/2025-01-01/restorableDroppedManagedDatabases.json
      - stable/2025-01-01/restorePoints.json
      - stable/2025-01-01/sensitivityLabels.json
      - stable/2025-01-01/serverAdvancedThreatProtectionSettings.json
      - stable/2025-01-01/serverAdvisors.json
      - stable/2025-01-01/serverAutomaticTuning.json
      - stable/2025-01-01/serverAzureAdAdministrators.json
      - stable/2025-01-01/serverAzureAdOnlyAuthentications.json
      - stable/2025-01-01/serverConfigurationOptions.json
      - stable/2025-01-01/serverConnectionPolicies.json
      - stable/2025-01-01/serverDevOpsAudit.json
      - stable/2025-01-01/serverDnsAliases.json
      - stable/2025-01-01/serverKeys.json
      - stable/2025-01-01/serverOperations.json
      - stable/2025-01-01/servers.json
      - stable/2025-01-01/serverSecurityAlertPolicies.json
      - stable/2025-01-01/serverTrustCertificates.json
      - stable/2025-01-01/serverTrustGroups.json
      - stable/2025-01-01/serverUsages.json
      - stable/2025-01-01/serverVulnerabilityAssessments.json
      - stable/2025-01-01/sqlAgent.json
      - stable/2025-01-01/sqlVulnerabilityAssessmentBaseline.json
      - stable/2025-01-01/sqlVulnerabilityAssessmentExecuteScan.json
      - stable/2025-01-01/sqlVulnerabilityAssessmentRuleBaseline.json
      - stable/2025-01-01/sqlVulnerabilityAssessmentScanResult.json
      - stable/2025-01-01/sqlVulnerabilityAssessmentScans.json
      - stable/2025-01-01/sqlVulnerabilityAssessmentsSettings.json
      - stable/2025-01-01/startStopManagedInstanceSchedules.json
      - stable/2025-01-01/subscriptionUsages.json
      - stable/2025-01-01/synapseLinkWorkspaces.json
      - stable/2025-01-01/syncAgents.json
      - stable/2025-01-01/syncGroups.json
      - stable/2025-01-01/syncMembers.json
      - stable/2025-01-01/tdeCertificates.json
      - stable/2025-01-01/timeZones.json
      - stable/2025-01-01/transparentDataEncryptions.json
      - stable/2025-01-01/usages.json
      - stable/2025-01-01/virtualClusters.json
      - stable/2025-01-01/virtualNetworkRules.json
      - stable/2025-01-01/workloadClassifiers.json
      - stable/2025-01-01/workloadGroups.json
      - stable/2025-01-01/common.json
  - version: 2025-02-01-preview
    source: typespec
    swagger-files:
      - preview/2025-02-01-preview/backupShortTermRetentionPolicies.json
      - preview/2025-02-01-preview/blobAuditing.json
      - preview/2025-02-01-preview/databaseAdvancedThreatProtectionSettings.json
      - preview/2025-02-01-preview/databaseAdvisors.json
      - preview/2025-02-01-preview/databaseAutomaticTuning.json
      - preview/2025-02-01-preview/databaseColumns.json
      - preview/2025-02-01-preview/databaseEncryptionProtectorRevalidate.json
      - preview/2025-02-01-preview/databaseEncryptionProtectorRevert.json
      - preview/2025-02-01-preview/databaseExtensions.json
      - preview/2025-02-01-preview/databaseOperations.json
      - preview/2025-02-01-preview/databaseRecommendedActions.json
      - preview/2025-02-01-preview/databases.json
      - preview/2025-02-01-preview/databaseSchemas.json
      - preview/2025-02-01-preview/databaseSecurityAlertPolicies.json
      - preview/2025-02-01-preview/databaseSqlVulnerabilityAssessmentBaselines.json
      - preview/2025-02-01-preview/databaseSqlVulnerabilityAssessmentExecuteScan.json
      - preview/2025-02-01-preview/databaseSqlVulnerabilityAssessmentRuleBaselines.json
      - preview/2025-02-01-preview/databaseSqlVulnerabilityAssessmentScanResult.json
      - preview/2025-02-01-preview/databaseSqlVulnerabilityAssessmentScans.json
      - preview/2025-02-01-preview/databaseSqlVulnerabilityAssessmentsSettings.json
      - preview/2025-02-01-preview/databaseTables.json
      - preview/2025-02-01-preview/databaseUsages.json
      - preview/2025-02-01-preview/databaseVulnerabilityAssessmentRuleBaselines.json
      - preview/2025-02-01-preview/databaseVulnerabilityAssessments.json
      - preview/2025-02-01-preview/databaseVulnerabilityAssessmentScans.json
      - preview/2025-02-01-preview/dataMaskingPolicies.json
      - preview/2025-02-01-preview/dataMaskingRules.json
      - preview/2025-02-01-preview/dataWarehouseUserActivities.json
      - preview/2025-02-01-preview/deletedServers.json
      - preview/2025-02-01-preview/distributedAvailabilityGroups.json
      - preview/2025-02-01-preview/elasticPoolOperations.json
      - preview/2025-02-01-preview/elasticPools.json
      - preview/2025-02-01-preview/encryptionProtectors.json
      - preview/2025-02-01-preview/endpointCertificates.json
      - preview/2025-02-01-preview/failoverGroups.json
      - preview/2025-02-01-preview/firewallRules.json
      - preview/2025-02-01-preview/geoBackupPolicies.json
      - preview/2025-02-01-preview/instanceFailoverGroups.json
      - preview/2025-02-01-preview/instancePoolOperations.json
      - preview/2025-02-01-preview/instancePools.json
      - preview/2025-02-01-preview/iPv6FirewallRules.json
      - preview/2025-02-01-preview/jobAgents.json
      - preview/2025-02-01-preview/jobCredentials.json
      - preview/2025-02-01-preview/jobExecutions.json
      - preview/2025-02-01-preview/jobPrivateEndpoints.json
      - preview/2025-02-01-preview/jobs.json
      - preview/2025-02-01-preview/jobStepExecutions.json
      - preview/2025-02-01-preview/jobSteps.json
      - preview/2025-02-01-preview/jobTargetExecutions.json
      - preview/2025-02-01-preview/jobTargetGroups.json
      - preview/2025-02-01-preview/jobVersions.json
      - preview/2025-02-01-preview/ledgerDigestUploads.json
      - preview/2025-02-01-preview/locationCapabilities.json
      - preview/2025-02-01-preview/longTermRetentionBackups.json
      - preview/2025-02-01-preview/longTermRetentionManagedInstanceBackups.json
      - preview/2025-02-01-preview/longTermRetentionPolicies.json
      - preview/2025-02-01-preview/maintenanceWindowOptions.json
      - preview/2025-02-01-preview/maintenanceWindows.json
      - preview/2025-02-01-preview/managedBackupShortTermRetentionPolicies.json
      - preview/2025-02-01-preview/managedDatabaseAdvancedThreatProtectionSettings.json
      - preview/2025-02-01-preview/managedDatabaseColumns.json
      - preview/2025-02-01-preview/managedDatabaseMoveOperations.json
      - preview/2025-02-01-preview/managedDatabaseQueries.json
      - preview/2025-02-01-preview/managedDatabaseRestoreDetails.json
      - preview/2025-02-01-preview/managedDatabases.json
      - preview/2025-02-01-preview/managedDatabaseSchemas.json
      - preview/2025-02-01-preview/managedDatabaseSecurityAlertPolicies.json
      - preview/2025-02-01-preview/managedDatabaseSecurityEvents.json
      - preview/2025-02-01-preview/managedDatabaseSensitivityLabels.json
      - preview/2025-02-01-preview/managedDatabaseTables.json
      - preview/2025-02-01-preview/managedDatabaseTransparentDataEncryption.json
      - preview/2025-02-01-preview/managedDatabaseVulnerabilityAssessmentRuleBaselines.json
      - preview/2025-02-01-preview/managedDatabaseVulnerabilityAssessments.json
      - preview/2025-02-01-preview/managedDatabaseVulnerabilityAssessmentScans.json
      - preview/2025-02-01-preview/managedInstanceAdministrators.json
      - preview/2025-02-01-preview/managedInstanceAdvancedThreatProtectionSettings.json
      - preview/2025-02-01-preview/managedInstanceAzureAdOnlyAuthentications.json
      - preview/2025-02-01-preview/managedInstanceDtcs.json
      - preview/2025-02-01-preview/managedInstanceEncryptionProtectors.json
      - preview/2025-02-01-preview/managedInstanceKeys.json
      - preview/2025-02-01-preview/managedInstanceLongTermRetentionPolicies.json
      - preview/2025-02-01-preview/managedInstanceOperations.json
      - preview/2025-02-01-preview/managedInstancePrivateEndpointConnections.json
      - preview/2025-02-01-preview/managedInstancePrivateLinkResources.json
      - preview/2025-02-01-preview/managedInstances.json
      - preview/2025-02-01-preview/managedInstanceTdeCertificates.json
      - preview/2025-02-01-preview/managedInstanceVulnerabilityAssessments.json
      - preview/2025-02-01-preview/managedLedgerDigestUploads.json
      - preview/2025-02-01-preview/managedRestorableDroppedDatabaseBackupShortTermRetentionPolicies.json
      - preview/2025-02-01-preview/managedServerDnsAliases.json
      - preview/2025-02-01-preview/managedServerSecurityAlertPolicies.json
      - preview/2025-02-01-preview/networkSecurityPerimeterConfigurations.json
      - preview/2025-02-01-preview/operations.json
      - preview/2025-02-01-preview/outboundFirewallRules.json
      - preview/2025-02-01-preview/privateEndpointConnections.json
      - preview/2025-02-01-preview/privateLinkResources.json
      - preview/2025-02-01-preview/recoverableDatabases.json
      - preview/2025-02-01-preview/recoverableManagedDatabases.json
      - preview/2025-02-01-preview/replicationLinks.json
      - preview/2025-02-01-preview/restorableDroppedDatabases.json
      - preview/2025-02-01-preview/restorableDroppedManagedDatabases.json
      - preview/2025-02-01-preview/restorePoints.json
      - preview/2025-02-01-preview/sensitivityLabels.json
      - preview/2025-02-01-preview/serverAdvancedThreatProtectionSettings.json
      - preview/2025-02-01-preview/serverAdvisors.json
      - preview/2025-02-01-preview/serverAutomaticTuning.json
      - preview/2025-02-01-preview/serverAzureAdAdministrators.json
      - preview/2025-02-01-preview/serverAzureAdOnlyAuthentications.json
      - preview/2025-02-01-preview/serverConfigurationOptions.json
      - preview/2025-02-01-preview/serverConnectionPolicies.json
      - preview/2025-02-01-preview/serverDevOpsAudit.json
      - preview/2025-02-01-preview/serverDnsAliases.json
      - preview/2025-02-01-preview/serverKeys.json
      - preview/2025-02-01-preview/serverOperations.json
      - preview/2025-02-01-preview/servers.json
      - preview/2025-02-01-preview/serverSecurityAlertPolicies.json
      - preview/2025-02-01-preview/serverTrustCertificates.json
      - preview/2025-02-01-preview/serverTrustGroups.json
      - preview/2025-02-01-preview/serverUsages.json
      - preview/2025-02-01-preview/serverVulnerabilityAssessments.json
      - preview/2025-02-01-preview/sqlAgent.json
      - preview/2025-02-01-preview/sqlVulnerabilityAssessmentBaseline.json
      - preview/2025-02-01-preview/sqlVulnerabilityAssessmentExecuteScan.json
      - preview/2025-02-01-preview/sqlVulnerabilityAssessmentRuleBaseline.json
      - preview/2025-02-01-preview/sqlVulnerabilityAssessmentScanResult.json
      - preview/2025-02-01-preview/sqlVulnerabilityAssessmentScans.json
      - preview/2025-02-01-preview/sqlVulnerabilityAssessmentsSettings.json
      - preview/2025-02-01-preview/startStopManagedInstanceSchedules.json
      - preview/2025-02-01-preview/subscriptionUsages.json
      - preview/2025-02-01-preview/synapseLinkWorkspaces.json
      - preview/2025-02-01-preview/syncAgents.json
      - preview/2025-02-01-preview/syncGroups.json
      - preview/2025-02-01-preview/syncMembers.json
      - preview/2025-02-01-preview/tdeCertificates.json
      - preview/2025-02-01-preview/timeZones.json
      - preview/2025-02-01-preview/transparentDataEncryptions.json
      - preview/2025-02-01-preview/usages.json
      - preview/2025-02-01-preview/virtualClusters.json
      - preview/2025-02-01-preview/virtualNetworkRules.json
      - preview/2025-02-01-preview/workloadClassifiers.json
      - preview/2025-02-01-preview/workloadGroups.json
      - preview/2025-02-01-preview/common.json
