versions:
  - version: 2025-04-11-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AzureDataTransfer/preview/2025-04-11-preview/azuredatatransfer.json
  - version: 2025-05-21
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AzureDataTransfer/stable/2025-05-21/azuredatatransfer.json
  - version: 2025-05-30-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AzureDataTransfer/preview/2025-05-30-preview/azuredatatransfer.json
  - version: 2025-10-10-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AzureDataTransfer/preview/2025-10-10-preview/azuredatatransfer.json
