versions:
  - version: 2023-10-11-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.AzureDataTransfer/preview/2023-10-11-preview/azuredatatransfer.json
  - version: 2024-01-25
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.AzureDataTransfer/stable/2024-01-25/azuredatatransfer.json
  - version: 2024-05-07
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.AzureDataTransfer/stable/2024-05-07/azuredatatransfer.json
  - version: 2024-09-11
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.AzureDataTransfer/stable/2024-09-11/azuredatatransfer.json
  - version: 2024-09-27
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.AzureDataTransfer/stable/2024-09-27/azuredatatransfer.json
  - version: 2025-03-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.AzureDataTransfer/preview/2025-03-01-preview/azuredatatransfer.json
  - version: 2025-04-11-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AzureDataTransfer/preview/2025-04-11-preview/azuredatatransfer.json
  - version: 2025-05-21
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AzureDataTransfer/stable/2025-05-21/azuredatatransfer.json
  - version: 2025-05-30-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AzureDataTransfer/preview/2025-05-30-preview/azuredatatransfer.json
  - version: 2025-10-10-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AzureDataTransfer/preview/2025-10-10-preview/azuredatatransfer.json
