versions:
  - version: 2025-08-15
    source: typespec
    swagger-files:
      - stable/2025-08-15/ComputeLimit.json
  - version: 2026-03-20
    source: typespec
    swagger-files:
      - stable/2026-03-20/ComputeLimit.json
  - version: 2026-04-30
    source: typespec
    swagger-files:
      - stable/2026-04-30/ComputeLimit.json
  - version: 2026-06-01
    source: typespec
    swagger-files:
      - stable/2026-06-01/ComputeLimit.json
  - version: 2026-07-01
    source: typespec
    swagger-files:
      - stable/2026-07-01/ComputeLimit.json
  - version: 2026-07-31
    source: typespec
    swagger-files:
      - stable/2026-07-31/ComputeLimit.json
