versions:
  - version: 2023-02-01-preview
    source: swagger
    swagger-files:
      - preview/2023-02-01-preview/AccessControlLists.json
      - preview/2023-02-01-preview/IpCommunities.json
      - preview/2023-02-01-preview/IpExtendedCommunities.json
      - preview/2023-02-01-preview/IpPrefixes.json
      - preview/2023-02-01-preview/L2IsolationDomains.json
      - preview/2023-02-01-preview/L3IsolationDomains.json
      - preview/2023-02-01-preview/NetworkDeviceSkus.json
      - preview/2023-02-01-preview/NetworkDevices.json
      - preview/2023-02-01-preview/NetworkFabricControllers.json
      - preview/2023-02-01-preview/NetworkFabricSkus.json
      - preview/2023-02-01-preview/NetworkFabrics.json
      - preview/2023-02-01-preview/NetworkRackSkus.json
      - preview/2023-02-01-preview/NetworkRacks.json
      - preview/2023-02-01-preview/Operations.json
      - preview/2023-02-01-preview/RoutePolicies.json
      - preview/2023-02-01-preview/common.json
  - version: 2023-06-15
    source: swagger
    swagger-files:
      - stable/2023-06-15/AccessControlLists.json
      - stable/2023-06-15/InternetGatewayRules.json
      - stable/2023-06-15/InternetGateways.json
      - stable/2023-06-15/IpCommunities.json
      - stable/2023-06-15/IpExtendedCommunities.json
      - stable/2023-06-15/IpPrefixes.json
      - stable/2023-06-15/L2IsolationDomains.json
      - stable/2023-06-15/L3IsolationDomains.json
      - stable/2023-06-15/NeighborGroups.json
      - stable/2023-06-15/NetworkDeviceSkus.json
      - stable/2023-06-15/NetworkDevices.json
      - stable/2023-06-15/NetworkFabricControllers.json
      - stable/2023-06-15/NetworkFabricSkus.json
      - stable/2023-06-15/NetworkFabrics.json
      - stable/2023-06-15/NetworkPacketBrokers.json
      - stable/2023-06-15/NetworkRacks.json
      - stable/2023-06-15/NetworkTapRules.json
      - stable/2023-06-15/NetworkTaps.json
      - stable/2023-06-15/Operations.json
      - stable/2023-06-15/RoutePolicies.json
      - stable/2023-06-15/common.json
  - version: 2024-02-15-preview
    source: typespec
    swagger-files:
      - preview/2024-02-15-preview/managednetworkfabric.json
  - version: 2024-06-15-preview
    source: typespec
    swagger-files:
      - preview/2024-06-15-preview/managednetworkfabric.json
  - version: 2025-07-15
    source: typespec
    swagger-files:
      - stable/2025-07-15/managednetworkfabric.json
