versions:
  - version: 2023-03-01-preview
    source: swagger
    swagger-files:
      - preview/2023-03-01-preview/metricBatch.json
  - version: 2023-05-01-preview
    source: swagger
    swagger-files:
      - preview/2023-05-01-preview/metricBatch.json
  - version: 2023-10-01
    source: swagger
    swagger-files:
      - stable/2023-10-01/metricBatch.json
  - version: 2024-02-01
    source: typespec
    swagger-files:
      - stable/2024-02-01/metricBatch.json
