// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package typespec-go

import "github.com/Azure/azure-sdk-for-go/sdk/azcore"

// SystemEventsClient - Azure Messaging EventGrid SystemEvents
// Don't use this type directly, use a constructor function instead.
type SystemEventsClient struct {
	internal *azcore.Client
	endpoint string
}

