versions:
  - version: 2018-05-05
    source: swagger
    swagger-files:
      - stable/2018-05-05/AlertsManagement.json
  - version: 2018-05-05-preview
    source: swagger
    swagger-files:
      - preview/2018-05-05-preview/AlertsManagement.json
  - version: 2019-03-01
    source: swagger
    swagger-files:
      - stable/2019-03-01/AlertsManagement.json
  - version: 2019-05-05-preview
    source: swagger
    swagger-files:
      - preview/2019-05-05-preview/AlertsManagement.json
  - version: 2021-01-01-preview
    source: swagger
    swagger-files:
      - preview/2021-01-01-preview/AlertsManagement.json
  - version: 2025-05-25-preview
    source: typespec
    swagger-files:
      - preview/2025-05-25-preview/AlertsManagement.json
