// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armservicenetworking

// AssociationsInterfaceClientCreateOrUpdateOptions contains the optional parameters for the AssociationsInterfaceClient.CreateOrUpdate
// method.
type AssociationsInterfaceClientCreateOrUpdateOptions struct {
	ResumeToken string
}

// AssociationsInterfaceClientDeleteOptions contains the optional parameters for the AssociationsInterfaceClient.Delete method.
type AssociationsInterfaceClientDeleteOptions struct {
	ResumeToken string
}

// AssociationsInterfaceClientGetOptions contains the optional parameters for the AssociationsInterfaceClient.Get method.
type AssociationsInterfaceClientGetOptions struct {
	// placeholder for future optional parameters
}

// AssociationsInterfaceClientListByTrafficControllerOptions contains the optional parameters for the AssociationsInterfaceClient.NewListByTrafficControllerPager
// method.
type AssociationsInterfaceClientListByTrafficControllerOptions struct {
	// placeholder for future optional parameters
}

// AssociationsInterfaceClientUpdateOptions contains the optional parameters for the AssociationsInterfaceClient.Update method.
type AssociationsInterfaceClientUpdateOptions struct {
	// placeholder for future optional parameters
}

// FrontendsInterfaceClientCreateOrUpdateOptions contains the optional parameters for the FrontendsInterfaceClient.CreateOrUpdate
// method.
type FrontendsInterfaceClientCreateOrUpdateOptions struct {
	ResumeToken string
}

// FrontendsInterfaceClientDeleteOptions contains the optional parameters for the FrontendsInterfaceClient.Delete method.
type FrontendsInterfaceClientDeleteOptions struct {
	ResumeToken string
}

// FrontendsInterfaceClientGetOptions contains the optional parameters for the FrontendsInterfaceClient.Get method.
type FrontendsInterfaceClientGetOptions struct {
	// placeholder for future optional parameters
}

// FrontendsInterfaceClientListByTrafficControllerOptions contains the optional parameters for the FrontendsInterfaceClient.NewListByTrafficControllerPager
// method.
type FrontendsInterfaceClientListByTrafficControllerOptions struct {
	// placeholder for future optional parameters
}

// FrontendsInterfaceClientUpdateOptions contains the optional parameters for the FrontendsInterfaceClient.Update method.
type FrontendsInterfaceClientUpdateOptions struct {
	// placeholder for future optional parameters
}

// OperationsClientListOptions contains the optional parameters for the OperationsClient.NewListPager method.
type OperationsClientListOptions struct {
	// placeholder for future optional parameters
}

// TrafficControllerInterfaceClientCreateOrUpdateOptions contains the optional parameters for the TrafficControllerInterfaceClient.CreateOrUpdate
// method.
type TrafficControllerInterfaceClientCreateOrUpdateOptions struct {
	ResumeToken string
}

// TrafficControllerInterfaceClientDeleteOptions contains the optional parameters for the TrafficControllerInterfaceClient.Delete
// method.
type TrafficControllerInterfaceClientDeleteOptions struct {
	ResumeToken string
}

// TrafficControllerInterfaceClientGetOptions contains the optional parameters for the TrafficControllerInterfaceClient.Get
// method.
type TrafficControllerInterfaceClientGetOptions struct {
	// placeholder for future optional parameters
}

// TrafficControllerInterfaceClientListByResourceGroupOptions contains the optional parameters for the TrafficControllerInterfaceClient.NewListByResourceGroupPager
// method.
type TrafficControllerInterfaceClientListByResourceGroupOptions struct {
	// placeholder for future optional parameters
}

// TrafficControllerInterfaceClientListBySubscriptionOptions contains the optional parameters for the TrafficControllerInterfaceClient.NewListBySubscriptionPager
// method.
type TrafficControllerInterfaceClientListBySubscriptionOptions struct {
	// placeholder for future optional parameters
}

// TrafficControllerInterfaceClientUpdateOptions contains the optional parameters for the TrafficControllerInterfaceClient.Update
// method.
type TrafficControllerInterfaceClientUpdateOptions struct {
	// placeholder for future optional parameters
}
