versions:
  - version: 2020-08-20
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/stable/2020-08-20/CommunicationService.json
  - version: 2020-08-20-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2020-08-20-preview/CommunicationService.json
  - version: 2021-10-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2021-10-01-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2021-10-01-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2021-10-01-preview/EmailServices.json
  - version: 2022-07-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2022-07-01-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2022-07-01-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2022-07-01-preview/EmailServices.json
  - version: 2023-03-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2023-03-01-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-03-01-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2023-03-01-preview/EmailServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-03-01-preview/SenderUsernames.json
  - version: 2023-03-31
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/stable/2023-03-31/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/stable/2023-03-31/Domains.json
      - ../resource-manager/Microsoft.Communication/stable/2023-03-31/EmailServices.json
      - ../resource-manager/Microsoft.Communication/stable/2023-03-31/SenderUsernames.json
  - version: 2023-04-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/stable/2023-04-01/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/stable/2023-04-01/Domains.json
      - ../resource-manager/Microsoft.Communication/stable/2023-04-01/EmailServices.json
      - ../resource-manager/Microsoft.Communication/stable/2023-04-01/SenderUsernames.json
  - version: 2023-04-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2023-04-01-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-04-01-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2023-04-01-preview/EmailServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-04-01-preview/SenderUsernames.json
  - version: 2023-06-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2023-06-01-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-06-01-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2023-06-01-preview/EmailServices.json
      - ../resource-manager/Microsoft.Communication/preview/2023-06-01-preview/SenderUsernames.json
      - ../resource-manager/Microsoft.Communication/preview/2023-06-01-preview/SuppressionLists.json
  - version: 2024-09-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2024-09-01-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2024-09-01-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2024-09-01-preview/EmailServices.json
      - ../resource-manager/Microsoft.Communication/preview/2024-09-01-preview/SenderUsernames.json
      - ../resource-manager/Microsoft.Communication/preview/2024-09-01-preview/SmtpUsernames.json
      - ../resource-manager/Microsoft.Communication/preview/2024-09-01-preview/SuppressionLists.json
  - version: 2025-05-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/stable/2025-05-01/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/stable/2025-05-01/Domains.json
      - ../resource-manager/Microsoft.Communication/stable/2025-05-01/EmailServices.json
      - ../resource-manager/Microsoft.Communication/stable/2025-05-01/SenderUsernames.json
  - version: 2025-05-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Communication/preview/2025-05-01-preview/CommunicationServices.json
      - ../resource-manager/Microsoft.Communication/preview/2025-05-01-preview/Domains.json
      - ../resource-manager/Microsoft.Communication/preview/2025-05-01-preview/EmailServices.json
      - ../resource-manager/Microsoft.Communication/preview/2025-05-01-preview/SenderUsernames.json
      - ../resource-manager/Microsoft.Communication/preview/2025-05-01-preview/SmtpUsernames.json
      - ../resource-manager/Microsoft.Communication/preview/2025-05-01-preview/SuppressionLists.json
  - version: 2025-09-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Communication/stable/2025-09-01/openapi.json
  - version: 2026-03-18
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Communication/stable/2026-03-18/openapi.json
