versions:
  - version: 2023-01-01-preview
    source: swagger
    swagger-files:
      - preview/2023-01-01-preview/help.json
  - version: 2023-06-01
    source: swagger
    swagger-files:
      - stable/2023-06-01/help.json
  - version: 2023-09-01-preview
    source: swagger
    swagger-files:
      - preview/2023-09-01-preview/help.json
  - version: 2024-03-01-preview
    source: typespec
    swagger-files:
      - preview/2024-03-01-preview/help.json
