versions:
  - version: 2025-09-01-preview
    source: typespec
    swagger-files:
      - ../data-plane/Azure.Analaytics.Purview.DataQuality/preview/2025-09-01-preview/purviewDataQuality.json
  - version: 2026-01-12-preview
    source: typespec
    swagger-files:
      - ../data-plane/Azure.Analaytics.Purview.DataQuality/preview/2026-01-12-preview/purviewDataQuality.json
