versions:
  - version: 2025-01-31-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.DependencyMap/preview/2025-01-31-preview/dependencyMap.json
  - version: 2025-05-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.DependencyMap/preview/2025-05-01-preview/dependencyMap.json
  - version: 2025-07-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.DependencyMap/preview/2025-07-01-preview/dependencyMap.json
