// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package typespec-go

// OperationsClientListResponse contains the response from method OperationsClient.NewListPager.
type OperationsClientListResponse struct {
	// A list of REST API operations supported by an Azure Resource Provider. It contains an URL link to get the next set of results.
	PagedOperation
}

// SharedPrivateLinkResourcesClientCreateResponse contains the response from method SharedPrivateLinkResourcesClient.Create.
type SharedPrivateLinkResourcesClientCreateResponse struct {
	// Concrete proxy resource types can be created by aliasing this type using a specific property type.
	SharedPrivateLinkResource

	// The Retry-After header can indicate how long the client should wait before polling the operation status.
	RetryAfter *int32
}

// SharedPrivateLinkResourcesClientDeleteResponse contains the response from method SharedPrivateLinkResourcesClient.Delete.
type SharedPrivateLinkResourcesClientDeleteResponse struct {
	// Standard Azure Resource Manager operation status response
	ArmOperationStatus

	// The Retry-After header can indicate how long the client should wait before polling the operation status.
	RetryAfter *int32
}

// SharedPrivateLinkResourcesClientGetResponse contains the response from method SharedPrivateLinkResourcesClient.Get.
type SharedPrivateLinkResourcesClientGetResponse struct {
	// Concrete proxy resource types can be created by aliasing this type using a specific property type.
	SharedPrivateLinkResource
}

// SharedPrivateLinkResourcesClientListByWatcherResponse contains the response from method SharedPrivateLinkResourcesClient.NewListByWatcherPager.
type SharedPrivateLinkResourcesClientListByWatcherResponse struct {
	// The response of a SharedPrivateLinkResource list operation.
	SharedPrivateLinkResourceListResult
}

// TargetsClientCreateOrUpdateResponse contains the response from method TargetsClient.CreateOrUpdate.
type TargetsClientCreateOrUpdateResponse struct {
	// Concrete proxy resource types can be created by aliasing this type using a specific property type.
	Target
}

// TargetsClientDeleteResponse contains the response from method TargetsClient.Delete.
type TargetsClientDeleteResponse struct {
	// placeholder for future response values
}

// TargetsClientGetResponse contains the response from method TargetsClient.Get.
type TargetsClientGetResponse struct {
	// Concrete proxy resource types can be created by aliasing this type using a specific property type.
	Target
}

// TargetsClientListByWatcherResponse contains the response from method TargetsClient.NewListByWatcherPager.
type TargetsClientListByWatcherResponse struct {
	// The response of a Target list operation.
	TargetListResult
}

// WatchersClientCreateOrUpdateResponse contains the response from method WatchersClient.CreateOrUpdate.
type WatchersClientCreateOrUpdateResponse struct {
	// The DatabaseWatcherProviderHub resource.
	Watcher

	// The Retry-After header can indicate how long the client should wait before polling the operation status.
	RetryAfter *int32
}

// WatchersClientDeleteResponse contains the response from method WatchersClient.Delete.
type WatchersClientDeleteResponse struct {
	// Standard Azure Resource Manager operation status response
	ArmOperationStatus

	// The Retry-After header can indicate how long the client should wait before polling the operation status.
	RetryAfter *int32
}

// WatchersClientGetResponse contains the response from method WatchersClient.Get.
type WatchersClientGetResponse struct {
	// The DatabaseWatcherProviderHub resource.
	Watcher
}

// WatchersClientListByResourceGroupResponse contains the response from method WatchersClient.NewListByResourceGroupPager.
type WatchersClientListByResourceGroupResponse struct {
	// The response of a Watcher list operation.
	WatcherListResult
}

// WatchersClientListBySubscriptionResponse contains the response from method WatchersClient.NewListBySubscriptionPager.
type WatchersClientListBySubscriptionResponse struct {
	// The response of a Watcher list operation.
	WatcherListResult
}

// WatchersClientStartResponse contains the response from method WatchersClient.Start.
type WatchersClientStartResponse struct {
	// Standard Azure Resource Manager operation status response
	ArmOperationStatus

	// The Retry-After header can indicate how long the client should wait before polling the operation status.
	RetryAfter *int32
}

// WatchersClientStopResponse contains the response from method WatchersClient.Stop.
type WatchersClientStopResponse struct {
	// Standard Azure Resource Manager operation status response
	ArmOperationStatus

	// The Retry-After header can indicate how long the client should wait before polling the operation status.
	RetryAfter *int32
}

// WatchersClientUpdateResponse contains the response from method WatchersClient.Update.
type WatchersClientUpdateResponse struct {
	// The DatabaseWatcherProviderHub resource.
	Watcher

	// The Retry-After header can indicate how long the client should wait before polling the operation status.
	RetryAfter *int32
}

