versions:
  - version: 2023-11-01
    source: typespec
    swagger-files:
      - stable/2023-11-01/fabric.json
  - version: 2025-01-15-preview
    source: typespec
    swagger-files:
      - preview/2025-01-15-preview/fabric.json
