versions:
  - version: 2015-08-31-preview
    source: swagger
    swagger-files:
      - preview/2015-08-31-preview/ManagedIdentity.json
  - version: 2018-11-30
    source: swagger
    swagger-files:
      - stable/2018-11-30/ManagedIdentity.json
  - version: 2021-09-30-preview
    source: swagger
    swagger-files:
      - preview/2021-09-30-preview/ManagedIdentity.json
  - version: 2022-01-31-preview
    source: swagger
    swagger-files:
      - preview/2022-01-31-preview/ManagedIdentity.json
  - version: 2023-01-31
    source: swagger
    swagger-files:
      - stable/2023-01-31/ManagedIdentity.json
  - version: 2023-07-31-preview
    source: swagger
    swagger-files:
      - preview/2023-07-31-preview/ManagedIdentity.json
  - version: 2024-11-30
    source: typespec
    swagger-files:
      - stable/2024-11-30/ManagedIdentity.json
  - version: 2025-01-31-preview
    source: swagger
    swagger-files:
      - preview/2025-01-31-preview/ManagedIdentity.json
  - version: 2025-05-31-preview
    source: typespec
    swagger-files:
      - preview/2025-05-31-preview/ManagedIdentity.json
