versions:
  - version: 2021-11-01
    source: typespec
    swagger-files:
      - stable/2021-11-01/widget.json
  - version: 2024-10-01-preview
    source: typespec
    swagger-files:
      - preview/2024-10-01-preview/widget.json
