versions:
  - version: 2021-10-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Contoso/preview/2021-10-01-preview/contoso.json
  - version: 2021-11-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Contoso/stable/2021-11-01/contoso.json
