versions:
  - version: 2022-08-01-preview
    source: typespec
    swagger-files:
      - preview/2022-08-01-preview/deploymentStacks.json
  - version: 2024-03-01
    source: typespec
    swagger-files:
      - stable/2024-03-01/deploymentStacks.json
  - version: 2025-07-01
    source: typespec
    swagger-files:
      - stable/2025-07-01/deploymentStacks.json
