versions:
  - version: 2021-03-15-preview
    source: swagger
    swagger-files:
      - preview/2021-03-15-preview/customlocations.json
  - version: 2021-08-15
    source: swagger
    swagger-files:
      - stable/2021-08-15/customlocations.json
  - version: 2021-08-31-preview
    source: typespec
    swagger-files:
      - preview/2021-08-31-preview/customlocations.json
  - version: 2024-09-15-preview
    source: swagger
    swagger-files:
      - preview/2024-09-15-preview/customlocations.json
