emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}"
    output-file: "{project-root}/{version-status}/{version}/hci.json"
    arm-types-dir: "{project-root}/../../../../common-types/resource-management"
  "@azure-tools/typespec-go":
    service-dir: sdk/resourcemanager/azurestackhci
    module: github.com/Azure/azure-sdk-for-go/{service-dir}/armazurestackhci/v3
    fix-const-stuttering: true
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
    flavor: "azure"
    emitter-output-dir: "{output-dir}/{service-dir}/armazurestackhci"
  "@azure-tools/typespec-python":
    service-dir: "sdk/azurestackhci"
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-azurestackhci"
    namespace: azure.mgmt.azurestackhci
    generate-test: true
    generate-sample: true
    flavor: azure
  "@azure-tools/typespec-java":
    flavor: azure
    namespace: com.azure.resourcemanager.azurestackhci
    service-dir: "sdk/azurestackhci"
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-azurestackhci"
    service-name: "Azure Stack Hci"
    use-object-for-unknown: true
  "@azure-typespec/http-client-csharp-mgmt":
    namespace: "Azure.ResourceManager.Hci"
    emitter-output-dir: "{output-dir}/sdk/azurestackhci/{namespace}"
    enable-wire-path-attribute: true
  "@azure-tools/typespec-ts":
    service-dir: "sdk/azurestackhci"
    package-dir: "arm-azurestackhci"
    emitter-output-dir: "{output-dir}/{service-dir}/{package-dir}"
    flavor: azure
    compatibility-lro: true
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-azurestackhci"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
    - "@azure-tools/typespec-azure-rulesets/client-sdk"
parameters:
  service-dir:
    default: sdk/azurestackhci
