versions:
  - version: 2024-06-19
    source: typespec
    swagger-files:
      - ../resource-manager/Qumulo.Storage/stable/2024-06-19/Qumulo.Storage.json
  - version: 2025-10-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Qumulo.Storage/preview/2025-10-01-preview/Qumulo.Storage.json
  - version: 2026-02-17-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Qumulo.Storage/preview/2026-02-17-preview/Qumulo.Storage.json
  - version: 2026-04-16
    source: typespec
    swagger-files:
      - ../resource-manager/Qumulo.Storage/stable/2026-04-16/Qumulo.Storage.json
