versions:
  - version: 2025-05-01
    source: typespec
    swagger-files:
      - ../data-plane/Azure.AI.Agents/stable/2025-05-01/azure-ai-agents.json
  - version: 2025-05-15-preview
    source: typespec
    swagger-files:
      - ../data-plane/Azure.AI.Agents/preview/2025-05-15-preview/azure-ai-agents.json
  - version: v1
    source: typespec
    swagger-files:
      - ../data-plane/Azure.AI.Agents/stable/v1/azure-ai-agents.json
