versions:
  - version: 2022-11-01
    source: typespec
    swagger-files:
      - stable/2022-11-01/loadtestservice.json
  - version: 2023-04-01-preview
    source: typespec
    swagger-files:
      - preview/2023-04-01-preview/loadtestservice.json
  - version: 2024-03-01-preview
    source: typespec
    swagger-files:
      - preview/2024-03-01-preview/loadtestservice.json
  - version: 2024-05-01-preview
    source: typespec
    swagger-files:
      - preview/2024-05-01-preview/loadtestservice.json
  - version: 2024-07-01-preview
    source: typespec
    swagger-files:
      - preview/2024-07-01-preview/loadtestservice.json
  - version: 2024-12-01-preview
    source: typespec
    swagger-files:
      - preview/2024-12-01-preview/loadtestservice.json
  - version: 2025-03-01-preview
    source: typespec
    swagger-files:
      - preview/2025-03-01-preview/loadtestservice.json
  - version: 2025-11-01-preview
    source: typespec
    swagger-files:
      - preview/2025-11-01-preview/loadtestservice.json
  - version: 2026-04-01
    source: typespec
    swagger-files:
      - stable/2026-04-01/loadtestservice.json
