parameters:
  "service-dir":
    default: "sdk/maps"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}"
    examples-dir: "{project-root}/examples"
    output-file: "{version-status}/{version}/timezone.json"
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-maps-timezone"
    namespace: "azure.maps.timezone"
    generate-test: false
    generate-sample: false
    flavor: azure
  "@azure-typespec/http-client-csharp":
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
    namespace: Azure.Maps.Timezone
    model-namespace: false
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-maps-timezone"
    is-modular-library: true
    package-details:
      name: "@azure/azure-maps-timezone"
    flavor: azure
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-maps-timezone"
    namespace: com.azure.maps.timezone
    flavor: azure
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
