versions:
  - version: 2020-04-30
    source: swagger
    swagger-files:
      - stable/2020-04-30/redhatopenshift.json
  - version: 2021-09-01-preview
    source: swagger
    swagger-files:
      - preview/2021-09-01-preview/redhatopenshift.json
  - version: 2022-04-01
    source: swagger
    swagger-files:
      - stable/2022-04-01/redhatopenshift.json
  - version: 2022-09-04
    source: swagger
    swagger-files:
      - stable/2022-09-04/redhatopenshift.json
  - version: 2023-04-01
    source: swagger
    swagger-files:
      - stable/2023-04-01/redhatopenshift.json
  - version: 2023-07-01-preview
    source: swagger
    swagger-files:
      - preview/2023-07-01-preview/redhatopenshift.json
  - version: 2023-09-04
    source: swagger
    swagger-files:
      - stable/2023-09-04/redhatopenshift.json
  - version: 2023-11-22
    source: swagger
    swagger-files:
      - stable/2023-11-22/redhatopenshift.json
  - version: 2024-08-12-preview
    source: swagger
    swagger-files:
      - preview/2024-08-12-preview/redhatopenshift.json
  - version: 2025-07-25
    source: typespec
    swagger-files:
      - stable/2025-07-25/redhatopenshift.json
