versions:
  - version: 2019-10-01-preview
    source: typespec
    swagger-files:
      - preview/2019-10-01-preview/deploymentScripts.json
  - version: 2020-10-01
    source: typespec
    swagger-files:
      - stable/2020-10-01/deploymentScripts.json
  - version: 2023-08-01
    source: typespec
    swagger-files:
      - stable/2023-08-01/deploymentScripts.json
