versions:
  - version: 2025-05-01
    source: typespec
    swagger-files:
      - stable/2025-05-01/azure-ai-agents.json
  - version: 2025-05-15-preview
    source: typespec
    swagger-files:
      - preview/2025-05-15-preview/azure-ai-agents.json
  - version: v1
    source: typespec
    swagger-files:
      - stable/v1/azure-ai-agents.json
