versions:
  - version: 2018-08-20-preview
    source: swagger
    swagger-files:
      - preview/2018-08-20-preview/healthcare-apis.json
  - version: 2019-09-16
    source: swagger
    swagger-files:
      - stable/2019-09-16/healthcare-apis.json
  - version: 2020-03-15
    source: swagger
    swagger-files:
      - stable/2020-03-15/healthcare-apis.json
  - version: 2020-03-30
    source: swagger
    swagger-files:
      - stable/2020-03-30/healthcare-apis.json
  - version: 2021-01-11
    source: swagger
    swagger-files:
      - stable/2021-01-11/healthcare-apis.json
  - version: 2021-06-01-preview
    source: swagger
    swagger-files:
      - preview/2021-06-01-preview/healthcare-apis.json
  - version: 2021-11-01
    source: swagger
    swagger-files:
      - stable/2021-11-01/healthcare-apis.json
  - version: 2022-01-31-preview
    source: swagger
    swagger-files:
      - preview/2022-01-31-preview/healthcare-apis.json
  - version: 2022-05-15
    source: swagger
    swagger-files:
      - stable/2022-05-15/healthcare-apis.json
  - version: 2022-06-01
    source: swagger
    swagger-files:
      - stable/2022-06-01/healthcare-apis.json
  - version: 2022-10-01-preview
    source: swagger
    swagger-files:
      - preview/2022-10-01-preview/healthcare-apis.json
  - version: 2022-12-01
    source: swagger
    swagger-files:
      - stable/2022-12-01/healthcare-apis.json
  - version: 2023-02-28
    source: swagger
    swagger-files:
      - stable/2023-02-28/healthcare-apis.json
  - version: 2023-09-06
    source: swagger
    swagger-files:
      - stable/2023-09-06/healthcare-apis.json
  - version: 2023-11-01
    source: swagger
    swagger-files:
      - stable/2023-11-01/healthcare-apis.json
  - version: 2023-12-01
    source: swagger
    swagger-files:
      - stable/2023-12-01/healthcare-apis.json
  - version: 2024-03-01
    source: swagger
    swagger-files:
      - stable/2024-03-01/healthcare-apis.json
  - version: 2024-03-31
    source: swagger
    swagger-files:
      - stable/2024-03-31/healthcare-apis.json
  - version: 2025-03-01-preview
    source: swagger
    swagger-files:
      - preview/2025-03-01-preview/healthcare-apis.json
  - version: 2025-04-01-preview
    source: typespec
    swagger-files:
      - preview/2025-04-01-preview/healthcare-apis.json
