versions:
  - version: 2015-07-01
    source: swagger
    swagger-files:
      - ../stable/2015-07-01/authorization-RoleAssignmentsCalls.json
  - version: 2017-10-01-preview
    source: swagger
    swagger-files:
      - ../preview/2017-10-01-preview/authorization-RoleAssignmentsCalls.json
  - version: 2018-01-01-preview
    source: swagger
    swagger-files:
      - ../preview/2018-01-01-preview/authorization-RoleAssignmentsCalls.json
  - version: 2018-09-01-preview
    source: swagger
    swagger-files:
      - ../preview/2018-09-01-preview/authorization-RoleAssignmentsCalls.json
  - version: 2020-03-01-preview
    source: swagger
    swagger-files:
      - ../preview/2020-03-01-preview/authorization-RoleAssignmentsCalls.json
  - version: 2020-04-01-preview
    source: swagger
    swagger-files:
      - ../preview/2020-04-01-preview/authorization-RoleAssignmentsCalls.json
  - version: 2020-08-01-preview
    source: swagger
    swagger-files:
      - ../preview/2020-08-01-preview/authorization-RoleAssignmentsCalls.json
  - version: 2020-10-01-preview
    source: swagger
    swagger-files:
      - ../preview/2020-10-01-preview/authorization-RoleAssignmentsCalls.json
  - version: 2022-04-01
    source: typespec
    swagger-files:
      - ../stable/2022-04-01/authorization-RoleAssignmentsCalls.json
