versions:
  - version: 2025-03-30
    source: typespec
    swagger-files:
      - stable/2025-03-30/openapi.json
  - version: 2024-04-15
    source: swagger
    swagger-files:
      - stable/2024-04-15/common.json
      - stable/2024-04-15/configurationGroupSchema.json
      - stable/2024-04-15/configurationGroupValues.json
      - stable/2024-04-15/networkFunction.json
      - stable/2024-04-15/networkFunctionDefinition.json
      - stable/2024-04-15/networkServiceDesign.json
      - stable/2024-04-15/operation.json
      - stable/2024-04-15/publisher.json
      - stable/2024-04-15/pureProxyArtifact.json
      - stable/2024-04-15/site.json
      - stable/2024-04-15/siteNetworkService.json
  - version: 2023-09-01
    source: swagger
    swagger-files:
      - stable/2023-09-01/common.json
      - stable/2023-09-01/configurationGroupSchema.json
      - stable/2023-09-01/configurationGroupValues.json
      - stable/2023-09-01/networkFunction.json
      - stable/2023-09-01/networkFunctionDefinition.json
      - stable/2023-09-01/networkServiceDesign.json
      - stable/2023-09-01/operation.json
      - stable/2023-09-01/publisher.json
      - stable/2023-09-01/pureProxyArtifact.json
      - stable/2023-09-01/site.json
      - stable/2023-09-01/siteNetworkService.json
  - version: 2022-01-01-preview
    source: swagger
    swagger-files:
      - preview/2022-01-01-preview/common.json
      - preview/2022-01-01-preview/device.json
      - preview/2022-01-01-preview/networkFunction.json
      - preview/2022-01-01-preview/networkFunctionVendor.json
      - preview/2022-01-01-preview/operation.json
      - preview/2022-01-01-preview/vendor.json
      - preview/2022-01-01-preview/vendorNetworkFunction.json
  - version: 2021-05-01
    source: swagger
    swagger-files:
      - stable/2021-05-01/common.json
      - stable/2021-05-01/device.json
      - stable/2021-05-01/networkFunction.json
      - stable/2021-05-01/networkFunctionVendor.json
      - stable/2021-05-01/operation.json
      - stable/2021-05-01/vendor.json
      - stable/2021-05-01/vendorNetworkFunction.json
  - version: 2020-01-01-preview
    source: swagger
    swagger-files:
      - preview/2020-01-01-preview/common.json
      - preview/2020-01-01-preview/device.json
      - preview/2020-01-01-preview/networkFunction.json
      - preview/2020-01-01-preview/networkFunctionVendor.json
      - preview/2020-01-01-preview/operation.json
      - preview/2020-01-01-preview/vendor.json
      - preview/2020-01-01-preview/vendorNetworkFunction.json
