versions:
  - version: 2024-04-01-preview
    source: typespec
    swagger-files:
      - ../data-plane/Microsoft.MachineLearningServices/preview/2024-04-01-preview/azure-ai-assets.json
  - version: 2024-05-01-preview
    source: typespec
    swagger-files:
      - ../data-plane/Microsoft.MachineLearningServices/preview/2024-05-01-preview/azure-ai-assets.json
