versions:
  - version: 2019-03-18
    source: swagger
    swagger-files:
      - preview/2019-03-18/HybridCompute.json
  - version: 2019-08-02
    source: swagger
    swagger-files:
      - preview/2019-08-02/HybridCompute.json
  - version: 2019-12-12
    source: swagger
    swagger-files:
      - stable/2019-12-12/HybridCompute.json
  - version: 2020-07-30-preview
    source: swagger
    swagger-files:
      - preview/2020-07-30-preview/HybridCompute.json
  - version: 2020-08-02
    source: swagger
    swagger-files:
      - stable/2020-08-02/HybridCompute.json
  - version: 2020-08-15-preview
    source: swagger
    swagger-files:
      - preview/2020-08-15-preview/HybridCompute.json
      - preview/2020-08-15-preview/privateLinkScopes.json
  - version: 2021-01-28-preview
    source: swagger
    swagger-files:
      - preview/2021-01-28-preview/HybridCompute.json
      - preview/2021-01-28-preview/privateLinkScopes.json
  - version: 2021-03-25-preview
    source: swagger
    swagger-files:
      - preview/2021-03-25-preview/HybridCompute.json
      - preview/2021-03-25-preview/privateLinkScopes.json
  - version: 2021-04-22-preview
    source: swagger
    swagger-files:
      - preview/2021-04-22-preview/HybridCompute.json
      - preview/2021-04-22-preview/privateLinkScopes.json
  - version: 2021-05-17-preview
    source: swagger
    swagger-files:
      - preview/2021-05-17-preview/HybridCompute.json
      - preview/2021-05-17-preview/privateLinkScopes.json
  - version: 2021-05-20
    source: swagger
    swagger-files:
      - stable/2021-05-20/HybridCompute.json
      - stable/2021-05-20/privateLinkScopes.json
  - version: 2021-06-10-preview
    source: swagger
    swagger-files:
      - preview/2021-06-10-preview/HybridCompute.json
      - preview/2021-06-10-preview/privateLinkScopes.json
  - version: 2021-12-10-preview
    source: swagger
    swagger-files:
      - preview/2021-12-10-preview/HybridCompute.json
      - preview/2021-12-10-preview/privateLinkScopes.json
  - version: 2022-03-10
    source: swagger
    swagger-files:
      - stable/2022-03-10/HybridCompute.json
      - stable/2022-03-10/privateLinkScopes.json
  - version: 2022-05-10-preview
    source: swagger
    swagger-files:
      - preview/2022-05-10-preview/HybridCompute.json
      - preview/2022-05-10-preview/privateLinkScopes.json
  - version: 2022-08-11-preview
    source: swagger
    swagger-files:
      - preview/2022-08-11-preview/HybridCompute.json
      - preview/2022-08-11-preview/privateLinkScopes.json
  - version: 2022-11-10
    source: swagger
    swagger-files:
      - stable/2022-11-10/HybridCompute.json
      - stable/2022-11-10/privateLinkScopes.json
  - version: 2022-12-27
    source: swagger
    swagger-files:
      - stable/2022-12-27/HybridCompute.json
      - stable/2022-12-27/privateLinkScopes.json
  - version: 2022-12-27-preview
    source: swagger
    swagger-files:
      - preview/2022-12-27-preview/HybridCompute.json
      - preview/2022-12-27-preview/privateLinkScopes.json
  - version: 2023-03-15-preview
    source: swagger
    swagger-files:
      - preview/2023-03-15-preview/HybridCompute.json
      - preview/2023-03-15-preview/privateLinkScopes.json
  - version: 2023-06-20-preview
    source: swagger
    swagger-files:
      - preview/2023-06-20-preview/HybridCompute.json
      - preview/2023-06-20-preview/privateLinkScopes.json
  - version: 2023-10-03-preview
    source: swagger
    swagger-files:
      - preview/2023-10-03-preview/HybridCompute.json
      - preview/2023-10-03-preview/privateLinkScopes.json
  - version: 2024-03-31-preview
    source: swagger
    swagger-files:
      - preview/2024-03-31-preview/HybridCompute.json
      - preview/2024-03-31-preview/privateLinkScopes.json
  - version: 2024-05-20-preview
    source: swagger
    swagger-files:
      - preview/2024-05-20-preview/HybridCompute.json
      - preview/2024-05-20-preview/privateLinkScopes.json
  - version: 2024-07-10
    source: swagger
    swagger-files:
      - stable/2024-07-10/HybridCompute.json
      - stable/2024-07-10/privateLinkScopes.json
  - version: 2024-07-31-preview
    source: swagger
    swagger-files:
      - preview/2024-07-31-preview/HybridCompute.json
      - preview/2024-07-31-preview/privateLinkScopes.json
  - version: 2024-09-10-preview
    source: swagger
    swagger-files:
      - preview/2024-09-10-preview/HybridCompute.json
      - preview/2024-09-10-preview/privateLinkScopes.json
  - version: 2024-11-10-preview
    source: swagger
    swagger-files:
      - preview/2024-11-10-preview/HybridCompute.json
      - preview/2024-11-10-preview/privateLinkScopes.json
  - version: 2025-01-13
    source: swagger
    swagger-files:
      - stable/2025-01-13/HybridCompute.json
      - stable/2025-01-13/privateLinkScopes.json
  - version: 2025-02-19-preview
    source: swagger
    swagger-files:
      - preview/2025-02-19-preview/HybridCompute.json
      - preview/2025-02-19-preview/privateLinkScopes.json
  - version: 2025-06-01
    source: swagger
    swagger-files:
      - preview/2025-06-01/HybridCompute.json
      - preview/2025-06-01/privateLinkScopes.json
  - version: 2025-08-21-preview
    source: swagger
    swagger-files:
      - preview/2025-08-21-preview/HybridCompute.json
      - preview/2025-08-21-preview/privateLinkScopes.json
  - version: 2025-09-16-preview
    source: typespec
    swagger-files:
      - preview/2025-09-16-preview/openapi.json
  - version: 2026-02-12-preview
    source: typespec
    swagger-files:
      - preview/2026-02-12-preview/openapi.json
  - version: 2026-06-04-preview
    source: typespec
    swagger-files:
      - preview/2026-06-04-preview/openapi.json
  - version: 2026-06-16-preview
    source: typespec
    swagger-files:
      - preview/2026-06-16-preview/openapi.json
