versions:
  - version: 2020-09-01-preview
    source: typespec
    swagger-files:
      - ../../../../../tsp-output/@azure-tools/typespec-autorest/ResourceChanges/preview/2020-09-01-preview/openapi.json
