parameters:
  "service-dir":
    default: "sdk/compute"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    omit-unreachable-types: true
    emitter-output-dir: "{project-root}"
    output-file: "{version-status}/{version}/scheduledActions.json"
    examples-dir: "{project-root}/examples"
    arm-types-dir: "{project-root}/../../../../common-types/resource-management"
  "@azure-typespec/http-client-csharp-mgmt":
    namespace: "Azure.ResourceManager.Compute.ScheduledActions"
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
  "@azure-tools/typespec-python":
    namespace: "azure.mgmt.computescheduledactions"
    generate-test: true
    generate-sample: true
    flavor: "azure"
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-computescheduledactions"
  "@azure-tools/typespec-java":
    service-dir: "sdk/compute"
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-compute-scheduledactions"
    namespace: "com.azure.resourcemanager.compute.scheduledactions"
    service-name: "Compute ScheduledActions"
    flavor: azure
  "@azure-tools/typespec-ts":
    service-dir: "sdk/compute"
    emitter-output-dir: "{output-dir}/{service-dir}/arm-compute-scheduledactions"
    flavor: azure
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-compute-scheduledactions"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/compute"
    emitter-output-dir: "{output-dir}/{service-dir}/armscheduledactions"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armscheduledactions"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
