versions:
  - version: 2015-08-01
    source: swagger
    swagger-files:
      - stable/2015-08-01/service.json
  - version: 2015-08-01-preview
    source: swagger
    swagger-files:
      - preview/2015-08-01-preview/logicAppsManagementClient.json
  - version: 2016-03-01
    source: swagger
    swagger-files:
      - stable/2016-03-01/Certificates.json
      - stable/2016-03-01/CommonDefinitions.json
      - stable/2016-03-01/DeletedWebApps.json
      - stable/2016-03-01/Diagnostics.json
      - stable/2016-03-01/Provider.json
      - stable/2016-03-01/Recommendations.json
      - stable/2016-03-01/ResourceHealthMetadata.json
      - stable/2016-03-01/ResourceProvider.json
  - version: 2016-06-01
    source: swagger
    swagger-files:
      - stable/2016-06-01/logicAppsManagementClient.json
  - version: 2016-08-01
    source: swagger
    swagger-files:
      - stable/2016-08-01/WebApps.json
  - version: 2016-09-01
    source: swagger
    swagger-files:
      - stable/2016-09-01/AppServiceEnvironments.json
      - stable/2016-09-01/AppServicePlans.json
  - version: 2018-02-01
    source: swagger
    swagger-files:
      - stable/2018-02-01/AppServiceEnvironments.json
      - stable/2018-02-01/AppServicePlans.json
      - stable/2018-02-01/Certificates.json
      - stable/2018-02-01/CommonDefinitions.json
      - stable/2018-02-01/DeletedWebApps.json
      - stable/2018-02-01/Diagnostics.json
      - stable/2018-02-01/Provider.json
      - stable/2018-02-01/Recommendations.json
      - stable/2018-02-01/ResourceHealthMetadata.json
      - stable/2018-02-01/ResourceProvider.json
      - stable/2018-02-01/WebApps.json
  - version: 2018-11-01
    source: swagger
    swagger-files:
      - stable/2018-11-01/Certificates.json
      - stable/2018-11-01/WebApps.json
  - version: 2019-08-01
    source: swagger
    swagger-files:
      - stable/2019-08-01/AppServiceEnvironments.json
      - stable/2019-08-01/AppServicePlans.json
      - stable/2019-08-01/Certificates.json
      - stable/2019-08-01/CommonDefinitions.json
      - stable/2019-08-01/DeletedWebApps.json
      - stable/2019-08-01/Diagnostics.json
      - stable/2019-08-01/Provider.json
      - stable/2019-08-01/Recommendations.json
      - stable/2019-08-01/ResourceHealthMetadata.json
      - stable/2019-08-01/ResourceProvider.json
      - stable/2019-08-01/StaticSites.json
      - stable/2019-08-01/WebApps.json
  - version: 2020-06-01
    source: swagger
    swagger-files:
      - stable/2020-06-01/AppServiceEnvironments.json
      - stable/2020-06-01/AppServicePlans.json
      - stable/2020-06-01/Certificates.json
      - stable/2020-06-01/CommonDefinitions.json
      - stable/2020-06-01/DeletedWebApps.json
      - stable/2020-06-01/Diagnostics.json
      - stable/2020-06-01/Provider.json
      - stable/2020-06-01/Recommendations.json
      - stable/2020-06-01/ResourceHealthMetadata.json
      - stable/2020-06-01/ResourceProvider.json
      - stable/2020-06-01/StaticSites.json
      - stable/2020-06-01/WebApps.json
  - version: 2020-09-01
    source: swagger
    swagger-files:
      - stable/2020-09-01/AppServiceEnvironments.json
      - stable/2020-09-01/AppServicePlans.json
      - stable/2020-09-01/Certificates.json
      - stable/2020-09-01/CommonDefinitions.json
      - stable/2020-09-01/DeletedWebApps.json
      - stable/2020-09-01/Diagnostics.json
      - stable/2020-09-01/Provider.json
      - stable/2020-09-01/Recommendations.json
      - stable/2020-09-01/ResourceHealthMetadata.json
      - stable/2020-09-01/ResourceProvider.json
      - stable/2020-09-01/StaticSites.json
      - stable/2020-09-01/WebApps.json
  - version: 2020-10-01
    source: swagger
    swagger-files:
      - stable/2020-10-01/AppServiceEnvironments.json
      - stable/2020-10-01/AppServicePlans.json
      - stable/2020-10-01/Certificates.json
      - stable/2020-10-01/CommonDefinitions.json
      - stable/2020-10-01/DeletedWebApps.json
      - stable/2020-10-01/Diagnostics.json
      - stable/2020-10-01/Provider.json
      - stable/2020-10-01/Recommendations.json
      - stable/2020-10-01/ResourceHealthMetadata.json
      - stable/2020-10-01/ResourceProvider.json
      - stable/2020-10-01/StaticSites.json
      - stable/2020-10-01/WebApps.json
  - version: 2020-12-01
    source: swagger
    swagger-files:
      - stable/2020-12-01/AppServiceEnvironments.json
      - stable/2020-12-01/AppServicePlans.json
      - stable/2020-12-01/Certificates.json
      - stable/2020-12-01/CommonDefinitions.json
      - stable/2020-12-01/DeletedWebApps.json
      - stable/2020-12-01/Diagnostics.json
      - stable/2020-12-01/Global.json
      - stable/2020-12-01/Provider.json
      - stable/2020-12-01/Recommendations.json
      - stable/2020-12-01/ResourceHealthMetadata.json
      - stable/2020-12-01/ResourceProvider.json
      - stable/2020-12-01/StaticSites.json
      - stable/2020-12-01/WebApps.json
  - version: 2021-01-01
    source: swagger
    swagger-files:
      - stable/2021-01-01/AppServiceEnvironments.json
      - stable/2021-01-01/AppServicePlans.json
      - stable/2021-01-01/Certificates.json
      - stable/2021-01-01/CommonDefinitions.json
      - stable/2021-01-01/DeletedWebApps.json
      - stable/2021-01-01/Diagnostics.json
      - stable/2021-01-01/Global.json
      - stable/2021-01-01/KubeEnvironments.json
      - stable/2021-01-01/Provider.json
      - stable/2021-01-01/Recommendations.json
      - stable/2021-01-01/ResourceHealthMetadata.json
      - stable/2021-01-01/ResourceProvider.json
      - stable/2021-01-01/StaticSites.json
      - stable/2021-01-01/WebApps.json
  - version: 2021-01-15
    source: swagger
    swagger-files:
      - stable/2021-01-15/AppServiceEnvironments.json
      - stable/2021-01-15/AppServicePlans.json
      - stable/2021-01-15/Certificates.json
      - stable/2021-01-15/CommonDefinitions.json
      - stable/2021-01-15/DeletedWebApps.json
      - stable/2021-01-15/Diagnostics.json
      - stable/2021-01-15/Global.json
      - stable/2021-01-15/KubeEnvironments.json
      - stable/2021-01-15/Provider.json
      - stable/2021-01-15/Recommendations.json
      - stable/2021-01-15/ResourceHealthMetadata.json
      - stable/2021-01-15/ResourceProvider.json
      - stable/2021-01-15/StaticSites.json
      - stable/2021-01-15/WebApps.json
  - version: 2021-02-01
    source: swagger
    swagger-files:
      - stable/2021-02-01/AppServiceEnvironments.json
      - stable/2021-02-01/AppServicePlans.json
      - stable/2021-02-01/Certificates.json
      - stable/2021-02-01/CommonDefinitions.json
      - stable/2021-02-01/DeletedWebApps.json
      - stable/2021-02-01/Diagnostics.json
      - stable/2021-02-01/Global.json
      - stable/2021-02-01/KubeEnvironments.json
      - stable/2021-02-01/Provider.json
      - stable/2021-02-01/Recommendations.json
      - stable/2021-02-01/ResourceHealthMetadata.json
      - stable/2021-02-01/ResourceProvider.json
      - stable/2021-02-01/StaticSites.json
      - stable/2021-02-01/WebApps.json
  - version: 2021-03-01
    source: swagger
    swagger-files:
      - stable/2021-03-01/AppServiceEnvironments.json
      - stable/2021-03-01/AppServicePlans.json
      - stable/2021-03-01/Certificates.json
      - stable/2021-03-01/CommonDefinitions.json
      - stable/2021-03-01/ContainerApps.json
      - stable/2021-03-01/ContainerAppsRevisions.json
      - stable/2021-03-01/DeletedWebApps.json
      - stable/2021-03-01/Diagnostics.json
      - stable/2021-03-01/Global.json
      - stable/2021-03-01/KubeEnvironments.json
      - stable/2021-03-01/Provider.json
      - stable/2021-03-01/Recommendations.json
      - stable/2021-03-01/ResourceHealthMetadata.json
      - stable/2021-03-01/ResourceProvider.json
      - stable/2021-03-01/StaticSites.json
      - stable/2021-03-01/WebApps.json
  - version: 2022-03-01
    source: swagger
    swagger-files:
      - stable/2022-03-01/AppServiceEnvironments.json
      - stable/2022-03-01/AppServicePlans.json
      - stable/2022-03-01/Certificates.json
      - stable/2022-03-01/CommonDefinitions.json
      - stable/2022-03-01/ContainerApps.json
      - stable/2022-03-01/ContainerAppsRevisions.json
      - stable/2022-03-01/DeletedWebApps.json
      - stable/2022-03-01/Diagnostics.json
      - stable/2022-03-01/Global.json
      - stable/2022-03-01/KubeEnvironments.json
      - stable/2022-03-01/Provider.json
      - stable/2022-03-01/Recommendations.json
      - stable/2022-03-01/ResourceHealthMetadata.json
      - stable/2022-03-01/ResourceProvider.json
      - stable/2022-03-01/StaticSites.json
      - stable/2022-03-01/WebApps.json
  - version: 2022-09-01
    source: swagger
    swagger-files:
      - stable/2022-09-01/AppServiceEnvironments.json
      - stable/2022-09-01/AppServicePlans.json
      - stable/2022-09-01/Certificates.json
      - stable/2022-09-01/CommonDefinitions.json
      - stable/2022-09-01/ContainerApps.json
      - stable/2022-09-01/ContainerAppsRevisions.json
      - stable/2022-09-01/DeletedWebApps.json
      - stable/2022-09-01/Diagnostics.json
      - stable/2022-09-01/Global.json
      - stable/2022-09-01/KubeEnvironments.json
      - stable/2022-09-01/Provider.json
      - stable/2022-09-01/Recommendations.json
      - stable/2022-09-01/ResourceHealthMetadata.json
      - stable/2022-09-01/ResourceProvider.json
      - stable/2022-09-01/StaticSites.json
      - stable/2022-09-01/WebApps.json
  - version: 2023-01-01
    source: swagger
    swagger-files:
      - stable/2023-01-01/AppServiceEnvironments.json
      - stable/2023-01-01/AppServicePlans.json
      - stable/2023-01-01/Certificates.json
      - stable/2023-01-01/CommonDefinitions.json
      - stable/2023-01-01/ContainerApps.json
      - stable/2023-01-01/ContainerAppsRevisions.json
      - stable/2023-01-01/DeletedWebApps.json
      - stable/2023-01-01/Diagnostics.json
      - stable/2023-01-01/Global.json
      - stable/2023-01-01/KubeEnvironments.json
      - stable/2023-01-01/Provider.json
      - stable/2023-01-01/Recommendations.json
      - stable/2023-01-01/ResourceHealthMetadata.json
      - stable/2023-01-01/ResourceProvider.json
      - stable/2023-01-01/StaticSites.json
      - stable/2023-01-01/WebApps.json
  - version: 2023-12-01
    source: swagger
    swagger-files:
      - stable/2023-12-01/AppServiceEnvironments.json
      - stable/2023-12-01/AppServicePlans.json
      - stable/2023-12-01/Certificates.json
      - stable/2023-12-01/CommonDefinitions.json
      - stable/2023-12-01/ContainerApps.json
      - stable/2023-12-01/ContainerAppsRevisions.json
      - stable/2023-12-01/DeletedWebApps.json
      - stable/2023-12-01/Diagnostics.json
      - stable/2023-12-01/Global.json
      - stable/2023-12-01/KubeEnvironments.json
      - stable/2023-12-01/Provider.json
      - stable/2023-12-01/Recommendations.json
      - stable/2023-12-01/ResourceHealthMetadata.json
      - stable/2023-12-01/ResourceProvider.json
      - stable/2023-12-01/StaticSites.json
      - stable/2023-12-01/WebApps.json
  - version: 2024-04-01
    source: swagger
    swagger-files:
      - stable/2024-04-01/AppServiceEnvironments.json
      - stable/2024-04-01/AppServicePlans.json
      - stable/2024-04-01/Certificates.json
      - stable/2024-04-01/CommonDefinitions.json
      - stable/2024-04-01/DeletedWebApps.json
      - stable/2024-04-01/Diagnostics.json
      - stable/2024-04-01/Global.json
      - stable/2024-04-01/KubeEnvironments.json
      - stable/2024-04-01/Provider.json
      - stable/2024-04-01/Recommendations.json
      - stable/2024-04-01/ResourceHealthMetadata.json
      - stable/2024-04-01/ResourceProvider.json
      - stable/2024-04-01/StaticSites.json
      - stable/2024-04-01/WebApps.json
  - version: 2024-11-01
    source: swagger
    swagger-files:
      - stable/2024-11-01/AppServiceEnvironments.json
      - stable/2024-11-01/AppServicePlans.json
      - stable/2024-11-01/Certificates.json
      - stable/2024-11-01/CommonDefinitions.json
      - stable/2024-11-01/DeletedWebApps.json
      - stable/2024-11-01/Diagnostics.json
      - stable/2024-11-01/Global.json
      - stable/2024-11-01/KubeEnvironments.json
      - stable/2024-11-01/Provider.json
      - stable/2024-11-01/Recommendations.json
      - stable/2024-11-01/ResourceHealthMetadata.json
      - stable/2024-11-01/ResourceProvider.json
      - stable/2024-11-01/SiteCertificates.json
      - stable/2024-11-01/StaticSites.json
      - stable/2024-11-01/WebApps.json
  - version: 2025-03-01
    source: typespec
    swagger-files:
      - stable/2025-03-01/openapi.json
  - version: 2025-05-01
    source: typespec
    swagger-files:
      - stable/2025-05-01/openapi.json
  - version: 2026-03-01-preview
    source: typespec
    swagger-files:
      - preview/2026-03-01-preview/openapi.json
  - version: 2026-03-15
    source: typespec
    swagger-files:
      - stable/2026-03-15/openapi.json
  - version: 2026-07-15
    source: typespec
    swagger-files:
      - stable/2026-07-15/openapi.json
