versions:
  - version: 2018-03-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2018-03-01-preview/machineLearningServices.json
  - version: 2018-11-19
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2018-11-19/machineLearningServices.json
  - version: 2019-05-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2019-05-01/machineLearningServices.json
  - version: 2019-06-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2019-06-01/machineLearningServices.json
  - version: 2019-11-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2019-11-01/machineLearningServices.json
  - version: 2020-01-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2020-01-01/machineLearningServices.json
  - version: 2020-02-18-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2020-02-18-preview/machineLearningServices.json
  - version: 2020-03-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2020-03-01/machineLearningServices.json
  - version: 2020-04-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2020-04-01/machineLearningServices.json
  - version: 2020-04-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2020-04-01-preview/machineLearningServices.json
  - version: 2020-05-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2020-05-01-preview/machineLearningServices.json
  - version: 2020-05-15-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2020-05-15-preview/machineLearningServices.json
  - version: 2020-06-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2020-06-01/machineLearningServices.json
  - version: 2020-08-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2020-08-01/machineLearningServices.json
  - version: 2020-09-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2020-09-01-preview/jobs.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2020-09-01-preview/machineLearningServices.json
  - version: 2021-01-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2021-01-01/machineLearningServices.json
  - version: 2021-03-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2021-03-01-preview/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2021-03-01-preview/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2021-03-01-preview/workspaceFeatures.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2021-03-01-preview/workspaceSkus.json
  - version: 2021-04-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2021-04-01/machineLearningServices.json
  - version: 2021-07-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2021-07-01/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2021-07-01/workspaceFeatures.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2021-07-01/workspaceSkus.json
  - version: 2022-01-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/workspaceFeatures.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2022-01-01-preview/workspaceSkus.json
  - version: 2022-02-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2022-02-01-preview/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2022-02-01-preview/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2022-02-01-preview/workspaceFeatures.json
  - version: 2022-05-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2022-05-01/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2022-05-01/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2022-05-01/workspaceFeatures.json
  - version: 2022-06-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2022-06-01-preview/workspaceFeatures.json
  - version: 2022-10-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2022-10-01/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2022-10-01/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2022-10-01/workspaceFeatures.json
  - version: 2022-10-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2022-10-01-preview/workspaceFeatures.json
  - version: 2022-12-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2022-12-01-preview/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2022-12-01-preview/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2022-12-01-preview/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2022-12-01-preview/workspaceFeatures.json
  - version: 2023-02-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-02-01-preview/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-02-01-preview/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-02-01-preview/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-02-01-preview/workspaceFeatures.json
  - version: 2023-04-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2023-04-01/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2023-04-01/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2023-04-01/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2023-04-01/workspaceFeatures.json
  - version: 2023-04-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-04-01-preview/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-04-01-preview/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-04-01-preview/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-04-01-preview/workspaceFeatures.json
  - version: 2023-06-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceFeatures.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-06-01-preview/workspaceRP.json
  - version: 2023-08-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/workspaceFeatures.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2023-08-01-preview/workspaceRP.json
  - version: 2023-10-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2023-10-01/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2023-10-01/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2023-10-01/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2023-10-01/workspaceFeatures.json
  - version: 2024-01-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2024-01-01-preview/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2024-01-01-preview/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2024-01-01-preview/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2024-01-01-preview/workspaceFeatures.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2024-01-01-preview/workspaceRP.json
  - version: 2024-04-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2024-04-01/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2024-04-01/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2024-04-01/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2024-04-01/workspaceFeatures.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2024-04-01/workspaceRP.json
  - version: 2024-04-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2024-04-01-preview/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2024-04-01-preview/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2024-04-01-preview/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2024-04-01-preview/workspaceFeatures.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2024-04-01-preview/workspaceRP.json
  - version: 2024-07-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2024-07-01-preview/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2024-07-01-preview/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2024-07-01-preview/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2024-07-01-preview/workspaceFeatures.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2024-07-01-preview/workspaceRP.json
  - version: 2024-10-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2024-10-01/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2024-10-01/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2024-10-01/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2024-10-01/workspaceFeatures.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2024-10-01/workspaceRP.json
  - version: 2024-10-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2024-10-01-preview/openapi.json
  - version: 2025-01-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2025-01-01-preview/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2025-01-01-preview/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2025-01-01-preview/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2025-01-01-preview/workspaceFeatures.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2025-01-01-preview/workspaceRP.json
  - version: 2025-04-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2025-04-01/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2025-04-01/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2025-04-01/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2025-04-01/workspaceFeatures.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2025-04-01/workspaceRP.json
  - version: 2025-04-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2025-04-01-preview/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2025-04-01-preview/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2025-04-01-preview/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2025-04-01-preview/workspaceFeatures.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2025-04-01-preview/workspaceRP.json
  - version: 2025-06-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2025-06-01/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2025-06-01/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2025-06-01/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2025-06-01/workspaceFeatures.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2025-06-01/workspaceRP.json
  - version: 2025-07-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2025-07-01-preview/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2025-07-01-preview/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2025-07-01-preview/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2025-07-01-preview/workspaceFeatures.json
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2025-07-01-preview/workspaceRP.json
  - version: 2025-09-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2025-09-01/machineLearningServices.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2025-09-01/mfe.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2025-09-01/registries.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2025-09-01/workspaceFeatures.json
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2025-09-01/workspaceRP.json
  - version: 2025-10-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2025-10-01-preview/openapi.json
  - version: 2025-12-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2025-12-01/openapi.json
  - version: 2026-01-15-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2026-01-15-preview/openapi.json
  - version: 2026-03-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2026-03-01/openapi.json
  - version: 2026-03-15-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2026-03-15-preview/openapi.json
  - version: 2026-05-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/stable/2026-05-01/openapi.json
  - version: 2026-05-15-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.MachineLearningServices/preview/2026-05-15-preview/openapi.json
