versions:
  - version: 2022-08-17-preview
    source: swagger
    swagger-files:
      - preview/2022-08-17-preview/search.json
  - version: 2022-09-25-preview
    source: swagger
    swagger-files:
      - preview/2022-09-25-preview/search.json
  - version: 2023-01-01-preview
    source: swagger
    swagger-files:
      - preview/2023-01-01-preview/search.json
  - version: 2025-05-01
    source: typespec
    swagger-files:
      - stable/2025-05-01/openapi.json
