versions:
  - version: 2025-03-21
    source: typespec
    swagger-files:
      - stable/2025-03-21/Dell.Storage.json
  - version: 2025-03-21-preview
    source: typespec
    swagger-files:
      - preview/2025-03-21-preview/Dell.Storage.json
