versions:
  - version: 2018-09-01-preview
    source: swagger
    swagger-files:
      - ../preview/2018-09-01-preview/graphquery.json
  - version: 2019-04-01
    source: swagger
    swagger-files:
      - ../stable/2019-04-01/graphquery.json
  - version: 2021-03-01
    source: swagger
    swagger-files:
      - ../stable/2021-03-01/graphquery.json
  - version: 2022-10-01
    source: swagger
    swagger-files:
      - ../stable/2022-10-01/graphquery.json
  - version: 2024-04-01
    source: typespec
    swagger-files:
      - ../stable/2024-04-01/graphquery.json
