versions:
  - version: 2022-06-27-preview
    source: swagger
    swagger-files:
      - preview/2022-06-27-preview/Qumulo.Storage.json
  - version: 2022-10-12
    source: swagger
    swagger-files:
      - stable/2022-10-12/Qumulo.Storage.json
  - version: 2022-10-12-preview
    source: swagger
    swagger-files:
      - preview/2022-10-12-preview/Qumulo.Storage.json
  - version: 2024-06-19
    source: typespec
    swagger-files:
      - stable/2024-06-19/Qumulo.Storage.json
  - version: 2025-10-01-preview
    source: typespec
    swagger-files:
      - preview/2025-10-01-preview/Qumulo.Storage.json
  - version: 2026-02-17-preview
    source: typespec
    swagger-files:
      - preview/2026-02-17-preview/Qumulo.Storage.json
  - version: 2026-04-16
    source: typespec
    swagger-files:
      - stable/2026-04-16/Qumulo.Storage.json
