// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armavs

// AddonsClientBeginCreateOrUpdateOptions contains the optional parameters for the AddonsClient.CreateOrUpdate method.
type AddonsClientBeginCreateOrUpdateOptions struct {
	ResumeToken string
}

// AddonsClientBeginDeleteOptions contains the optional parameters for the AddonsClient.Delete method.
type AddonsClientBeginDeleteOptions struct {
	ResumeToken string
}

// AddonsClientGetOptions contains the optional parameters for the AddonsClient.Get method.
type AddonsClientGetOptions struct {
	// placeholder for future optional parameters
}

// AddonsClientListByPrivateCloudOptions contains the optional parameters for the AddonsClient.NewListByPrivateCloudPager
// method.
type AddonsClientListByPrivateCloudOptions struct {
	// placeholder for future optional parameters
}

// AuthorizationsClientBeginCreateOrUpdateOptions contains the optional parameters for the AuthorizationsClient.CreateOrUpdate
// method.
type AuthorizationsClientBeginCreateOrUpdateOptions struct {
	ResumeToken string
}

// AuthorizationsClientBeginDeleteOptions contains the optional parameters for the AuthorizationsClient.Delete method.
type AuthorizationsClientBeginDeleteOptions struct {
	ResumeToken string
}

// AuthorizationsClientGetOptions contains the optional parameters for the AuthorizationsClient.Get method.
type AuthorizationsClientGetOptions struct {
	// placeholder for future optional parameters
}

// AuthorizationsClientListByPrivateCloudOptions contains the optional parameters for the AuthorizationsClient.NewListByPrivateCloudPager
// method.
type AuthorizationsClientListByPrivateCloudOptions struct {
	// placeholder for future optional parameters
}

// CloudLinksClientBeginCreateOrUpdateOptions contains the optional parameters for the CloudLinksClient.CreateOrUpdate method.
type CloudLinksClientBeginCreateOrUpdateOptions struct {
	ResumeToken string
}

// CloudLinksClientBeginDeleteOptions contains the optional parameters for the CloudLinksClient.Delete method.
type CloudLinksClientBeginDeleteOptions struct {
	ResumeToken string
}

// CloudLinksClientGetOptions contains the optional parameters for the CloudLinksClient.Get method.
type CloudLinksClientGetOptions struct {
	// placeholder for future optional parameters
}

// CloudLinksClientListByPrivateCloudOptions contains the optional parameters for the CloudLinksClient.NewListByPrivateCloudPager
// method.
type CloudLinksClientListByPrivateCloudOptions struct {
	// placeholder for future optional parameters
}

// ClustersClientBeginCreateOrUpdateOptions contains the optional parameters for the ClustersClient.CreateOrUpdate method.
type ClustersClientBeginCreateOrUpdateOptions struct {
	ResumeToken string
}

// ClustersClientBeginDeleteOptions contains the optional parameters for the ClustersClient.Delete method.
type ClustersClientBeginDeleteOptions struct {
	ResumeToken string
}

// ClustersClientGetOptions contains the optional parameters for the ClustersClient.Get method.
type ClustersClientGetOptions struct {
	// placeholder for future optional parameters
}

// ClustersClientListByPrivateCloudOptions contains the optional parameters for the ClustersClient.NewListByPrivateCloudPager
// method.
type ClustersClientListByPrivateCloudOptions struct {
	// placeholder for future optional parameters
}

// ClustersClientListZonesOptions contains the optional parameters for the ClustersClient.ListZones method.
type ClustersClientListZonesOptions struct {
	// placeholder for future optional parameters
}

// ClustersClientUpdateOptions contains the optional parameters for the ClustersClient.Update method.
type ClustersClientUpdateOptions struct {
	// placeholder for future optional parameters
}

// DatastoresClientBeginCreateOrUpdateOptions contains the optional parameters for the DatastoresClient.CreateOrUpdate method.
type DatastoresClientBeginCreateOrUpdateOptions struct {
	ResumeToken string
}

// DatastoresClientBeginDeleteOptions contains the optional parameters for the DatastoresClient.Delete method.
type DatastoresClientBeginDeleteOptions struct {
	ResumeToken string
}

// DatastoresClientGetOptions contains the optional parameters for the DatastoresClient.Get method.
type DatastoresClientGetOptions struct {
	// placeholder for future optional parameters
}

// DatastoresClientListByClusterOptions contains the optional parameters for the DatastoresClient.NewListByClusterPager method.
type DatastoresClientListByClusterOptions struct {
	// placeholder for future optional parameters
}

// GlobalReachConnectionsClientBeginCreateOrUpdateOptions contains the optional parameters for the GlobalReachConnectionsClient.CreateOrUpdate
// method.
type GlobalReachConnectionsClientBeginCreateOrUpdateOptions struct {
	ResumeToken string
}

// GlobalReachConnectionsClientBeginDeleteOptions contains the optional parameters for the GlobalReachConnectionsClient.Delete
// method.
type GlobalReachConnectionsClientBeginDeleteOptions struct {
	ResumeToken string
}

// GlobalReachConnectionsClientGetOptions contains the optional parameters for the GlobalReachConnectionsClient.Get method.
type GlobalReachConnectionsClientGetOptions struct {
	// placeholder for future optional parameters
}

// GlobalReachConnectionsClientListByPrivateCloudOptions contains the optional parameters for the GlobalReachConnectionsClient.NewListByPrivateCloudPager
// method.
type GlobalReachConnectionsClientListByPrivateCloudOptions struct {
	// placeholder for future optional parameters
}

// HcxEnterpriseSitesClientCreateOrUpdateOptions contains the optional parameters for the HcxEnterpriseSitesClient.CreateOrUpdate
// method.
type HcxEnterpriseSitesClientCreateOrUpdateOptions struct {
	// placeholder for future optional parameters
}

// HcxEnterpriseSitesClientDeleteOptions contains the optional parameters for the HcxEnterpriseSitesClient.Delete method.
type HcxEnterpriseSitesClientDeleteOptions struct {
	// placeholder for future optional parameters
}

// HcxEnterpriseSitesClientGetOptions contains the optional parameters for the HcxEnterpriseSitesClient.Get method.
type HcxEnterpriseSitesClientGetOptions struct {
	// placeholder for future optional parameters
}

// HcxEnterpriseSitesClientListByPrivateCloudOptions contains the optional parameters for the HcxEnterpriseSitesClient.NewListByPrivateCloudPager
// method.
type HcxEnterpriseSitesClientListByPrivateCloudOptions struct {
	// placeholder for future optional parameters
}

// IscsiPathsClientBeginCreateOrUpdateOptions contains the optional parameters for the IscsiPathsClient.CreateOrUpdate method.
type IscsiPathsClientBeginCreateOrUpdateOptions struct {
	ResumeToken string
}

// IscsiPathsClientBeginDeleteOptions contains the optional parameters for the IscsiPathsClient.Delete method.
type IscsiPathsClientBeginDeleteOptions struct {
	ResumeToken string
}

// IscsiPathsClientGetOptions contains the optional parameters for the IscsiPathsClient.Get method.
type IscsiPathsClientGetOptions struct {
	// placeholder for future optional parameters
}

// IscsiPathsClientListByPrivateCloudOptions contains the optional parameters for the IscsiPathsClient.NewListByPrivateCloudPager
// method.
type IscsiPathsClientListByPrivateCloudOptions struct {
	// placeholder for future optional parameters
}

// LocationsClientCheckQuotaAvailabilityOptions contains the optional parameters for the LocationsClient.CheckQuotaAvailability
// method.
type LocationsClientCheckQuotaAvailabilityOptions struct {
	// placeholder for future optional parameters
}

// LocationsClientCheckTrialAvailabilityOptions contains the optional parameters for the LocationsClient.CheckTrialAvailability
// method.
type LocationsClientCheckTrialAvailabilityOptions struct {
	// Optionally, check for a specific SKU
	Sku *ResourceSKUType
}

// OperationsClientListOptions contains the optional parameters for the OperationsClient.NewListPager method.
type OperationsClientListOptions struct {
	// placeholder for future optional parameters
}

// PlacementPoliciesClientBeginDeleteOptions contains the optional parameters for the PlacementPoliciesClient.Delete method.
type PlacementPoliciesClientBeginDeleteOptions struct {
	ResumeToken string
}

// PlacementPoliciesClientCreateOrUpdateOptions contains the optional parameters for the PlacementPoliciesClient.CreateOrUpdate
// method.
type PlacementPoliciesClientCreateOrUpdateOptions struct {
	// placeholder for future optional parameters
}

// PlacementPoliciesClientGetOptions contains the optional parameters for the PlacementPoliciesClient.Get method.
type PlacementPoliciesClientGetOptions struct {
	// placeholder for future optional parameters
}

// PlacementPoliciesClientListByClusterOptions contains the optional parameters for the PlacementPoliciesClient.NewListByClusterPager
// method.
type PlacementPoliciesClientListByClusterOptions struct {
	// placeholder for future optional parameters
}

// PlacementPoliciesClientUpdateOptions contains the optional parameters for the PlacementPoliciesClient.Update method.
type PlacementPoliciesClientUpdateOptions struct {
	// placeholder for future optional parameters
}

// PrivateCloudsClientBeginCreateOrUpdateOptions contains the optional parameters for the PrivateCloudsClient.CreateOrUpdate
// method.
type PrivateCloudsClientBeginCreateOrUpdateOptions struct {
	ResumeToken string
}

// PrivateCloudsClientBeginDeleteOptions contains the optional parameters for the PrivateCloudsClient.Delete method.
type PrivateCloudsClientBeginDeleteOptions struct {
	ResumeToken string
}

// PrivateCloudsClientBeginRotateNsxtPasswordOptions contains the optional parameters for the PrivateCloudsClient.RotateNsxtPassword
// method.
type PrivateCloudsClientBeginRotateNsxtPasswordOptions struct {
	ResumeToken string
}

// PrivateCloudsClientBeginRotateVcenterPasswordOptions contains the optional parameters for the PrivateCloudsClient.RotateVcenterPassword
// method.
type PrivateCloudsClientBeginRotateVcenterPasswordOptions struct {
	ResumeToken string
}

// PrivateCloudsClientGetOptions contains the optional parameters for the PrivateCloudsClient.Get method.
type PrivateCloudsClientGetOptions struct {
	// placeholder for future optional parameters
}

// PrivateCloudsClientListAdminCredentialsOptions contains the optional parameters for the PrivateCloudsClient.ListAdminCredentials
// method.
type PrivateCloudsClientListAdminCredentialsOptions struct {
	// placeholder for future optional parameters
}

// PrivateCloudsClientListByResourceGroupOptions contains the optional parameters for the PrivateCloudsClient.NewListByResourceGroupPager
// method.
type PrivateCloudsClientListByResourceGroupOptions struct {
	// placeholder for future optional parameters
}

// PrivateCloudsClientListInSubscriptionOptions contains the optional parameters for the PrivateCloudsClient.NewListInSubscriptionPager
// method.
type PrivateCloudsClientListInSubscriptionOptions struct {
	// placeholder for future optional parameters
}

// PrivateCloudsClientUpdateOptions contains the optional parameters for the PrivateCloudsClient.Update method.
type PrivateCloudsClientUpdateOptions struct {
	// placeholder for future optional parameters
}

// ScriptCmdletsClientGetOptions contains the optional parameters for the ScriptCmdletsClient.Get method.
type ScriptCmdletsClientGetOptions struct {
	// placeholder for future optional parameters
}

// ScriptCmdletsClientListByScriptPackageOptions contains the optional parameters for the ScriptCmdletsClient.NewListByScriptPackagePager
// method.
type ScriptCmdletsClientListByScriptPackageOptions struct {
	// placeholder for future optional parameters
}

// ScriptExecutionsClientBeginCreateOrUpdateOptions contains the optional parameters for the ScriptExecutionsClient.CreateOrUpdate
// method.
type ScriptExecutionsClientBeginCreateOrUpdateOptions struct {
	ResumeToken string
}

// ScriptExecutionsClientBeginDeleteOptions contains the optional parameters for the ScriptExecutionsClient.Delete method.
type ScriptExecutionsClientBeginDeleteOptions struct {
	ResumeToken string
}

// ScriptExecutionsClientGetExecutionLogsOptions contains the optional parameters for the ScriptExecutionsClient.GetExecutionLogs
// method.
type ScriptExecutionsClientGetExecutionLogsOptions struct {
	// Name of the desired output stream to return. If not provided, will return all. An empty array will return nothing.
	ScriptOutputStreamType []*ScriptOutputStreamType
}

// ScriptExecutionsClientGetOptions contains the optional parameters for the ScriptExecutionsClient.Get method.
type ScriptExecutionsClientGetOptions struct {
	// placeholder for future optional parameters
}

// ScriptExecutionsClientListByPrivateCloudOptions contains the optional parameters for the ScriptExecutionsClient.NewListByPrivateCloudPager
// method.
type ScriptExecutionsClientListByPrivateCloudOptions struct {
	// placeholder for future optional parameters
}

// ScriptPackagesClientGetOptions contains the optional parameters for the ScriptPackagesClient.Get method.
type ScriptPackagesClientGetOptions struct {
	// placeholder for future optional parameters
}

// ScriptPackagesClientListByPrivateCloudOptions contains the optional parameters for the ScriptPackagesClient.NewListByPrivateCloudPager
// method.
type ScriptPackagesClientListByPrivateCloudOptions struct {
	// placeholder for future optional parameters
}

// VirtualMachinesClientBeginRestrictMovementOptions contains the optional parameters for the VirtualMachinesClient.RestrictMovement
// method.
type VirtualMachinesClientBeginRestrictMovementOptions struct {
	ResumeToken string
}

// VirtualMachinesClientGetOptions contains the optional parameters for the VirtualMachinesClient.Get method.
type VirtualMachinesClientGetOptions struct {
	// placeholder for future optional parameters
}

// VirtualMachinesClientListByClusterOptions contains the optional parameters for the VirtualMachinesClient.NewListByClusterPager
// method.
type VirtualMachinesClientListByClusterOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkDNSServicesClientBeginDeleteOptions contains the optional parameters for the WorkloadNetworkDNSServicesClient.Delete
// method.
type WorkloadNetworkDNSServicesClientBeginDeleteOptions struct {
	ResumeToken string
}

// WorkloadNetworkDNSServicesClientBeginUpdateOptions contains the optional parameters for the WorkloadNetworkDNSServicesClient.Update
// method.
type WorkloadNetworkDNSServicesClientBeginUpdateOptions struct {
	ResumeToken string
}

// WorkloadNetworkDNSServicesClientCreateOptions contains the optional parameters for the WorkloadNetworkDNSServicesClient.Create
// method.
type WorkloadNetworkDNSServicesClientCreateOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkDNSServicesClientGetOptions contains the optional parameters for the WorkloadNetworkDNSServicesClient.Get
// method.
type WorkloadNetworkDNSServicesClientGetOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkDNSServicesClientListByWorkloadNetworkOptions contains the optional parameters for the WorkloadNetworkDNSServicesClient.NewListByWorkloadNetworkPager
// method.
type WorkloadNetworkDNSServicesClientListByWorkloadNetworkOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkDNSZonesClientBeginDeleteOptions contains the optional parameters for the WorkloadNetworkDNSZonesClient.Delete
// method.
type WorkloadNetworkDNSZonesClientBeginDeleteOptions struct {
	ResumeToken string
}

// WorkloadNetworkDNSZonesClientBeginUpdateOptions contains the optional parameters for the WorkloadNetworkDNSZonesClient.Update
// method.
type WorkloadNetworkDNSZonesClientBeginUpdateOptions struct {
	ResumeToken string
}

// WorkloadNetworkDNSZonesClientCreateOptions contains the optional parameters for the WorkloadNetworkDNSZonesClient.Create
// method.
type WorkloadNetworkDNSZonesClientCreateOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkDNSZonesClientGetOptions contains the optional parameters for the WorkloadNetworkDNSZonesClient.Get method.
type WorkloadNetworkDNSZonesClientGetOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkDNSZonesClientListByWorkloadNetworkOptions contains the optional parameters for the WorkloadNetworkDNSZonesClient.NewListByWorkloadNetworkPager
// method.
type WorkloadNetworkDNSZonesClientListByWorkloadNetworkOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkDhcpConfigurationsClientBeginDeleteOptions contains the optional parameters for the WorkloadNetworkDhcpConfigurationsClient.Delete
// method.
type WorkloadNetworkDhcpConfigurationsClientBeginDeleteOptions struct {
	ResumeToken string
}

// WorkloadNetworkDhcpConfigurationsClientBeginUpdateOptions contains the optional parameters for the WorkloadNetworkDhcpConfigurationsClient.Update
// method.
type WorkloadNetworkDhcpConfigurationsClientBeginUpdateOptions struct {
	ResumeToken string
}

// WorkloadNetworkDhcpConfigurationsClientCreateOptions contains the optional parameters for the WorkloadNetworkDhcpConfigurationsClient.Create
// method.
type WorkloadNetworkDhcpConfigurationsClientCreateOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkDhcpConfigurationsClientGetOptions contains the optional parameters for the WorkloadNetworkDhcpConfigurationsClient.Get
// method.
type WorkloadNetworkDhcpConfigurationsClientGetOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkDhcpConfigurationsClientListByWorkloadNetworkOptions contains the optional parameters for the WorkloadNetworkDhcpConfigurationsClient.NewListByWorkloadNetworkPager
// method.
type WorkloadNetworkDhcpConfigurationsClientListByWorkloadNetworkOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkGatewaysClientGetOptions contains the optional parameters for the WorkloadNetworkGatewaysClient.Get method.
type WorkloadNetworkGatewaysClientGetOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkGatewaysClientListByWorkloadNetworkOptions contains the optional parameters for the WorkloadNetworkGatewaysClient.NewListByWorkloadNetworkPager
// method.
type WorkloadNetworkGatewaysClientListByWorkloadNetworkOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkPortMirroringProfilesClientBeginDeleteOptions contains the optional parameters for the WorkloadNetworkPortMirroringProfilesClient.Delete
// method.
type WorkloadNetworkPortMirroringProfilesClientBeginDeleteOptions struct {
	ResumeToken string
}

// WorkloadNetworkPortMirroringProfilesClientBeginUpdateOptions contains the optional parameters for the WorkloadNetworkPortMirroringProfilesClient.Update
// method.
type WorkloadNetworkPortMirroringProfilesClientBeginUpdateOptions struct {
	ResumeToken string
}

// WorkloadNetworkPortMirroringProfilesClientCreateOptions contains the optional parameters for the WorkloadNetworkPortMirroringProfilesClient.Create
// method.
type WorkloadNetworkPortMirroringProfilesClientCreateOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkPortMirroringProfilesClientGetOptions contains the optional parameters for the WorkloadNetworkPortMirroringProfilesClient.Get
// method.
type WorkloadNetworkPortMirroringProfilesClientGetOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkPortMirroringProfilesClientListByWorkloadNetworkOptions contains the optional parameters for the WorkloadNetworkPortMirroringProfilesClient.NewListByWorkloadNetworkPager
// method.
type WorkloadNetworkPortMirroringProfilesClientListByWorkloadNetworkOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkPublicIPsClientBeginDeleteOptions contains the optional parameters for the WorkloadNetworkPublicIPsClient.Delete
// method.
type WorkloadNetworkPublicIPsClientBeginDeleteOptions struct {
	ResumeToken string
}

// WorkloadNetworkPublicIPsClientCreateOptions contains the optional parameters for the WorkloadNetworkPublicIPsClient.Create
// method.
type WorkloadNetworkPublicIPsClientCreateOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkPublicIPsClientGetOptions contains the optional parameters for the WorkloadNetworkPublicIPsClient.Get method.
type WorkloadNetworkPublicIPsClientGetOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkPublicIPsClientListByWorkloadNetworkOptions contains the optional parameters for the WorkloadNetworkPublicIPsClient.NewListByWorkloadNetworkPager
// method.
type WorkloadNetworkPublicIPsClientListByWorkloadNetworkOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkSegmentsClientBeginDeleteSegmentOptions contains the optional parameters for the WorkloadNetworkSegmentsClient.DeleteSegment
// method.
type WorkloadNetworkSegmentsClientBeginDeleteSegmentOptions struct {
	ResumeToken string
}

// WorkloadNetworkSegmentsClientBeginUpdateOptions contains the optional parameters for the WorkloadNetworkSegmentsClient.Update
// method.
type WorkloadNetworkSegmentsClientBeginUpdateOptions struct {
	ResumeToken string
}

// WorkloadNetworkSegmentsClientCreateOptions contains the optional parameters for the WorkloadNetworkSegmentsClient.Create
// method.
type WorkloadNetworkSegmentsClientCreateOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkSegmentsClientGetOptions contains the optional parameters for the WorkloadNetworkSegmentsClient.Get method.
type WorkloadNetworkSegmentsClientGetOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkSegmentsClientListByWorkloadNetworkOptions contains the optional parameters for the WorkloadNetworkSegmentsClient.NewListByWorkloadNetworkPager
// method.
type WorkloadNetworkSegmentsClientListByWorkloadNetworkOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkVMGroupsClientBeginDeleteOptions contains the optional parameters for the WorkloadNetworkVMGroupsClient.Delete
// method.
type WorkloadNetworkVMGroupsClientBeginDeleteOptions struct {
	ResumeToken string
}

// WorkloadNetworkVMGroupsClientBeginUpdateOptions contains the optional parameters for the WorkloadNetworkVMGroupsClient.Update
// method.
type WorkloadNetworkVMGroupsClientBeginUpdateOptions struct {
	ResumeToken string
}

// WorkloadNetworkVMGroupsClientCreateOptions contains the optional parameters for the WorkloadNetworkVMGroupsClient.Create
// method.
type WorkloadNetworkVMGroupsClientCreateOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkVMGroupsClientGetOptions contains the optional parameters for the WorkloadNetworkVMGroupsClient.Get method.
type WorkloadNetworkVMGroupsClientGetOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkVMGroupsClientListByWorkloadNetworkOptions contains the optional parameters for the WorkloadNetworkVMGroupsClient.NewListByWorkloadNetworkPager
// method.
type WorkloadNetworkVMGroupsClientListByWorkloadNetworkOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkVirtualMachinesClientGetOptions contains the optional parameters for the WorkloadNetworkVirtualMachinesClient.Get
// method.
type WorkloadNetworkVirtualMachinesClientGetOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworkVirtualMachinesClientListByWorkloadNetworkOptions contains the optional parameters for the WorkloadNetworkVirtualMachinesClient.NewListByWorkloadNetworkPager
// method.
type WorkloadNetworkVirtualMachinesClientListByWorkloadNetworkOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworksClientGetOptions contains the optional parameters for the WorkloadNetworksClient.Get method.
type WorkloadNetworksClientGetOptions struct {
	// placeholder for future optional parameters
}

// WorkloadNetworksClientListByPrivateCloudOptions contains the optional parameters for the WorkloadNetworksClient.NewListByPrivateCloudPager
// method.
type WorkloadNetworksClientListByPrivateCloudOptions struct {
	// placeholder for future optional parameters
}
