versions:
  - version: 2023-12-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.StandbyPool/preview/2023-12-01-preview/standbypool.json
  - version: 2024-03-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.StandbyPool/stable/2024-03-01/standbypool.json
  - version: 2024-03-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.StandbyPool/preview/2024-03-01-preview/standbypool.json
  - version: 2025-03-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.StandbyPool/stable/2025-03-01/standbypool.json
  - version: 2025-10-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.StandbyPool/stable/2025-10-01/standbypool.json
  - version: 2026-04-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.StandbyPool/stable/2026-04-01/standbypool.json
