versions:
  - version: 2024-03-01-preview
    source: typespec
    swagger-files:
      - preview/2024-03-01-preview/mongoCluster.json
  - version: 2024-06-01-preview
    source: typespec
    swagger-files:
      - preview/2024-06-01-preview/mongoCluster.json
  - version: 2024-07-01
    source: typespec
    swagger-files:
      - stable/2024-07-01/mongoCluster.json
  - version: 2024-10-01-preview
    source: typespec
    swagger-files:
      - preview/2024-10-01-preview/mongoCluster.json
  - version: 2025-04-01-preview
    source: typespec
    swagger-files:
      - preview/2025-04-01-preview/mongoCluster.json
  - version: 2025-07-01-preview
    source: typespec
    swagger-files:
      - preview/2025-07-01-preview/mongoCluster.json
  - version: 2025-08-01-preview
    source: typespec
    swagger-files:
      - preview/2025-08-01-preview/mongoCluster.json
  - version: 2025-09-01
    source: typespec
    swagger-files:
      - stable/2025-09-01/mongoCluster.json
  - version: 2026-02-01-preview
    source: typespec
    swagger-files:
      - preview/2026-02-01-preview/mongoCluster.json
  - version: 2026-06-01
    source: typespec
    swagger-files:
      - stable/2026-06-01/mongoCluster.json
