versions:
  - version: 2024-04-01-preview
    source: typespec
    swagger-files:
      - preview/2024-04-01-preview/deviceupdate.json
  - version: 2024-10-01-preview
    source: typespec
    swagger-files:
      - preview/2024-10-01-preview/deviceupdate.json
  - version: 2025-04-01-preview
    source: typespec
    swagger-files:
      - preview/2025-04-01-preview/deviceupdate.json
  - version: 2025-05-01-preview
    source: typespec
    swagger-files:
      - preview/2025-05-01-preview/deviceupdate.json
