versions:
  - version: 2026-06-06
    source: typespec
    swagger-files:
      - stable/2026-06-06/generated_file.json
  - version: 2026-10-06
    source: typespec
    swagger-files:
      - stable/2026-10-06/generated_file.json
  - version: 2026-12-06
    source: typespec
    swagger-files:
      - stable/2026-12-06/generated_file.json
