parameters:
  "service-dir":
    default: "sdk/storage"
  "dependencies":
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}"
    examples-dir: "{project-root}/examples"
    output-file: "{version-status}/{version}/generated_file.json"
  "@azure-tools/typespec-python":
    flavor: azure
    "package-name": "azure-storage-file-share"
    "package-pprint-name": "Azure Storage File Share"
    "namespace": "azure.storage.fileshare._generated"
    package-mode: dataplane
    emitter-output-dir: "{output-dir}/{service-dir}/azure-storage-file-share"
  "@azure-typespec/http-client-csharp":
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
    namespace: "Azure.Storage.Files.Shares"
    model-namespace: true
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/storage-file-share"
    generate-metadata: false
    generate-test: false
    include-headers-in-response: true
    enable-storage-compat: true
    experimental-extensible-enums: true
    package-details:
      name: "@azure/storage-file-share"
      description: "Azure.Storage.File Service"
    flavor: azure
  # "@azure-tools/typespec-java":
  #   emitter-output-dir: "{output-dir}/{service-dir}/azure-storage-file"
  #   namespace: com.azure.storage.file
  #   flavor: azure
  # "@azure-tools/typespec-rust":
  #   package-dir: "azure_storage_file"
  #   crate-name: "azure_storage_file"
  #   crate-version: "0.1.0"
  #   flavor: azure
  #   temp-omit-doc-links: true
  # TODO: Replace this with client.tsp solution once it lands (issue: https://github.com/Azure/typespec-rust/issues/806)
  #   omit-constructors: true
  "@azure-tools/typespec-go":
    containing-module: "github.com/Azure/azure-sdk-for-go/sdk/storage/azfile"
    service-dir: "sdk/storage"
    emitter-output-dir: "{output-dir}/{service-dir}/azfile/internal/generated"
    generate-fakes: false
    file-prefix: "zz_"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
