versions:
  - version: 2021-10-20-preview2
    source: swagger
    swagger-files:
      - ../data-plane/JobRouter/preview/2021-10-20-preview2/communicationservicejobrouter.json
  - version: 2022-07-18-preview
    source: swagger
    swagger-files:
      - ../data-plane/JobRouter/preview/2022-07-18-preview/communicationservicejobrouter.json
  - version: 2023-11-01
    source: typespec
    swagger-files:
      - ../data-plane/JobRouter/stable/2023-11-01/communicationservicejobrouter.json
  - version: 2024-01-18-preview
    source: typespec
    swagger-files:
      - ../data-plane/JobRouter/preview/2024-01-18-preview/communicationservicejobrouter.json
