versions:
  - version: 2024-06-01-preview
    source: typespec
    swagger-files:
      - preview/2024-06-01-preview/openapi.json
  - version: 2024-12-01-preview
    source: typespec
    swagger-files:
      - preview/2024-12-01-preview/openapi.json
  - version: 2025-05-01-preview
    source: typespec
    swagger-files:
      - preview/2025-05-01-preview/openapi.json
  - version: 2025-11-01-preview
    source: typespec
    swagger-files:
      - preview/2025-11-01-preview/openapi.json
  - version: 2026-03-01-preview
    source: typespec
    swagger-files:
      - preview/2026-03-01-preview/openapi.json
