emit:
- '@azure-tools/typespec-autorest'
linter:
  extends:
  - '@azure-tools/typespec-azure-rulesets/resource-manager'
options:
  '@azure-tools/typespec-autorest':
    azure-resource-provider-folder: resource-manager
    emit-lro-options: all
    emitter-output-dir: '{project-root}/..'
    examples-dir: '{project-root}/examples'
    omit-unreachable-types: true
    output-file: '{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/billingbenefits.json'
  '@azure-tools/typespec-go':
    emitter-output-dir: '{output-dir}/{service-dir}/armbillingbenefits'
    factory-gather-all-params: false
    fix-const-stuttering: true
    flavor: azure
    generate-fakes: true
    generate-samples: true
    head-as-boolean: true
    inject-spans: true
    module: github.com/Azure/azure-sdk-for-go/{service-dir}/armbillingbenefits/v2
    service-dir: sdk/resourcemanager/billingbenefits
  '@azure-tools/typespec-java':
    emitter-output-dir: '{output-dir}/{service-dir}/azure-resourcemanager-billingbenefits'
    flavor: azure
    namespace: com.azure.resourcemanager.billingbenefits
    service-name: BillingBenefits
  '@azure-tools/typespec-python':
    api-version: 2025-12-01-preview
    emitter-output-dir: '{output-dir}/{service-dir}/azure-mgmt-billingbenefits'
    flavor: azure
    generate-sample: true
    generate-test: true
    namespace: azure.mgmt.billingbenefits
  '@azure-tools/typespec-ts':
    emitter-output-dir: '{output-dir}/{service-dir}/arm-billingbenefits'
    experimental-extensible-enums: true
    flavor: azure
    is-modular-library: true
    package-details:
      name: '@azure/arm-billingbenefits'
    typespec-title-map:
      BillingBenefitsClient: BillingBenefitsRP
parameters:
  service-dir:
    default: sdk/billingbenefits
