versions:
  - version: "1.0"
    source: swagger
    swagger-files:
      - stable/1.0/traffic.json
  - version: 2025-01-01
    source: typespec
    swagger-files:
      - stable/2025-01-01/traffic.json
