versions:
  - version: 2024-03-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/SplitIO.Experimentation/preview/2024-03-01-preview/splitio.json
  - version: 2024-07-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/SplitIO.Experimentation/preview/2024-07-01-preview/splitio.json
