versions:
  - version: 2024-11-01
    source: typespec
    swagger-files:
      - stable/2024-11-01/redis.json
  - version: 2025-08-01-preview
    source: typespec
    swagger-files:
      - preview/2025-08-01-preview/redis.json
