versions:
  - version: 2025-10-08
    source: typespec
    swagger-files:
      - ../resource-manager/PaloAltoNetworks.Cloudngfw/stable/2025-10-08/PaloAltoNetworks.Cloudngfw.json
  - version: 2026-01-26-preview
    source: typespec
    swagger-files:
      - ../resource-manager/PaloAltoNetworks.Cloudngfw/preview/2026-01-26-preview/PaloAltoNetworks.Cloudngfw.json
  - version: 2026-05-11-preview
    source: typespec
    swagger-files:
      - ../resource-manager/PaloAltoNetworks.Cloudngfw/preview/2026-05-11-preview/PaloAltoNetworks.Cloudngfw.json
