versions:
  - version: 2017-09-07-privatepreview
    source: swagger
    swagger-files:
      - preview/2017-09-07-privatepreview/kusto.json
  - version: 2018-09-07-preview
    source: swagger
    swagger-files:
      - preview/2018-09-07-preview/kusto.json
  - version: 2019-01-21
    source: swagger
    swagger-files:
      - stable/2019-01-21/kusto.json
  - version: 2019-05-15
    source: swagger
    swagger-files:
      - stable/2019-05-15/kusto.json
  - version: 2019-09-07
    source: swagger
    swagger-files:
      - stable/2019-09-07/kusto.json
  - version: 2019-11-09
    source: swagger
    swagger-files:
      - stable/2019-11-09/kusto.json
  - version: 2020-02-15
    source: swagger
    swagger-files:
      - stable/2020-02-15/kusto.json
  - version: 2020-06-14
    source: swagger
    swagger-files:
      - stable/2020-06-14/kusto.json
  - version: 2020-09-18
    source: swagger
    swagger-files:
      - stable/2020-09-18/kusto.json
  - version: 2021-01-01
    source: swagger
    swagger-files:
      - stable/2021-01-01/kusto.json
  - version: 2021-08-27
    source: swagger
    swagger-files:
      - stable/2021-08-27/kusto.json
  - version: 2022-02-01
    source: swagger
    swagger-files:
      - stable/2022-02-01/kusto.json
  - version: 2022-07-07
    source: swagger
    swagger-files:
      - stable/2022-07-07/kusto.json
  - version: 2022-11-11
    source: swagger
    swagger-files:
      - stable/2022-11-11/kusto.json
  - version: 2022-12-29
    source: swagger
    swagger-files:
      - stable/2022-12-29/kusto.json
  - version: 2023-05-02
    source: swagger
    swagger-files:
      - stable/2023-05-02/kusto.json
  - version: 2023-08-15
    source: swagger
    swagger-files:
      - stable/2023-08-15/kusto.json
  - version: 2024-04-13
    source: swagger
    swagger-files:
      - stable/2024-04-13/kusto.json
  - version: 2025-02-14
    source: typespec
    swagger-files:
      - stable/2025-02-14/kusto.json
