// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.costmanagement.implementation;

import com.azure.core.annotation.BodyParam;
import com.azure.core.annotation.Delete;
import com.azure.core.annotation.ExpectedResponses;
import com.azure.core.annotation.Get;
import com.azure.core.annotation.HeaderParam;
import com.azure.core.annotation.Headers;
import com.azure.core.annotation.Host;
import com.azure.core.annotation.HostParam;
import com.azure.core.annotation.PathParam;
import com.azure.core.annotation.Post;
import com.azure.core.annotation.Put;
import com.azure.core.annotation.QueryParam;
import com.azure.core.annotation.ReturnType;
import com.azure.core.annotation.ServiceInterface;
import com.azure.core.annotation.ServiceMethod;
import com.azure.core.annotation.UnexpectedResponseExceptionType;
import com.azure.core.http.rest.PagedFlux;
import com.azure.core.http.rest.PagedIterable;
import com.azure.core.http.rest.PagedResponse;
import com.azure.core.http.rest.PagedResponseBase;
import com.azure.core.http.rest.Response;
import com.azure.core.http.rest.RestProxy;
import com.azure.core.management.exception.ManagementException;
import com.azure.core.util.Context;
import com.azure.core.util.FluxUtil;
import com.azure.resourcemanager.costmanagement.fluent.CostAllocationRulesClient;
import com.azure.resourcemanager.costmanagement.fluent.models.CostAllocationRuleCheckNameAvailabilityResponseInner;
import com.azure.resourcemanager.costmanagement.fluent.models.CostAllocationRuleDefinitionInner;
import com.azure.resourcemanager.costmanagement.implementation.models.CostAllocationRuleList;
import com.azure.resourcemanager.costmanagement.models.CostAllocationRuleCheckNameAvailabilityRequest;
import reactor.core.publisher.Mono;

/**
 * An instance of this class provides access to all the operations defined in CostAllocationRulesClient.
 */
public final class CostAllocationRulesClientImpl implements CostAllocationRulesClient {
    /**
     * The proxy service used to perform REST calls.
     */
    private final CostAllocationRulesService service;

    /**
     * The service client containing this operation class.
     */
    private final CostManagementManagementClientImpl client;

    /**
     * Initializes an instance of CostAllocationRulesClientImpl.
     * 
     * @param client the instance of the service client containing this operation class.
     */
    CostAllocationRulesClientImpl(CostManagementManagementClientImpl client) {
        this.service = RestProxy.create(CostAllocationRulesService.class, client.getHttpPipeline(),
            client.getSerializerAdapter());
        this.client = client;
    }

    /**
     * The interface defining all the services for CostManagementManagementClientCostAllocationRules to be used by the
     * proxy service to perform REST calls.
     */
    @Host("{endpoint}")
    @ServiceInterface(name = "CostManagementManagementClientCostAllocationRules")
    public interface CostAllocationRulesService {
        @Headers({ "Content-Type: application/json" })
        @Get("/providers/microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.CostManagement/costAllocationRules/{ruleName}")
        @ExpectedResponses({ 200 })
        @UnexpectedResponseExceptionType(ManagementException.class)
        Mono<Response<CostAllocationRuleDefinitionInner>> get(@HostParam("endpoint") String endpoint,
            @QueryParam("api-version") String apiVersion, @PathParam("billingAccountId") String billingAccountId,
            @PathParam("ruleName") String ruleName, @HeaderParam("Accept") String accept, Context context);

        @Headers({ "Content-Type: application/json" })
        @Get("/providers/microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.CostManagement/costAllocationRules/{ruleName}")
        @ExpectedResponses({ 200 })
        @UnexpectedResponseExceptionType(ManagementException.class)
        Response<CostAllocationRuleDefinitionInner> getSync(@HostParam("endpoint") String endpoint,
            @QueryParam("api-version") String apiVersion, @PathParam("billingAccountId") String billingAccountId,
            @PathParam("ruleName") String ruleName, @HeaderParam("Accept") String accept, Context context);

        @Put("/providers/microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.CostManagement/costAllocationRules/{ruleName}")
        @ExpectedResponses({ 200, 201 })
        @UnexpectedResponseExceptionType(ManagementException.class)
        Mono<Response<CostAllocationRuleDefinitionInner>> createOrUpdate(@HostParam("endpoint") String endpoint,
            @QueryParam("api-version") String apiVersion, @PathParam("billingAccountId") String billingAccountId,
            @PathParam("ruleName") String ruleName, @HeaderParam("Content-Type") String contentType,
            @HeaderParam("Accept") String accept,
            @BodyParam("application/json") CostAllocationRuleDefinitionInner costAllocationRule, Context context);

        @Put("/providers/microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.CostManagement/costAllocationRules/{ruleName}")
        @ExpectedResponses({ 200, 201 })
        @UnexpectedResponseExceptionType(ManagementException.class)
        Response<CostAllocationRuleDefinitionInner> createOrUpdateSync(@HostParam("endpoint") String endpoint,
            @QueryParam("api-version") String apiVersion, @PathParam("billingAccountId") String billingAccountId,
            @PathParam("ruleName") String ruleName, @HeaderParam("Content-Type") String contentType,
            @HeaderParam("Accept") String accept,
            @BodyParam("application/json") CostAllocationRuleDefinitionInner costAllocationRule, Context context);

        @Headers({ "Accept: application/json;q=0.9", "Content-Type: application/json" })
        @Delete("/providers/microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.CostManagement/costAllocationRules/{ruleName}")
        @ExpectedResponses({ 200, 204 })
        @UnexpectedResponseExceptionType(ManagementException.class)
        Mono<Response<Void>> delete(@HostParam("endpoint") String endpoint,
            @QueryParam("api-version") String apiVersion, @PathParam("billingAccountId") String billingAccountId,
            @PathParam("ruleName") String ruleName, Context context);

        @Headers({ "Accept: application/json;q=0.9", "Content-Type: application/json" })
        @Delete("/providers/microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.CostManagement/costAllocationRules/{ruleName}")
        @ExpectedResponses({ 200, 204 })
        @UnexpectedResponseExceptionType(ManagementException.class)
        Response<Void> deleteSync(@HostParam("endpoint") String endpoint, @QueryParam("api-version") String apiVersion,
            @PathParam("billingAccountId") String billingAccountId, @PathParam("ruleName") String ruleName,
            Context context);

        @Headers({ "Content-Type: application/json" })
        @Get("/providers/microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.CostManagement/costAllocationRules")
        @ExpectedResponses({ 200 })
        @UnexpectedResponseExceptionType(ManagementException.class)
        Mono<Response<CostAllocationRuleList>> list(@HostParam("endpoint") String endpoint,
            @QueryParam("api-version") String apiVersion, @PathParam("billingAccountId") String billingAccountId,
            @HeaderParam("Accept") String accept, Context context);

        @Headers({ "Content-Type: application/json" })
        @Get("/providers/microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.CostManagement/costAllocationRules")
        @ExpectedResponses({ 200 })
        @UnexpectedResponseExceptionType(ManagementException.class)
        Response<CostAllocationRuleList> listSync(@HostParam("endpoint") String endpoint,
            @QueryParam("api-version") String apiVersion, @PathParam("billingAccountId") String billingAccountId,
            @HeaderParam("Accept") String accept, Context context);

        @Post("/providers/microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.CostManagement/costAllocationRules/checkNameAvailability")
        @ExpectedResponses({ 200 })
        @UnexpectedResponseExceptionType(ManagementException.class)
        Mono<Response<CostAllocationRuleCheckNameAvailabilityResponseInner>> checkNameAvailability(
            @HostParam("endpoint") String endpoint, @QueryParam("api-version") String apiVersion,
            @PathParam("billingAccountId") String billingAccountId, @HeaderParam("Content-Type") String contentType,
            @HeaderParam("Accept") String accept,
            @BodyParam("application/json") CostAllocationRuleCheckNameAvailabilityRequest costAllocationRuleCheckNameAvailabilityRequest,
            Context context);

        @Post("/providers/microsoft.Billing/billingAccounts/{billingAccountId}/providers/Microsoft.CostManagement/costAllocationRules/checkNameAvailability")
        @ExpectedResponses({ 200 })
        @UnexpectedResponseExceptionType(ManagementException.class)
        Response<CostAllocationRuleCheckNameAvailabilityResponseInner> checkNameAvailabilitySync(
            @HostParam("endpoint") String endpoint, @QueryParam("api-version") String apiVersion,
            @PathParam("billingAccountId") String billingAccountId, @HeaderParam("Content-Type") String contentType,
            @HeaderParam("Accept") String accept,
            @BodyParam("application/json") CostAllocationRuleCheckNameAvailabilityRequest costAllocationRuleCheckNameAvailabilityRequest,
            Context context);

        @Headers({ "Content-Type: application/json" })
        @Get("{nextLink}")
        @ExpectedResponses({ 200 })
        @UnexpectedResponseExceptionType(ManagementException.class)
        Mono<Response<CostAllocationRuleList>> listNext(@PathParam(value = "nextLink", encoded = true) String nextLink,
            @HostParam("endpoint") String endpoint, @HeaderParam("Accept") String accept, Context context);

        @Headers({ "Content-Type: application/json" })
        @Get("{nextLink}")
        @ExpectedResponses({ 200 })
        @UnexpectedResponseExceptionType(ManagementException.class)
        Response<CostAllocationRuleList> listNextSync(@PathParam(value = "nextLink", encoded = true) String nextLink,
            @HostParam("endpoint") String endpoint, @HeaderParam("Accept") String accept, Context context);
    }

    /**
     * Get a cost allocation rule by rule name and billing account or enterprise enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param ruleName Cost allocation rule name. The name cannot include spaces or any non alphanumeric characters
     * other than '_' and '-'. The max length is 260 characters.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a cost allocation rule by rule name and billing account or enterprise enrollment along with
     * {@link Response} on successful completion of {@link Mono}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private Mono<Response<CostAllocationRuleDefinitionInner>> getWithResponseAsync(String billingAccountId,
        String ruleName) {
        final String accept = "application/json";
        return FluxUtil
            .withContext(context -> service.get(this.client.getEndpoint(), this.client.getApiVersion(),
                billingAccountId, ruleName, accept, context))
            .contextWrite(context -> context.putAll(FluxUtil.toReactorContext(this.client.getContext()).readOnly()));
    }

    /**
     * Get a cost allocation rule by rule name and billing account or enterprise enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param ruleName Cost allocation rule name. The name cannot include spaces or any non alphanumeric characters
     * other than '_' and '-'. The max length is 260 characters.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a cost allocation rule by rule name and billing account or enterprise enrollment on successful completion
     * of {@link Mono}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private Mono<CostAllocationRuleDefinitionInner> getAsync(String billingAccountId, String ruleName) {
        return getWithResponseAsync(billingAccountId, ruleName).flatMap(res -> Mono.justOrEmpty(res.getValue()));
    }

    /**
     * Get a cost allocation rule by rule name and billing account or enterprise enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param ruleName Cost allocation rule name. The name cannot include spaces or any non alphanumeric characters
     * other than '_' and '-'. The max length is 260 characters.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a cost allocation rule by rule name and billing account or enterprise enrollment along with
     * {@link Response}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<CostAllocationRuleDefinitionInner> getWithResponse(String billingAccountId, String ruleName,
        Context context) {
        final String accept = "application/json";
        return service.getSync(this.client.getEndpoint(), this.client.getApiVersion(), billingAccountId, ruleName,
            accept, context);
    }

    /**
     * Get a cost allocation rule by rule name and billing account or enterprise enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param ruleName Cost allocation rule name. The name cannot include spaces or any non alphanumeric characters
     * other than '_' and '-'. The max length is 260 characters.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return a cost allocation rule by rule name and billing account or enterprise enrollment.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public CostAllocationRuleDefinitionInner get(String billingAccountId, String ruleName) {
        return getWithResponse(billingAccountId, ruleName, Context.NONE).getValue();
    }

    /**
     * Create/Update a rule to allocate cost between different resources within a billing account or enterprise
     * enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param ruleName Cost allocation rule name. The name cannot include spaces or any non alphanumeric characters
     * other than '_' and '-'. The max length is 260 characters.
     * @param costAllocationRule Cost allocation rule to be created or updated.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the cost allocation rule model definition along with {@link Response} on successful completion of
     * {@link Mono}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private Mono<Response<CostAllocationRuleDefinitionInner>> createOrUpdateWithResponseAsync(String billingAccountId,
        String ruleName, CostAllocationRuleDefinitionInner costAllocationRule) {
        final String contentType = "application/json";
        final String accept = "application/json";
        return FluxUtil
            .withContext(context -> service.createOrUpdate(this.client.getEndpoint(), this.client.getApiVersion(),
                billingAccountId, ruleName, contentType, accept, costAllocationRule, context))
            .contextWrite(context -> context.putAll(FluxUtil.toReactorContext(this.client.getContext()).readOnly()));
    }

    /**
     * Create/Update a rule to allocate cost between different resources within a billing account or enterprise
     * enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param ruleName Cost allocation rule name. The name cannot include spaces or any non alphanumeric characters
     * other than '_' and '-'. The max length is 260 characters.
     * @param costAllocationRule Cost allocation rule to be created or updated.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the cost allocation rule model definition on successful completion of {@link Mono}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private Mono<CostAllocationRuleDefinitionInner> createOrUpdateAsync(String billingAccountId, String ruleName,
        CostAllocationRuleDefinitionInner costAllocationRule) {
        return createOrUpdateWithResponseAsync(billingAccountId, ruleName, costAllocationRule)
            .flatMap(res -> Mono.justOrEmpty(res.getValue()));
    }

    /**
     * Create/Update a rule to allocate cost between different resources within a billing account or enterprise
     * enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param ruleName Cost allocation rule name. The name cannot include spaces or any non alphanumeric characters
     * other than '_' and '-'. The max length is 260 characters.
     * @param costAllocationRule Cost allocation rule to be created or updated.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the cost allocation rule model definition along with {@link Response}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<CostAllocationRuleDefinitionInner> createOrUpdateWithResponse(String billingAccountId,
        String ruleName, CostAllocationRuleDefinitionInner costAllocationRule, Context context) {
        final String contentType = "application/json";
        final String accept = "application/json";
        return service.createOrUpdateSync(this.client.getEndpoint(), this.client.getApiVersion(), billingAccountId,
            ruleName, contentType, accept, costAllocationRule, context);
    }

    /**
     * Create/Update a rule to allocate cost between different resources within a billing account or enterprise
     * enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param ruleName Cost allocation rule name. The name cannot include spaces or any non alphanumeric characters
     * other than '_' and '-'. The max length is 260 characters.
     * @param costAllocationRule Cost allocation rule to be created or updated.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the cost allocation rule model definition.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public CostAllocationRuleDefinitionInner createOrUpdate(String billingAccountId, String ruleName,
        CostAllocationRuleDefinitionInner costAllocationRule) {
        return createOrUpdateWithResponse(billingAccountId, ruleName, costAllocationRule, Context.NONE).getValue();
    }

    /**
     * Delete cost allocation rule for billing account or enterprise enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param ruleName Cost allocation rule name. The name cannot include spaces or any non alphanumeric characters
     * other than '_' and '-'. The max length is 260 characters.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the {@link Response} on successful completion of {@link Mono}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private Mono<Response<Void>> deleteWithResponseAsync(String billingAccountId, String ruleName) {
        return FluxUtil
            .withContext(context -> service.delete(this.client.getEndpoint(), this.client.getApiVersion(),
                billingAccountId, ruleName, context))
            .contextWrite(context -> context.putAll(FluxUtil.toReactorContext(this.client.getContext()).readOnly()));
    }

    /**
     * Delete cost allocation rule for billing account or enterprise enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param ruleName Cost allocation rule name. The name cannot include spaces or any non alphanumeric characters
     * other than '_' and '-'. The max length is 260 characters.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return A {@link Mono} that completes when a successful response is received.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private Mono<Void> deleteAsync(String billingAccountId, String ruleName) {
        return deleteWithResponseAsync(billingAccountId, ruleName).flatMap(ignored -> Mono.empty());
    }

    /**
     * Delete cost allocation rule for billing account or enterprise enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param ruleName Cost allocation rule name. The name cannot include spaces or any non alphanumeric characters
     * other than '_' and '-'. The max length is 260 characters.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the {@link Response}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<Void> deleteWithResponse(String billingAccountId, String ruleName, Context context) {
        return service.deleteSync(this.client.getEndpoint(), this.client.getApiVersion(), billingAccountId, ruleName,
            context);
    }

    /**
     * Delete cost allocation rule for billing account or enterprise enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param ruleName Cost allocation rule name. The name cannot include spaces or any non alphanumeric characters
     * other than '_' and '-'. The max length is 260 characters.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public void delete(String billingAccountId, String ruleName) {
        deleteWithResponse(billingAccountId, ruleName, Context.NONE);
    }

    /**
     * Get the list of all cost allocation rules for a billing account or enterprise enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the list of all cost allocation rules for a billing account or enterprise enrollment along with
     * {@link PagedResponse} on successful completion of {@link Mono}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private Mono<PagedResponse<CostAllocationRuleDefinitionInner>> listSinglePageAsync(String billingAccountId) {
        final String accept = "application/json";
        return FluxUtil
            .withContext(context -> service.list(this.client.getEndpoint(), this.client.getApiVersion(),
                billingAccountId, accept, context))
            .<PagedResponse<CostAllocationRuleDefinitionInner>>map(res -> new PagedResponseBase<>(res.getRequest(),
                res.getStatusCode(), res.getHeaders(), res.getValue().value(), res.getValue().nextLink(), null))
            .contextWrite(context -> context.putAll(FluxUtil.toReactorContext(this.client.getContext()).readOnly()));
    }

    /**
     * Get the list of all cost allocation rules for a billing account or enterprise enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the list of all cost allocation rules for a billing account or enterprise enrollment as paginated
     * response with {@link PagedFlux}.
     */
    @ServiceMethod(returns = ReturnType.COLLECTION)
    private PagedFlux<CostAllocationRuleDefinitionInner> listAsync(String billingAccountId) {
        return new PagedFlux<>(() -> listSinglePageAsync(billingAccountId),
            nextLink -> listNextSinglePageAsync(nextLink));
    }

    /**
     * Get the list of all cost allocation rules for a billing account or enterprise enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the list of all cost allocation rules for a billing account or enterprise enrollment along with
     * {@link PagedResponse}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private PagedResponse<CostAllocationRuleDefinitionInner> listSinglePage(String billingAccountId) {
        final String accept = "application/json";
        Response<CostAllocationRuleList> res = service.listSync(this.client.getEndpoint(), this.client.getApiVersion(),
            billingAccountId, accept, Context.NONE);
        return new PagedResponseBase<>(res.getRequest(), res.getStatusCode(), res.getHeaders(), res.getValue().value(),
            res.getValue().nextLink(), null);
    }

    /**
     * Get the list of all cost allocation rules for a billing account or enterprise enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the list of all cost allocation rules for a billing account or enterprise enrollment along with
     * {@link PagedResponse}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private PagedResponse<CostAllocationRuleDefinitionInner> listSinglePage(String billingAccountId, Context context) {
        final String accept = "application/json";
        Response<CostAllocationRuleList> res = service.listSync(this.client.getEndpoint(), this.client.getApiVersion(),
            billingAccountId, accept, context);
        return new PagedResponseBase<>(res.getRequest(), res.getStatusCode(), res.getHeaders(), res.getValue().value(),
            res.getValue().nextLink(), null);
    }

    /**
     * Get the list of all cost allocation rules for a billing account or enterprise enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the list of all cost allocation rules for a billing account or enterprise enrollment as paginated
     * response with {@link PagedIterable}.
     */
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<CostAllocationRuleDefinitionInner> list(String billingAccountId) {
        return new PagedIterable<>(() -> listSinglePage(billingAccountId), nextLink -> listNextSinglePage(nextLink));
    }

    /**
     * Get the list of all cost allocation rules for a billing account or enterprise enrollment.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the list of all cost allocation rules for a billing account or enterprise enrollment as paginated
     * response with {@link PagedIterable}.
     */
    @ServiceMethod(returns = ReturnType.COLLECTION)
    public PagedIterable<CostAllocationRuleDefinitionInner> list(String billingAccountId, Context context) {
        return new PagedIterable<>(() -> listSinglePage(billingAccountId, context),
            nextLink -> listNextSinglePage(nextLink, context));
    }

    /**
     * Checks availability and correctness of a name for a cost allocation rule.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param costAllocationRuleCheckNameAvailabilityRequest Cost allocation rule to be created or updated.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the cost allocation rule check name availability response along with {@link Response} on successful
     * completion of {@link Mono}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private Mono<Response<CostAllocationRuleCheckNameAvailabilityResponseInner>> checkNameAvailabilityWithResponseAsync(
        String billingAccountId,
        CostAllocationRuleCheckNameAvailabilityRequest costAllocationRuleCheckNameAvailabilityRequest) {
        final String contentType = "application/json";
        final String accept = "application/json";
        return FluxUtil
            .withContext(
                context -> service.checkNameAvailability(this.client.getEndpoint(), this.client.getApiVersion(),
                    billingAccountId, contentType, accept, costAllocationRuleCheckNameAvailabilityRequest, context))
            .contextWrite(context -> context.putAll(FluxUtil.toReactorContext(this.client.getContext()).readOnly()));
    }

    /**
     * Checks availability and correctness of a name for a cost allocation rule.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param costAllocationRuleCheckNameAvailabilityRequest Cost allocation rule to be created or updated.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the cost allocation rule check name availability response on successful completion of {@link Mono}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private Mono<CostAllocationRuleCheckNameAvailabilityResponseInner> checkNameAvailabilityAsync(
        String billingAccountId,
        CostAllocationRuleCheckNameAvailabilityRequest costAllocationRuleCheckNameAvailabilityRequest) {
        return checkNameAvailabilityWithResponseAsync(billingAccountId, costAllocationRuleCheckNameAvailabilityRequest)
            .flatMap(res -> Mono.justOrEmpty(res.getValue()));
    }

    /**
     * Checks availability and correctness of a name for a cost allocation rule.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param costAllocationRuleCheckNameAvailabilityRequest Cost allocation rule to be created or updated.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the cost allocation rule check name availability response along with {@link Response}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Response<CostAllocationRuleCheckNameAvailabilityResponseInner> checkNameAvailabilityWithResponse(
        String billingAccountId,
        CostAllocationRuleCheckNameAvailabilityRequest costAllocationRuleCheckNameAvailabilityRequest,
        Context context) {
        final String contentType = "application/json";
        final String accept = "application/json";
        return service.checkNameAvailabilitySync(this.client.getEndpoint(), this.client.getApiVersion(),
            billingAccountId, contentType, accept, costAllocationRuleCheckNameAvailabilityRequest, context);
    }

    /**
     * Checks availability and correctness of a name for a cost allocation rule.
     * 
     * @param billingAccountId BillingAccount ID.
     * @param costAllocationRuleCheckNameAvailabilityRequest Cost allocation rule to be created or updated.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the cost allocation rule check name availability response.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    public CostAllocationRuleCheckNameAvailabilityResponseInner checkNameAvailability(String billingAccountId,
        CostAllocationRuleCheckNameAvailabilityRequest costAllocationRuleCheckNameAvailabilityRequest) {
        return checkNameAvailabilityWithResponse(billingAccountId, costAllocationRuleCheckNameAvailabilityRequest,
            Context.NONE).getValue();
    }

    /**
     * Get the next page of items.
     * 
     * @param nextLink The URL to get the next list of items.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the list of all cost allocation rules for a billing account or enterprise enrollment along with
     * {@link PagedResponse} on successful completion of {@link Mono}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private Mono<PagedResponse<CostAllocationRuleDefinitionInner>> listNextSinglePageAsync(String nextLink) {
        final String accept = "application/json";
        return FluxUtil.withContext(context -> service.listNext(nextLink, this.client.getEndpoint(), accept, context))
            .<PagedResponse<CostAllocationRuleDefinitionInner>>map(res -> new PagedResponseBase<>(res.getRequest(),
                res.getStatusCode(), res.getHeaders(), res.getValue().value(), res.getValue().nextLink(), null))
            .contextWrite(context -> context.putAll(FluxUtil.toReactorContext(this.client.getContext()).readOnly()));
    }

    /**
     * Get the next page of items.
     * 
     * @param nextLink The URL to get the next list of items.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the list of all cost allocation rules for a billing account or enterprise enrollment along with
     * {@link PagedResponse}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private PagedResponse<CostAllocationRuleDefinitionInner> listNextSinglePage(String nextLink) {
        final String accept = "application/json";
        Response<CostAllocationRuleList> res
            = service.listNextSync(nextLink, this.client.getEndpoint(), accept, Context.NONE);
        return new PagedResponseBase<>(res.getRequest(), res.getStatusCode(), res.getHeaders(), res.getValue().value(),
            res.getValue().nextLink(), null);
    }

    /**
     * Get the next page of items.
     * 
     * @param nextLink The URL to get the next list of items.
     * @param context The context to associate with this operation.
     * @throws IllegalArgumentException thrown if parameters fail the validation.
     * @throws ManagementException thrown if the request is rejected by server.
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent.
     * @return the list of all cost allocation rules for a billing account or enterprise enrollment along with
     * {@link PagedResponse}.
     */
    @ServiceMethod(returns = ReturnType.SINGLE)
    private PagedResponse<CostAllocationRuleDefinitionInner> listNextSinglePage(String nextLink, Context context) {
        final String accept = "application/json";
        Response<CostAllocationRuleList> res
            = service.listNextSync(nextLink, this.client.getEndpoint(), accept, context);
        return new PagedResponseBase<>(res.getRequest(), res.getStatusCode(), res.getHeaders(), res.getValue().value(),
            res.getValue().nextLink(), null);
    }
}
