versions:
  - version: 2020-09-01
    source: swagger
    swagger-files:
      - ../Microsoft.DeviceUpdate/preview/2020-09-01/deviceupdate.json
  - version: 2021-06-01-preview
    source: swagger
    swagger-files:
      - ../Microsoft.DeviceUpdate/preview/2021-06-01-preview/deviceupdate.json
  - version: 2022-07-01-preview
    source: swagger
    swagger-files:
      - ../Microsoft.DeviceUpdate/preview/2022-07-01-preview/deviceupdate.json
  - version: 2022-10-01
    source: typespec
    swagger-files:
      - ../Microsoft.DeviceUpdate/stable/2022-10-01/deviceupdate.json
  - version: 2023-10-01-preview
    source: swagger
    swagger-files:
      - ../Microsoft.DeviceUpdate/preview/2023-10-01-preview/deviceupdate.json
  - version: 2026-06-01
    source: typespec
    swagger-files:
      - ../Microsoft.DeviceUpdate/stable/2026-06-01/deviceupdate.json
