versions:
  - version: 2022-10-01
    source: typespec
    swagger-files:
      - ../Microsoft.DeviceUpdate/stable/2022-10-01/deviceupdate.json
  - version: 2026-06-01
    source: typespec
    swagger-files:
      - ../Microsoft.DeviceUpdate/stable/2026-06-01/deviceupdate.json
