emit:
  - "@azure-tools/typespec-autorest"

linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"

parameters:
  "service-dir":
    default: "sdk/genome"
  "service-directory-name":
    default: "genome"

options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "resource-manager"
    emitter-output-dir: "{project-root}"
    examples-dir: "{project-root}/examples"
    output-file: "{version-status}/{version}/genome.json"
    arm-types-dir: "{project-root}/../../../../common-types/resource-management"
    omit-unreachable-types: true
    use-read-only-status-schema: true

  "@azure-tools/typespec-csharp":
    flavor: azure
    clear-output-folder: true
    model-namespace: false
    namespace: "Azure.ResourceManager.Genome"
    use-model-reader-writer: true
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"

  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-genome"
    namespace: "com.azure.resourcemanager.genome"
    service-name: "Genome"
    flavor: azure

  "@azure-tools/typespec-ts":
    flavor: azure
    emitter-output-dir: "{output-dir}/{service-dir}/arm-genome"
    package-details:
      name: "@azure/arm-genome"
    experimental-extensible-enums: true

  "@azure-tools/typespec-python":
    flavor: azure
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-genome"
    namespace: "azure.mgmt.genome"
    generate-sample: true
    generate-test: true

  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/genome"
    emitter-output-dir: "{output-dir}/{service-dir}/armgenome"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armgenome"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
