versions:
  - version: 2024-12-01-preview
    source: typespec
    swagger-files:
      - preview/2024-12-01-preview/openapi.json
  - version: 2024-12-30
    source: typespec
    swagger-files:
      - stable/2024-12-30/openapi.json
  - version: 2025-06-01-preview
    source: typespec
    swagger-files:
      - preview/2025-06-01-preview/openapi.json
  - version: 2025-12-01-preview
    source: typespec
    swagger-files:
      - preview/2025-12-01-preview/openapi.json
