versions:
  - version: 2023-05-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ConnectedCache/preview/2023-05-01-preview/ConnectedCache.json
  - version: 2024-11-30-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ConnectedCache/preview/2024-11-30-preview/ConnectedCache.json
