versions:
  - version: 2018-06-17-preview
    source: swagger
    swagger-files:
      - ../preview/2018-06-17-preview/workbookOperations_API.json
  - version: 2020-10-20
    source: swagger
    swagger-files:
      - ../stable/2020-10-20/workbookOperations_API.json
  - version: 2021-03-08
    source: typespec
    swagger-files:
      - ../stable/2021-03-08/workbookOperations_API.json
