versions:
  - version: 2021-06-03-preview
    source: swagger
    swagger-files:
      - preview/2021-06-03-preview/monitoringAccounts_API.json
      - preview/2021-06-03-preview/operations_API.json
  - version: 2023-04-03
    source: swagger
    swagger-files:
      - stable/2023-04-03/monitoringAccounts_API.json
      - stable/2023-04-03/operations_API.json
  - version: 2023-10-01-preview
    source: typespec
    swagger-files:
      - preview/2023-10-01-preview/azuremonitorworkspace.json
  - version: 2025-05-03-preview
    source: typespec
    swagger-files:
      - preview/2025-05-03-preview/azuremonitorworkspace.json
  - version: 2025-10-03
    source: typespec
    swagger-files:
      - stable/2025-10-03/azuremonitorworkspace.json
  - version: 2025-10-03-preview
    source: typespec
    swagger-files:
      - preview/2025-10-03-preview/azuremonitorworkspace.json
