versions:
  - version: 2025-05-03-preview
    source: typespec
    swagger-files:
      - preview/2025-05-03-preview/azuremonitorworkspace.json
  - version: 2025-10-03-preview
    source: typespec
    swagger-files:
      - preview/2025-10-03-preview/azuremonitorworkspace.json
  - version: 2025-10-03
    source: typespec
    swagger-files:
      - stable/2025-10-03/azuremonitorworkspace.json
