// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.costmanagement.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.management.ProxyResource;
import com.azure.core.management.SystemData;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import com.azure.resourcemanager.costmanagement.models.CompressionModeType;
import com.azure.resourcemanager.costmanagement.models.DataOverwriteBehaviorType;
import com.azure.resourcemanager.costmanagement.models.ExportDefinition;
import com.azure.resourcemanager.costmanagement.models.ExportDeliveryInfo;
import com.azure.resourcemanager.costmanagement.models.ExportSchedule;
import com.azure.resourcemanager.costmanagement.models.ExportSuspensionContext;
import com.azure.resourcemanager.costmanagement.models.FormatType;
import com.azure.resourcemanager.costmanagement.models.SystemAssignedServiceIdentity;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * An export resource.
 */
@Fluent
public final class ExportInner extends ProxyResource {
    /*
     * The properties of the export.
     */
    private ExportProperties innerProperties;

    /*
     * The managed identity associated with Export
     */
    private SystemAssignedServiceIdentity identity;

    /*
     * The location of the Export's managed identity. Only required when utilizing managed identity.
     */
    private String location;

    /*
     * eTag of the resource. To handle concurrent update scenario, this field will be used to determine whether the user
     * is updating the latest version or not.
     */
    private String etag;

    /*
     * Azure Resource Manager metadata containing createdBy and modifiedBy information.
     */
    private SystemData systemData;

    /*
     * The type of the resource.
     */
    private String type;

    /*
     * The name of the resource.
     */
    private String name;

    /*
     * Fully qualified resource Id for the resource.
     */
    private String id;

    /**
     * Creates an instance of ExportInner class.
     */
    public ExportInner() {
    }

    /**
     * Get the innerProperties property: The properties of the export.
     * 
     * @return the innerProperties value.
     */
    private ExportProperties innerProperties() {
        return this.innerProperties;
    }

    /**
     * Get the identity property: The managed identity associated with Export.
     * 
     * @return the identity value.
     */
    public SystemAssignedServiceIdentity identity() {
        return this.identity;
    }

    /**
     * Set the identity property: The managed identity associated with Export.
     * 
     * @param identity the identity value to set.
     * @return the ExportInner object itself.
     */
    public ExportInner withIdentity(SystemAssignedServiceIdentity identity) {
        this.identity = identity;
        return this;
    }

    /**
     * Get the location property: The location of the Export's managed identity. Only required when utilizing managed
     * identity.
     * 
     * @return the location value.
     */
    public String location() {
        return this.location;
    }

    /**
     * Set the location property: The location of the Export's managed identity. Only required when utilizing managed
     * identity.
     * 
     * @param location the location value to set.
     * @return the ExportInner object itself.
     */
    public ExportInner withLocation(String location) {
        this.location = location;
        return this;
    }

    /**
     * Get the etag property: eTag of the resource. To handle concurrent update scenario, this field will be used to
     * determine whether the user is updating the latest version or not.
     * 
     * @return the etag value.
     */
    public String etag() {
        return this.etag;
    }

    /**
     * Set the etag property: eTag of the resource. To handle concurrent update scenario, this field will be used to
     * determine whether the user is updating the latest version or not.
     * 
     * @param etag the etag value to set.
     * @return the ExportInner object itself.
     */
    public ExportInner withEtag(String etag) {
        this.etag = etag;
        return this;
    }

    /**
     * Get the systemData property: Azure Resource Manager metadata containing createdBy and modifiedBy information.
     * 
     * @return the systemData value.
     */
    public SystemData systemData() {
        return this.systemData;
    }

    /**
     * Get the type property: The type of the resource.
     * 
     * @return the type value.
     */
    @Override
    public String type() {
        return this.type;
    }

    /**
     * Get the name property: The name of the resource.
     * 
     * @return the name value.
     */
    @Override
    public String name() {
        return this.name;
    }

    /**
     * Get the id property: Fully qualified resource Id for the resource.
     * 
     * @return the id value.
     */
    @Override
    public String id() {
        return this.id;
    }

    /**
     * Get the schedule property: Has schedule information for the export.
     * 
     * @return the schedule value.
     */
    public ExportSchedule schedule() {
        return this.innerProperties() == null ? null : this.innerProperties().schedule();
    }

    /**
     * Set the schedule property: Has schedule information for the export.
     * 
     * @param schedule the schedule value to set.
     * @return the ExportInner object itself.
     */
    public ExportInner withSchedule(ExportSchedule schedule) {
        if (this.innerProperties() == null) {
            this.innerProperties = new ExportProperties();
        }
        this.innerProperties().withSchedule(schedule);
        return this;
    }

    /**
     * Get the format property: The format of the export being delivered.
     * 
     * @return the format value.
     */
    public FormatType format() {
        return this.innerProperties() == null ? null : this.innerProperties().format();
    }

    /**
     * Set the format property: The format of the export being delivered.
     * 
     * @param format the format value to set.
     * @return the ExportInner object itself.
     */
    public ExportInner withFormat(FormatType format) {
        if (this.innerProperties() == null) {
            this.innerProperties = new ExportProperties();
        }
        this.innerProperties().withFormat(format);
        return this;
    }

    /**
     * Get the deliveryInfo property: Has delivery information for the export.
     * 
     * @return the deliveryInfo value.
     */
    public ExportDeliveryInfo deliveryInfo() {
        return this.innerProperties() == null ? null : this.innerProperties().deliveryInfo();
    }

    /**
     * Set the deliveryInfo property: Has delivery information for the export.
     * 
     * @param deliveryInfo the deliveryInfo value to set.
     * @return the ExportInner object itself.
     */
    public ExportInner withDeliveryInfo(ExportDeliveryInfo deliveryInfo) {
        if (this.innerProperties() == null) {
            this.innerProperties = new ExportProperties();
        }
        this.innerProperties().withDeliveryInfo(deliveryInfo);
        return this;
    }

    /**
     * Get the definition property: Has the definition for the export.
     * 
     * @return the definition value.
     */
    public ExportDefinition definition() {
        return this.innerProperties() == null ? null : this.innerProperties().definition();
    }

    /**
     * Set the definition property: Has the definition for the export.
     * 
     * @param definition the definition value to set.
     * @return the ExportInner object itself.
     */
    public ExportInner withDefinition(ExportDefinition definition) {
        if (this.innerProperties() == null) {
            this.innerProperties = new ExportProperties();
        }
        this.innerProperties().withDefinition(definition);
        return this;
    }

    /**
     * Get the runHistory property: If requested, has the most recent run history for the export.
     * 
     * @return the runHistory value.
     */
    public ExportExecutionListResultInner runHistory() {
        return this.innerProperties() == null ? null : this.innerProperties().runHistory();
    }

    /**
     * Set the runHistory property: If requested, has the most recent run history for the export.
     * 
     * @param runHistory the runHistory value to set.
     * @return the ExportInner object itself.
     */
    public ExportInner withRunHistory(ExportExecutionListResultInner runHistory) {
        if (this.innerProperties() == null) {
            this.innerProperties = new ExportProperties();
        }
        this.innerProperties().withRunHistory(runHistory);
        return this;
    }

    /**
     * Get the partitionData property: If set to true, exported data will be partitioned by size and placed in a blob
     * directory together with a manifest file.
     * 
     * @return the partitionData value.
     */
    public Boolean partitionData() {
        return this.innerProperties() == null ? null : this.innerProperties().partitionData();
    }

    /**
     * Set the partitionData property: If set to true, exported data will be partitioned by size and placed in a blob
     * directory together with a manifest file.
     * 
     * @param partitionData the partitionData value to set.
     * @return the ExportInner object itself.
     */
    public ExportInner withPartitionData(Boolean partitionData) {
        if (this.innerProperties() == null) {
            this.innerProperties = new ExportProperties();
        }
        this.innerProperties().withPartitionData(partitionData);
        return this;
    }

    /**
     * Get the dataOverwriteBehavior property: Allow customers to select overwrite data(OverwritePreviousReport) for
     * exports. This setting will enable overwrite data for the same month in customer storage account. By default set
     * to CreateNewReport.
     * 
     * @return the dataOverwriteBehavior value.
     */
    public DataOverwriteBehaviorType dataOverwriteBehavior() {
        return this.innerProperties() == null ? null : this.innerProperties().dataOverwriteBehavior();
    }

    /**
     * Set the dataOverwriteBehavior property: Allow customers to select overwrite data(OverwritePreviousReport) for
     * exports. This setting will enable overwrite data for the same month in customer storage account. By default set
     * to CreateNewReport.
     * 
     * @param dataOverwriteBehavior the dataOverwriteBehavior value to set.
     * @return the ExportInner object itself.
     */
    public ExportInner withDataOverwriteBehavior(DataOverwriteBehaviorType dataOverwriteBehavior) {
        if (this.innerProperties() == null) {
            this.innerProperties = new ExportProperties();
        }
        this.innerProperties().withDataOverwriteBehavior(dataOverwriteBehavior);
        return this;
    }

    /**
     * Get the compressionMode property: Allow customers to select compress data for exports. This setting will enable
     * destination file compression scheme at runtime. By default set to None. Gzip is for csv and snappy for parquet.
     * 
     * @return the compressionMode value.
     */
    public CompressionModeType compressionMode() {
        return this.innerProperties() == null ? null : this.innerProperties().compressionMode();
    }

    /**
     * Set the compressionMode property: Allow customers to select compress data for exports. This setting will enable
     * destination file compression scheme at runtime. By default set to None. Gzip is for csv and snappy for parquet.
     * 
     * @param compressionMode the compressionMode value to set.
     * @return the ExportInner object itself.
     */
    public ExportInner withCompressionMode(CompressionModeType compressionMode) {
        if (this.innerProperties() == null) {
            this.innerProperties = new ExportProperties();
        }
        this.innerProperties().withCompressionMode(compressionMode);
        return this;
    }

    /**
     * Get the exportDescription property: The export description set by customer at time of export creation/update.
     * 
     * @return the exportDescription value.
     */
    public String exportDescription() {
        return this.innerProperties() == null ? null : this.innerProperties().exportDescription();
    }

    /**
     * Set the exportDescription property: The export description set by customer at time of export creation/update.
     * 
     * @param exportDescription the exportDescription value to set.
     * @return the ExportInner object itself.
     */
    public ExportInner withExportDescription(String exportDescription) {
        if (this.innerProperties() == null) {
            this.innerProperties = new ExportProperties();
        }
        this.innerProperties().withExportDescription(exportDescription);
        return this;
    }

    /**
     * Get the nextRunTimeEstimate property: If the export has an active schedule, provides an estimate of the next run
     * time.
     * 
     * @return the nextRunTimeEstimate value.
     */
    public OffsetDateTime nextRunTimeEstimate() {
        return this.innerProperties() == null ? null : this.innerProperties().nextRunTimeEstimate();
    }

    /**
     * Get the systemSuspensionContext property: The export suspension reason if export is in SystemSuspended state.
     * This is not populated currently.
     * 
     * @return the systemSuspensionContext value.
     */
    public ExportSuspensionContext systemSuspensionContext() {
        return this.innerProperties() == null ? null : this.innerProperties().systemSuspensionContext();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeJsonField("properties", this.innerProperties);
        jsonWriter.writeJsonField("identity", this.identity);
        jsonWriter.writeStringField("location", this.location);
        jsonWriter.writeStringField("eTag", this.etag);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of ExportInner from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of ExportInner if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the ExportInner.
     */
    public static ExportInner fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            ExportInner deserializedExportInner = new ExportInner();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("id".equals(fieldName)) {
                    deserializedExportInner.id = reader.getString();
                } else if ("name".equals(fieldName)) {
                    deserializedExportInner.name = reader.getString();
                } else if ("type".equals(fieldName)) {
                    deserializedExportInner.type = reader.getString();
                } else if ("properties".equals(fieldName)) {
                    deserializedExportInner.innerProperties = ExportProperties.fromJson(reader);
                } else if ("identity".equals(fieldName)) {
                    deserializedExportInner.identity = SystemAssignedServiceIdentity.fromJson(reader);
                } else if ("location".equals(fieldName)) {
                    deserializedExportInner.location = reader.getString();
                } else if ("eTag".equals(fieldName)) {
                    deserializedExportInner.etag = reader.getString();
                } else if ("systemData".equals(fieldName)) {
                    deserializedExportInner.systemData = SystemData.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedExportInner;
        });
    }
}
