versions:
  - version: 2025-05-25
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.HealthBot/stable/2025-05-25/healthbot.json
  - version: 2025-11-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.HealthBot/stable/2025-11-01/healthbot.json
