versions:
  - version: 2025-11-01-preview
    source: typespec
    swagger-files:
      - preview/2025-11-01-preview/search.json
  - version: 2026-04-01
    source: typespec
    swagger-files:
      - stable/2026-04-01/search.json
  - version: 2026-05-01-preview
    source: typespec
    swagger-files:
      - preview/2026-05-01-preview/search.json
