versions:
  - version: 2021-09-15-preview
    source: swagger
    swagger-files:
      - preview/2021-09-15-preview/capabilities.json
      - preview/2021-09-15-preview/capabilityTypes.json
      - preview/2021-09-15-preview/experiments.json
      - preview/2021-09-15-preview/operations.json
      - preview/2021-09-15-preview/targetTypes.json
      - preview/2021-09-15-preview/targets.json
  - version: 2022-07-01-preview
    source: swagger
    swagger-files:
      - preview/2022-07-01-preview/capabilities.json
      - preview/2022-07-01-preview/capabilityTypes.json
      - preview/2022-07-01-preview/experiments.json
      - preview/2022-07-01-preview/operations.json
      - preview/2022-07-01-preview/targetTypes.json
      - preview/2022-07-01-preview/targets.json
  - version: 2022-10-01-preview
    source: swagger
    swagger-files:
      - preview/2022-10-01-preview/capabilities.json
      - preview/2022-10-01-preview/capabilityTypes.json
      - preview/2022-10-01-preview/experiments.json
      - preview/2022-10-01-preview/operations.json
      - preview/2022-10-01-preview/targetTypes.json
      - preview/2022-10-01-preview/targets.json
  - version: 2023-04-01-preview
    source: swagger
    swagger-files:
      - preview/2023-04-01-preview/capabilities.json
      - preview/2023-04-01-preview/capabilityTypes.json
      - preview/2023-04-01-preview/experiments.json
      - preview/2023-04-01-preview/operations.json
      - preview/2023-04-01-preview/targetTypes.json
      - preview/2023-04-01-preview/targets.json
  - version: 2023-04-15-preview
    source: swagger
    swagger-files:
      - preview/2023-04-15-preview/capabilities.json
      - preview/2023-04-15-preview/capabilityTypes.json
      - preview/2023-04-15-preview/experiments.json
      - preview/2023-04-15-preview/operations.json
      - preview/2023-04-15-preview/targetTypes.json
      - preview/2023-04-15-preview/targets.json
  - version: 2023-09-01-preview
    source: swagger
    swagger-files:
      - preview/2023-09-01-preview/capabilities.json
      - preview/2023-09-01-preview/capabilityTypes.json
      - preview/2023-09-01-preview/experiments.json
      - preview/2023-09-01-preview/operationStatuses.json
      - preview/2023-09-01-preview/operations.json
      - preview/2023-09-01-preview/targetTypes.json
      - preview/2023-09-01-preview/targets.json
  - version: 2023-10-27-preview
    source: swagger
    swagger-files:
      - preview/2023-10-27-preview/capabilities.json
      - preview/2023-10-27-preview/capabilityTypes.json
      - preview/2023-10-27-preview/experiments.json
      - preview/2023-10-27-preview/operationStatuses.json
      - preview/2023-10-27-preview/operations.json
      - preview/2023-10-27-preview/privateAccesses.json
      - preview/2023-10-27-preview/targetTypes.json
      - preview/2023-10-27-preview/targets.json
  - version: 2023-11-01
    source: swagger
    swagger-files:
      - stable/2023-11-01/capabilities.json
      - stable/2023-11-01/capabilityTypes.json
      - stable/2023-11-01/experiments.json
      - stable/2023-11-01/operationStatuses.json
      - stable/2023-11-01/operations.json
      - stable/2023-11-01/targetTypes.json
      - stable/2023-11-01/targets.json
  - version: 2024-01-01
    source: swagger
    swagger-files:
      - stable/2024-01-01/capabilities.json
      - stable/2024-01-01/capabilityTypes.json
      - stable/2024-01-01/experiments.json
      - stable/2024-01-01/operationStatuses.json
      - stable/2024-01-01/operations.json
      - stable/2024-01-01/targetTypes.json
      - stable/2024-01-01/targets.json
  - version: 2024-03-22-preview
    source: swagger
    swagger-files:
      - preview/2024-03-22-preview/capabilities.json
      - preview/2024-03-22-preview/capabilityTypes.json
      - preview/2024-03-22-preview/experiments.json
      - preview/2024-03-22-preview/operationStatuses.json
      - preview/2024-03-22-preview/operations.json
      - preview/2024-03-22-preview/privateAccesses.json
      - preview/2024-03-22-preview/targetTypes.json
      - preview/2024-03-22-preview/targets.json
  - version: 2025-01-01
    source: typespec
    swagger-files:
      - stable/2025-01-01/openapi.json
  - version: 2026-05-01-preview
    source: typespec
    swagger-files:
      - preview/2026-05-01-preview/openapi.json
