versions:
  - version: 2021-10-01
    source: swagger
    swagger-files:
      - stable/2021-10-01/questionanswering.json
  - version: 2023-04-01
    source: typespec
    swagger-files:
      - stable/2023-04-01/questionanswering.json
  - version: 2023-11-15-preview
    source: swagger
    swagger-files:
      - preview/2023-11-15-preview/questionanswering.json
  - version: 2025-05-15-preview
    source: typespec
    swagger-files:
      - preview/2025-05-15-preview/questionanswering.json
