versions:
  - version: 2024-11-01
    source: swagger
    swagger-files:
      - stable/2024-11-01/fluxconfiguration.json
  - version: 2025-04-01
    source: typespec
    swagger-files:
      - stable/2025-04-01/fluxconfiguration.json
