versions:
  - version: 2025-10-01
    source: typespec
    swagger-files:
      - stable/2025-10-01/VoiceLive.json
  - version: 2026-01-01-preview
    source: typespec
    swagger-files:
      - preview/2026-01-01-preview/VoiceLive.json
  - version: 2026-04-10
    source: typespec
    swagger-files:
      - stable/2026-04-10/VoiceLive.json
  - version: 2026-06-01-preview
    source: typespec
    swagger-files:
      - preview/2026-06-01-preview/VoiceLive.json
  - version: 2026-07-15
    source: typespec
    swagger-files:
      - stable/2026-07-15/VoiceLive.json
