versions:
  - version: 2023-10-31-preview
    source: typespec
    swagger-files:
      - ../data-plane/DocumentIntelligence/preview/2023-10-31-preview/DocumentIntelligence.json
  - version: 2024-02-29-preview
    source: typespec
    swagger-files:
      - ../data-plane/DocumentIntelligence/preview/2024-02-29-preview/DocumentIntelligence.json
  - version: 2024-07-31-preview
    source: typespec
    swagger-files:
      - ../data-plane/DocumentIntelligence/preview/2024-07-31-preview/DocumentIntelligence.json
  - version: 2024-11-30
    source: typespec
    swagger-files:
      - ../data-plane/DocumentIntelligence/stable/2024-11-30/DocumentIntelligence.json
