versions:
  - version: 2017-09-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Solutions/stable/2017-09-01/managedapplications.json
  - version: 2017-12-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Solutions/stable/2017-12-01/managedapplications.json
  - version: 2018-02-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Solutions/stable/2018-02-01/managedapplications.json
  - version: 2018-03-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Solutions/stable/2018-03-01/managedapplications.json
  - version: 2018-06-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Solutions/stable/2018-06-01/managedapplications.json
  - version: 2018-09-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Solutions/preview/2018-09-01-preview/managedapplications.json
  - version: 2019-07-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Solutions/stable/2019-07-01/managedapplications.json
  - version: 2020-08-21-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Solutions/preview/2020-08-21-preview/managedapplications.json
  - version: 2021-02-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Solutions/preview/2021-02-01-preview/managedapplications.json
  - version: 2021-07-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Solutions/stable/2021-07-01/managedapplications.json
  - version: 2023-12-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Solutions/preview/2023-12-01-preview/managedapplications.json
