versions:
  - version: 2019-05-01-preview
    source: swagger
    swagger-files:
      - preview/2019-05-01-preview/support.json
  - version: 2020-04-01
    source: swagger
    swagger-files:
      - stable/2020-04-01/support.json
  - version: 2021-06-01-preview
    source: swagger
    swagger-files:
      - preview/2021-06-01-preview/supportResourceIdDetails.json
  - version: 2022-09-01-preview
    source: swagger
    swagger-files:
      - preview/2022-09-01-preview/support.json
  - version: 2023-06-01-preview
    source: swagger
    swagger-files:
      - preview/2023-06-01-preview/support.json
  - version: 2024-04-01
    source: typespec
    swagger-files:
      - stable/2024-04-01/support.json
  - version: 2026-06-01
    source: typespec
    swagger-files:
      - stable/2026-06-01/support.json
  - version: 2026-07-01
    source: typespec
    swagger-files:
      - stable/2026-07-01/support.json
