versions:
  - version: 2024-02-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Edge/sites/preview/2024-02-01-preview/sites.json
  - version: 2025-03-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Edge/sites/preview/2025-03-01-preview/sites.json
  - version: 2025-06-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Edge/sites/stable/2025-06-01/sites.json
