versions:
  - version: 2020-03-01
    source: swagger
    swagger-files:
      - stable/2020-03-01/confluent.json
  - version: 2020-03-01-preview
    source: swagger
    swagger-files:
      - preview/2020-03-01-preview/confluent.json
  - version: 2021-03-01-preview
    source: swagger
    swagger-files:
      - preview/2021-03-01-preview/confluent.json
  - version: 2021-09-01-preview
    source: swagger
    swagger-files:
      - preview/2021-09-01-preview/confluent.json
  - version: 2021-12-01
    source: swagger
    swagger-files:
      - stable/2021-12-01/confluent.json
  - version: 2023-08-22
    source: swagger
    swagger-files:
      - stable/2023-08-22/confluent.json
  - version: 2024-02-13
    source: swagger
    swagger-files:
      - stable/2024-02-13/confluent.json
  - version: 2024-07-01
    source: typespec
    swagger-files:
      - stable/2024-07-01/confluent.json
  - version: 2025-07-17-preview
    source: typespec
    swagger-files:
      - preview/2025-07-17-preview/confluent.json
  - version: 2025-08-18-preview
    source: typespec
    swagger-files:
      - preview/2025-08-18-preview/confluent.json
  - version: 2026-05-01-preview
    source: typespec
    swagger-files:
      - preview/2026-05-01-preview/confluent.json
  - version: 2026-06-02-preview
    source: typespec
    swagger-files:
      - preview/2026-06-02-preview/confluent.json
