# Known renamed mappings between hand-authored and TSP-compiled swaggers
# Extracted from human review CSV analysis
KNOWN_DEFINITION_RENAMES = {
    "AmlSkill": "AzureMachineLearningSkill",
    "AnswerResult": "QueryAnswerResult",
    "Answers": "QueryAnswerType",
    "AzureOpenAIParameters": "AzureOpenAIVectorizerParameters",
    "BinaryQuantizationVectorSearchCompressionConfiguration": "BinaryQuantizationCompression",
    "BM25Similarity": "BM25SimilarityAlgorithm",
    "CaptionResult": "QueryCaptionResult",
    "Captions": "QueryCaptionType",
    "ClassicSimilarity": "ClassicSimilarityAlgorithm",
    "DataToExtract": "BlobIndexerDataToExtract",
    "ExecutionEnvironment": "IndexerExecutionEnvironment",
    "ExhaustiveKnnVectorSearchAlgorithmConfiguration": "ExhaustiveKnnAlgorithmConfiguration",
    "HnswVectorSearchAlgorithmConfiguration": "HnswAlgorithmConfiguration",
    "ImageAction": "BlobIndexerImageAction",
    "ParsingMode": "BlobIndexerParsingMode",
    "PdfTextRotationAlgorithm": "BlobIndexerPDFTextRotationAlgorithm",
    "QueryResultDocumentSemanticFieldState": "SemanticFieldState",
    "RawVectorQuery": "VectorizedQuery",
    "ScalarQuantizationVectorSearchCompressionConfiguration": "ScalarQuantizationCompression",
    "SemanticErrorHandling": "SemanticErrorMode",
    "SemanticPartialResponseReason": "SemanticErrorReason",
    "SemanticPartialResponseType": "SemanticSearchResultsType",
    "SemanticSettings": "SemanticSearch",
    "ServiceStatistics": "SearchServiceStatistics",
    "Similarity": "SimilarityAlgorithm",
    "Speller": "QuerySpellerType",
    "Suggester": "SearchSuggester",
    "VectorSearchCompressionConfiguration": "VectorSearchCompression",
    "WebApiParameters": "WebApiVectorizerParameters",
    "EncoderModelName": "SplitSkillEncoderModelName",
    "OcrSkillLineEnding": "OcrLineEnding",
    "PrioritizedFields": "SemanticPrioritizedFields",
}
