versions:
  - version: 2025-12-24-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Napster.CompanionAPI/preview/2025-12-24-preview/openapi.json
  - version: 2026-08-11
    source: typespec
    swagger-files:
      - ../resource-manager/Napster.CompanionAPI/stable/2026-08-11/openapi.json
