versions:
  - version: 2020-10-20
    source: swagger
    swagger-files:
      - stable/2020-10-20/healthbot.json
  - version: 2020-10-20-preview
    source: swagger
    swagger-files:
      - preview/2020-10-20-preview/healthbot.json
  - version: 2020-12-08
    source: swagger
    swagger-files:
      - stable/2020-12-08/healthbot.json
  - version: 2020-12-08-preview
    source: swagger
    swagger-files:
      - preview/2020-12-08-preview/healthbot.json
  - version: 2021-06-10
    source: swagger
    swagger-files:
      - stable/2021-06-10/healthbot.json
  - version: 2021-08-24
    source: swagger
    swagger-files:
      - stable/2021-08-24/healthbot.json
  - version: 2022-08-08
    source: swagger
    swagger-files:
      - stable/2022-08-08/healthbot.json
  - version: 2023-05-01
    source: swagger
    swagger-files:
      - stable/2023-05-01/healthbot.json
  - version: 2024-02-01
    source: swagger
    swagger-files:
      - stable/2024-02-01/healthbot.json
  - version: 2025-05-25
    source: typespec
    swagger-files:
      - stable/2025-05-25/healthbot.json
  - version: 2025-11-01
    source: typespec
    swagger-files:
      - stable/2025-11-01/healthbot.json
