// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package armplaywrighttesting

import "time"

// Account - A Playwright service account resource.
type Account struct {
	// REQUIRED; Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
	ID *string

	// REQUIRED; The geo-location where the resource lives
	Location *string

	// REQUIRED; The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string

	// The resource-specific properties for this resource.
	Properties *AccountProperties

	// Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SystemData

	// Resource tags.
	Tags map[string]*string

	// READ-ONLY; Name of account.
	Name *string
}

// AccountFreeTrialProperties - The Playwright service account quota resource free-trial properties.
type AccountFreeTrialProperties struct {
	// REQUIRED; The free-trial allocated limit value eg. allocated free minutes.
	AllocatedValue *int32

	// REQUIRED; The free-trial createdAt utcDateTime.
	CreatedAt *time.Time

	// REQUIRED; The free-trial expiryAt utcDateTime.
	ExpiryAt *time.Time

	// REQUIRED; The free-trial percentage used.
	PercentageUsed *float32

	// REQUIRED; The free-trial used value eg. used free minutes.
	UsedValue *int32
}

// AccountListResult - The response of a Account list operation.
type AccountListResult struct {
	// REQUIRED; The Account items on this page
	Value []*Account

	// The link to the next page of items
	NextLink *string
}

// AccountProperties - Account resource properties.
type AccountProperties struct {
	// The Playwright testing dashboard URI for the account resource.
	DashboardURI *string

	// The status of the last operation.
	ProvisioningState *ProvisioningState

	// This property sets the connection region for Playwright client workers to cloud-hosted browsers. If enabled, workers connect
	// to browsers in the closest Azure region, ensuring lower latency. If disabled, workers connect to browsers in the Azure
	// region in which the workspace was initially created.
	RegionalAffinity *EnablementStatus

	// When enabled, this feature allows the workspace to upload and display test results, including artifacts like traces and
	// screenshots, in the Playwright portal. This enables faster and more efficient troubleshooting.
	Reporting *EnablementStatus

	// When enabled, Playwright client workers can connect to cloud-hosted browsers. This can increase the number of parallel
	// workers for a test run, significantly minimizing test completion durations.
	ScalableExecution *EnablementStatus
}

// AccountQuota - A quota resource for a Playwright service account.
type AccountQuota struct {
	// REQUIRED; Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
	ID *string

	// REQUIRED; The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string

	// The resource-specific properties for this resource.
	Properties *AccountQuotaProperties

	// Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SystemData

	// READ-ONLY; The Playwright service account quota name.
	Name *QuotaNames
}

// AccountQuotaListResult - The response of a AccountQuota list operation.
type AccountQuotaListResult struct {
	// REQUIRED; The AccountQuota items on this page
	Value []*AccountQuota

	// The link to the next page of items
	NextLink *string
}

// AccountQuotaProperties - The Playwright service account quota resource properties.
type AccountQuotaProperties struct {
	// The Playwright service account quota resource free-trial properties.
	FreeTrial *AccountFreeTrialProperties

	// The status of the last operation.
	ProvisioningState *ProvisioningState
}

// AccountUpdate - The type used for update operations of the Account.
type AccountUpdate struct {
	Properties *AccountUpdateProperties

	// Resource tags.
	Tags map[string]*string
}

// AccountUpdateProperties - The updatable properties of the Account.
type AccountUpdateProperties struct {
	// This property sets the connection region for Playwright client workers to cloud-hosted browsers. If enabled, workers connect
	// to browsers in the closest Azure region, ensuring lower latency. If disabled, workers connect to browsers in the Azure
	// region in which the workspace was initially created.
	RegionalAffinity *EnablementStatus

	// When enabled, this feature allows the workspace to upload and display test results, including artifacts like traces and
	// screenshots, in the Playwright portal. This enables faster and more efficient troubleshooting.
	Reporting *EnablementStatus

	// When enabled, Playwright client workers can connect to cloud-hosted browsers. This can increase the number of parallel
	// workers for a test run, significantly minimizing test completion durations.
	ScalableExecution *EnablementStatus
}

// ArmResource - Common properties for all Azure Resource Manager resources.
type ArmResource struct {
	// REQUIRED; Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
	ID *string

	// REQUIRED; The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string

	// Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SystemData
}

// ArmResourceBase - Base class used for type definitions
type ArmResourceBase struct {
}

// CheckNameAvailabilityRequest - The check availability request body.
type CheckNameAvailabilityRequest struct {
	// The name of the resource for which availability needs to be checked.
	Name *string

	// The resource type.
	Type *string
}

// CheckNameAvailabilityResponse - The check availability result.
type CheckNameAvailabilityResponse struct {
	// Detailed reason why the given name is not available.
	Message *string

	// Indicates if the resource name is available.
	NameAvailable *bool

	// The reason why the given name is not available.
	Reason *CheckNameAvailabilityReason
}

// FreeTrialProperties - The subscription quota resource free-trial properties.
type FreeTrialProperties struct {
	// REQUIRED; The Playwright service account id.
	AccountID *string

	// REQUIRED; The free-trial state.
	State *FreeTrialState
}

// Operation - Details of a REST API operation, returned from the Resource Provider Operations API
type Operation struct {
	// Enum. Indicates the action type. "Internal" refers to actions that are for internal only APIs.
	ActionType *ActionType

	// Localized display information for this particular operation.
	Display *OperationDisplay

	// Whether the operation applies to data-plane. This is "true" for data-plane operations and "false" for Azure Resource Manager/control-plane
	// operations.
	IsDataAction *bool

	// The name of the operation, as per Resource-Based Access Control (RBAC). Examples: "Microsoft.Compute/virtualMachines/write",
	// "Microsoft.Compute/virtualMachines/capture/action"
	Name *string

	// The intended executor of the operation; as in Resource Based Access Control (RBAC) and audit logs UX. Default value is
	// "user,system"
	Origin *Origin
}

// OperationDisplay - Localized display information for and operation.
type OperationDisplay struct {
	// The short, localized friendly description of the operation; suitable for tool tips and detailed views.
	Description *string

	// The concise, localized friendly name for the operation; suitable for dropdowns. E.g. "Create or Update Virtual Machine",
	// "Restart Virtual Machine".
	Operation *string

	// The localized friendly form of the resource provider name, e.g. "Microsoft Monitoring Insights" or "Microsoft Compute".
	Provider *string

	// The localized friendly name of the resource type related to this operation. E.g. "Virtual Machines" or "Job Schedule Collections".
	Resource *string
}

// PagedOperation - A list of REST API operations supported by an Azure Resource Provider. It contains an URL link to get
// the next set of results.
type PagedOperation struct {
	// REQUIRED; The Operation items on this page
	Value []*Operation

	// The link to the next page of items
	NextLink *string
}

// ProxyResourceBase - The base proxy resource.
type ProxyResourceBase struct {
	// REQUIRED; Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
	ID *string

	// REQUIRED; The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string

	// Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SystemData
}

// Quota - A subscription quota resource.
type Quota struct {
	// REQUIRED; Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
	ID *string

	// REQUIRED; The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string

	// The resource-specific properties for this resource.
	Properties *QuotaProperties

	// Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SystemData

	// READ-ONLY; The quota name.
	Name *QuotaNames
}

// QuotaListResult - The response of a Quota list operation.
type QuotaListResult struct {
	// REQUIRED; The Quota items on this page
	Value []*Quota

	// The link to the next page of items
	NextLink *string
}

// QuotaProperties - The subscription quota resource properties.
type QuotaProperties struct {
	// The subscription quota resource free-trial properties.
	FreeTrial *FreeTrialProperties

	// The status of the last operation.
	ProvisioningState *ProvisioningState
}

// SystemData - Metadata pertaining to creation and last modification of the resource.
type SystemData struct {
	// The type of identity that created the resource.
	CreatedAt *time.Time

	// The identity that created the resource.
	CreatedBy *string

	// The type of identity that created the resource.
	CreatedByType *CreatedByType

	// The timestamp of resource last modification (UTC)
	LastModifiedAt *time.Time

	// The identity that last modified the resource.
	LastModifiedBy *string

	// The type of identity that last modified the resource.
	LastModifiedByType *CreatedByType
}

// TrackedResourceBase - The resource model definition for an Azure Resource Manager tracked top level resource
type TrackedResourceBase struct {
	// REQUIRED; Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
	ID *string

	// REQUIRED; The geo-location where the resource lives
	Location *string

	// REQUIRED; The type of the resource. E.g. "Microsoft.Compute/virtualMachines" or "Microsoft.Storage/storageAccounts"
	Type *string

	// Azure Resource Manager metadata containing createdBy and modifiedBy information.
	SystemData *SystemData

	// Resource tags.
	Tags map[string]*string
}
