versions:
  - version: 2025-06-10-preview
    source: typespec
    swagger-files:
      - preview/2025-06-10-preview/openapi.json
  - version: 2026-02-23
    source: typespec
    swagger-files:
      - stable/2026-02-23/openapi.json
  - version: 2026-05-22-preview
    source: typespec
    swagger-files:
      - preview/2026-05-22-preview/openapi.json
