versions:
  - version: 2026-04-06-preview
    source: typespec
    swagger-files:
      - preview/2026-04-06-preview/Bulkactions.json
  - version: 2026-06-06
    source: typespec
    swagger-files:
      - stable/2026-06-06/Bulkactions.json
  - version: 2026-07-06-preview
    source: typespec
    swagger-files:
      - preview/2026-07-06-preview/Bulkactions.json
