versions:
  - version: 2025-07-28-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ManagedOps/preview/2025-07-28-preview/managedops.json
  - version: 2026-01-06-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ManagedOps/preview/2026-01-06-preview/managedops.json
