versions:
  - version: 2015-03-01-preview
    source: swagger
    swagger-files:
      - preview/2015-03-01-preview/applications.json
      - preview/2015-03-01-preview/cluster.json
      - preview/2015-03-01-preview/configurations.json
      - preview/2015-03-01-preview/extensions.json
      - preview/2015-03-01-preview/locations.json
      - preview/2015-03-01-preview/operations.json
      - preview/2015-03-01-preview/scriptActions.json
      - preview/2015-03-01-preview/virtualMachines.json
  - version: 2018-06-01-preview
    source: swagger
    swagger-files:
      - stable/2018-06-01-preview/applications.json
      - stable/2018-06-01-preview/cluster.json
      - stable/2018-06-01-preview/configurations.json
      - stable/2018-06-01-preview/extensions.json
      - stable/2018-06-01-preview/locations.json
      - stable/2018-06-01-preview/operations.json
      - stable/2018-06-01-preview/scriptActions.json
      - stable/2018-06-01-preview/virtualMachines.json
  - version: 2021-06-01
    source: swagger
    swagger-files:
      - stable/2021-06-01/applications.json
      - stable/2021-06-01/cluster.json
      - stable/2021-06-01/configurations.json
      - stable/2021-06-01/extensions.json
      - stable/2021-06-01/locations.json
      - stable/2021-06-01/operations.json
      - stable/2021-06-01/privateEndpointConnections.json
      - stable/2021-06-01/privateLinkResources.json
      - stable/2021-06-01/scriptActions.json
      - stable/2021-06-01/virtualMachines.json
  - version: 2023-04-15-preview
    source: swagger
    swagger-files:
      - preview/2023-04-15-preview/applications.json
      - preview/2023-04-15-preview/cluster.json
      - preview/2023-04-15-preview/configurations.json
      - preview/2023-04-15-preview/extensions.json
      - preview/2023-04-15-preview/locations.json
      - preview/2023-04-15-preview/operations.json
      - preview/2023-04-15-preview/privateEndpointConnections.json
      - preview/2023-04-15-preview/privateLinkResources.json
      - preview/2023-04-15-preview/scriptActions.json
      - preview/2023-04-15-preview/virtualMachines.json
  - version: 2023-08-15-preview
    source: swagger
    swagger-files:
      - preview/2023-08-15-preview/applications.json
      - preview/2023-08-15-preview/cluster.json
      - preview/2023-08-15-preview/configurations.json
      - preview/2023-08-15-preview/extensions.json
      - preview/2023-08-15-preview/locations.json
      - preview/2023-08-15-preview/operations.json
      - preview/2023-08-15-preview/privateEndpointConnections.json
      - preview/2023-08-15-preview/privateLinkResources.json
      - preview/2023-08-15-preview/scriptActions.json
      - preview/2023-08-15-preview/virtualMachines.json
  - version: 2024-08-01-preview
    source: swagger
    swagger-files:
      - preview/2024-08-01-preview/applications.json
      - preview/2024-08-01-preview/cluster.json
      - preview/2024-08-01-preview/configurations.json
      - preview/2024-08-01-preview/extensions.json
      - preview/2024-08-01-preview/locations.json
      - preview/2024-08-01-preview/operations.json
      - preview/2024-08-01-preview/privateEndpointConnections.json
      - preview/2024-08-01-preview/privateLinkResources.json
      - preview/2024-08-01-preview/scriptActions.json
      - preview/2024-08-01-preview/virtualMachines.json
  - version: 2025-01-15-preview
    source: typespec
    swagger-files:
      - preview/2025-01-15-preview/openapi.json
