versions:
  - version: 2023-10-30-preview
    source: typespec
    swagger-files:
      - preview/2023-10-30-preview/devopsinfrastructure.json
  - version: 2023-12-13-preview
    source: typespec
    swagger-files:
      - preview/2023-12-13-preview/devopsinfrastructure.json
  - version: 2024-03-26-preview
    source: typespec
    swagger-files:
      - preview/2024-03-26-preview/devopsinfrastructure.json
  - version: 2024-04-04-preview
    source: typespec
    swagger-files:
      - preview/2024-04-04-preview/devopsinfrastructure.json
  - version: 2024-10-19
    source: typespec
    swagger-files:
      - stable/2024-10-19/devopsinfrastructure.json
  - version: 2025-01-21
    source: typespec
    swagger-files:
      - stable/2025-01-21/devopsinfrastructure.json
  - version: 2025-09-20
    source: typespec
    swagger-files:
      - stable/2025-09-20/devopsinfrastructure.json
  - version: 2026-04-17-preview
    source: typespec
    swagger-files:
      - preview/2026-04-17-preview/devopsinfrastructure.json
  - version: 2026-06-02
    source: typespec
    swagger-files:
      - stable/2026-06-02/devopsinfrastructure.json
