versions:
  - version: 2024-03-01-preview
    source: typespec
    swagger-files:
      - ../preview/2024-03-01-preview/metricAlert.json
  - version: 2026-01-01
    source: typespec
    swagger-files:
      - ../stable/2026-01-01/metricAlert.json
