name: Install dependencies for github-script actions
description: Installs dependencies for github-script actions

runs:
  using: composite

  steps:
    - uses: ./.github/actions/setup-node-install-deps
      with:
        # Use default Node version from runner cache for better performance
        # See: https://github.com/actions/setup-node/issues/1492
        node-version: ""
        # "--no-audit": improves performance
        # "--omit dev": not needed at runtime, improves performance
        install-command: "npm ci --no-audit --omit dev"
        working-directory: ./.github
