import eslint from "@eslint/js";
import { defineConfig } from "eslint/config";
import globals from "globals";
import tseslint from "typescript-eslint";

export function defineBaseConfig(options: {
  projectService?: boolean | object;
  tsconfigRootDir: string;
}): import("eslint").Linter.Config[] {
  const { projectService = true, tsconfigRootDir } = options;

  return defineConfig(
    eslint.configs.recommended,
    tseslint.configs.recommendedTypeChecked,
    {
      languageOptions: {
        // we only run in node, not browser
        globals: globals.node,
        // required to use tseslint.configs.recommendedTypeChecked
        parserOptions: {
          // Defaults to "true", which is the minimum required to use tseslint.configs.recommendedTypeChecked
          // Can be overridden by caller, by setting to a config object
          projectService,
          // Must be set by caller, since this should point to the root directory of the project being analyzed
          tsconfigRootDir,
        },
      },
    },
    {
      ignores: [
        // generated by `vitest --coverage`
        "coverage/**",
      ],
    },
  );
}
