{
  versions:
    [
      {
          version: 2025-01-31-preview,
          source: typespec,
          swagger-files: [ preview/2025-01-31-preview/openapi.json ]
        },
      {
          version: 2025-10-31-preview,
          source: typespec,
          swagger-files: [ preview/2025-10-31-preview/openapi.json ]
        },
      {
          version: 2026-03-31-preview,
          source: typespec,
          swagger-files: [ preview/2026-03-31-preview/openapi.json ]
        },
      {
          version: 2026-04-30-preview,
          source: typespec,
          swagger-files: [ preview/2026-04-30-preview/openapi.json ]
        }
    ]
}
