emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    omit-unreachable-types: true
    emitter-output-dir: "{project-root}"
    output-file: "{version-status}/{version}/openapi.json"
    arm-types-dir: "{project-root}/../../../../common-types/resource-management"
    examples-dir: "{project-root}/examples"
  "@azure-tools/typespec-csharp":
    flavor: azure
    emitter-output-dir: "{output-dir}/{service-dir}/Azure.ResourceManager.CleanRoom"
    clear-output-folder: true
    model-namespace: false
    namespace: "Azure.ResourceManager.CleanRoom"
  "@azure-tools/typespec-go":
    service-dir: sdk/resourcemanager/cleanroom
    emitter-output-dir: "{output-dir}/{service-dir}/armcleanroom"
    module: github.com/Azure/azure-sdk-for-go/{service-dir}/armcleanroom
    fix-const-stuttering: true
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
    flavor: azure
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-cleanroom"
    namespace: azure.mgmt.cleanroom
    generate-test: true
    generate-sample: true
    flavor: azure
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-cleanroom"
    flavor: azure
    namespace: com.azure.resourcemanager.cleanroom
    service-name: CleanRoom
  "@azure-tools/typespec-ts":
    experimental-extensible-enums: true
    emitter-output-dir: "{output-dir}/{service-dir}/arm-cleanroom"
    is-modular-library: true
    package-details:
      name: "@azure/arm-cleanroom"
    flavor: azure
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
parameters:
  service-dir:
    default: sdk/cleanroom
