versions:
  - version: 2015-08-01-preview
    source: swagger
    swagger-files:
      - ./preview/2015-08-01-preview/portal.json
  - version: 2018-10-01-preview
    source: swagger
    swagger-files:
      - ./preview/2018-10-01-preview/portal.json
  - version: 2019-01-01-preview
    source: swagger
    swagger-files:
      - ./preview/2019-01-01-preview/portal.json
      - ./preview/2019-01-01-preview/tenantConfiguration.json
  - version: 2020-09-01-preview
    source: typespec
    swagger-files:
      - preview/2020-09-01-preview/tenantConfiguration.json
      - preview/2020-09-01-preview/portal.json
      - preview/2020-09-01-preview/common.json
  - version: 2022-12-01-preview
    source: typespec
    swagger-files:
      - preview/2022-12-01-preview/tenantConfiguration.json
      - preview/2022-12-01-preview/portal.json
      - preview/2022-12-01-preview/common.json
  - version: 2025-04-01-preview
    source: typespec
    swagger-files:
      - preview/2025-04-01-preview/tenantConfiguration.json
      - preview/2025-04-01-preview/portal.json
      - preview/2025-04-01-preview/common.json
  - version: 2026-04-01
    source: typespec
    swagger-files:
      - stable/2026-04-01/tenantConfiguration.json
      - stable/2026-04-01/portal.json
      - stable/2026-04-01/common.json
