versions:
  - version: 2023-07-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.ApiCenter/preview/2023-07-01-preview/apicenter.json
  - version: 2024-03-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ApiCenter/stable/2024-03-01/apicenter.json
  - version: 2024-03-15-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ApiCenter/preview/2024-03-15-preview/apicenter.json
  - version: 2024-06-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ApiCenter/preview/2024-06-01-preview/apicenter.json
