versions:
  - version: 2017-02-27-preview
    source: swagger
    swagger-files:
      - preview/2017-02-27-preview/billing.json
  - version: 2017-04-24-preview
    source: swagger
    swagger-files:
      - preview/2017-04-24-preview/billing.json
  - version: 2018-03-01-preview
    source: swagger
    swagger-files:
      - preview/2018-03-01-preview/billing.json
      - preview/2018-03-01-preview/billingV2.json
  - version: 2018-11-01-preview
    source: swagger
    swagger-files:
      - preview/2018-11-01-preview/billing.json
  - version: 2019-10-01-preview
    source: swagger
    swagger-files:
      - preview/2019-10-01-preview/billing.json
  - version: 2020-05-01
    source: swagger
    swagger-files:
      - stable/2020-05-01/billing.json
      - stable/2020-05-01/billingOperations.json
  - version: 2020-09-01-preview
    source: swagger
    swagger-files:
      - preview/2020-09-01-preview/billingOperations.json
      - preview/2020-09-01-preview/billingPromotions.json
  - version: 2020-11-01-preview
    source: swagger
    swagger-files:
      - preview/2020-11-01-preview/billingOperations.json
      - preview/2020-11-01-preview/billingPromotions.json
  - version: 2021-10-01
    source: swagger
    swagger-files:
      - stable/2021-10-01/billingSubscription.json
      - stable/2021-10-01/payment.json
  - version: 2024-04-01
    source: typespec
    swagger-files:
      - stable/2024-04-01/openapi.json
  - version: 2024-08-01-preview
    source: swagger
    swagger-files:
      - preview/2024-08-01-preview/migration.json
      - preview/2024-08-01-preview/operation.json
      - preview/2024-08-01-preview/types.json
