versions:
  - version: 2023-03-01-preview
    source: typespec
    swagger-files:
      - ../../data-plane/HealthInsights/preview/2023-03-01-preview/openapi.json
  - version: 2023-09-01-preview
    source: typespec
    swagger-files:
      - ../../data-plane/HealthInsights/preview/2023-09-01-preview/openapi.json
  - version: 2024-04-01
    source: typespec
    swagger-files:
      - ../../data-plane/HealthInsights/stable/2024-04-01/openapi.json
  - version: 2024-08-01-preview
    source: typespec
    swagger-files:
      - ../../data-plane/HealthInsights/preview/2024-08-01-preview/openapi.json
  - version: 2024-10-01
    source: typespec
    swagger-files:
      - ../../data-plane/HealthInsights/stable/2024-10-01/openapi.json
