versions:
  - version: 2025-04-01
    source: typespec
    swagger-files:
      - stable/2025-04-01/deploymentsafeguards.json
  - version: 2025-04-02-preview
    source: typespec
    swagger-files:
      - preview/2025-04-02-preview/deploymentsafeguards.json
  - version: 2025-05-02-preview
    source: typespec
    swagger-files:
      - preview/2025-05-02-preview/deploymentsafeguards.json
  - version: 2025-07-01
    source: typespec
    swagger-files:
      - stable/2025-07-01/deploymentsafeguards.json
