versions:
  - version: 2015-02-01-preview
    source: swagger
    swagger-files:
      - preview/2015-02-01-preview/logic.json
  - version: 2015-08-01-preview
    source: swagger
    swagger-files:
      - preview/2015-08-01-preview/logic.json
  - version: 2016-06-01
    source: swagger
    swagger-files:
      - stable/2016-06-01/logic.json
  - version: 2018-07-01-preview
    source: swagger
    swagger-files:
      - preview/2018-07-01-preview/logic.json
  - version: 2019-05-01
    source: swagger
    swagger-files:
      - stable/2019-05-01/logic.json
  - version: 2026-04-01-preview
    source: typespec
    swagger-files:
      - preview/2026-04-01-preview/automationproject.json
