parameters:
  "service-dir":
    default: "sdk/logic"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    omit-unreachable-types: true
    emitter-output-dir: "{project-root}"
    output-file: "{version-status}/{version}/logic.json"
    emit-lro-options: "all"
    examples-dir: "{project-root}/examples"
    arm-types-dir: "{project-root}/../../../../common-types/resource-management"
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-logic"
    namespace: "azure.mgmt.logic"
    generate-test: true
    generate-sample: true
    flavor: azure
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-logic"
    namespace: "com.azure.resourcemanager.logic"
    flavor: azure
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/logic"
    emitter-output-dir: "{output-dir}/{service-dir}/armlogic"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armlogic"
    flavor: azure
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-tools/typespec-ts":
    flavor: azure
    experimental-extensible-enums: true
    emitter-output-dir: "{output-dir}/{service-dir}/arm-logic"
    package-details:
      name: "@azure/arm-logic"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
