versions:
  - version: 2024-01-15-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ProgrammableConnectivity/preview/2024-01-15-preview/openapi.json
  - version: 2025-03-30-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.ProgrammableConnectivity/preview/2025-03-30-preview/openapi.json
