versions:
  - version: 2025-04-30-preview
    source: typespec
    swagger-files:
      - ../data-plane/Microsoft.PlanetaryComputer/preview/2025-04-30-preview/openapi.json
  - version: 2026-04-15
    source: typespec
    swagger-files:
      - ../data-plane/Microsoft.PlanetaryComputer/stable/2026-04-15/openapi.json
