versions:
  - version: 2018-09-01-preview
    source: swagger
    swagger-files:
      - stable/2018-09-01-preview/attestation.json
  - version: 2020-10-01
    source: swagger
    swagger-files:
      - stable/2020-10-01/attestation.json
  - version: 2022-08-01
    source: swagger
    swagger-files:
      - stable/2022-08-01/attestation.json
  - version: 2022-09-01-preview
    source: swagger
    swagger-files:
      - preview/2022-09-01-preview/attestation.json
  - version: 2025-06-01
    source: typespec
    swagger-files:
      - stable/2025-06-01/attestation.json
