versions:
  - version: 2023-01-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.StorageActions/stable/2023-01-01/storageactions.json
  - version: 2026-03-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.StorageActions/stable/2026-03-01/storageactions.json
