versions:
  - version: 2018-06-01
    source: swagger
    swagger-files:
      - ../stable/2018-06-01/pricings.json
  - version: 2022-03-01
    source: swagger
    swagger-files:
      - ../stable/2022-03-01/pricings.json
  - version: 2023-01-01
    source: swagger
    swagger-files:
      - ../stable/2023-01-01/pricings.json
  - version: 2024-01-01
    source: typespec
    swagger-files:
      - ../stable/2024-01-01/pricings.json
  - version: 2025-10-01-preview
    source: swagger
    swagger-files:
      - ../preview/2025-10-01-preview/pricings.json
