versions:
  - version: 2025-06-01
    source: typespec
    swagger-files:
      - stable/2025-06-01/configurations.json
  - version: 2025-08-01
    source: typespec
    swagger-files:
      - stable/2025-08-01/configurations.json
