versions:
  - version: 2025-03-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Nginx.NginxPlus/preview/2025-03-01-preview/swagger.json
  - version: 2025-11-01
    source: typespec
    swagger-files:
      - ../resource-manager/Nginx.NginxPlus/stable/2025-11-01/swagger.json
