versions:
  - version: 2023-02-08-preview
    source: swagger
    swagger-files:
      - preview/2023-02-08-preview/common.json
      - preview/2023-02-08-preview/firmwares.json
      - preview/2023-02-08-preview/operations.json
      - preview/2023-02-08-preview/workspaces.json
  - version: 2024-01-10
    source: swagger
    swagger-files:
      - stable/2024-01-10/binaryHardeningResults.json
      - stable/2024-01-10/common.json
      - stable/2024-01-10/cryptoCertificates.json
      - stable/2024-01-10/cryptoKeys.json
      - stable/2024-01-10/cves.json
      - stable/2024-01-10/firmwares.json
      - stable/2024-01-10/operations.json
      - stable/2024-01-10/passwordHashes.json
      - stable/2024-01-10/sbomComponents.json
      - stable/2024-01-10/summaries.json
      - stable/2024-01-10/workspaces.json
  - version: 2025-04-01-preview
    source: typespec
    swagger-files:
      - preview/2025-04-01-preview/iotfirmwaredefense.json
  - version: 2025-08-02
    source: typespec
    swagger-files:
      - stable/2025-08-02/iotfirmwaredefense.json
  - version: 2025-12-01-preview
    source: typespec
    swagger-files:
      - preview/2025-12-01-preview/iotfirmwaredefense.json
