// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.costmanagement.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Show costs accumulated over time.
 */
public final class AccumulatedType extends ExpandableStringEnum<AccumulatedType> {
    /**
     * Static value true for AccumulatedType.
     */
    public static final AccumulatedType TRUE = fromString("true");

    /**
     * Static value false for AccumulatedType.
     */
    public static final AccumulatedType FALSE = fromString("false");

    /**
     * Creates a new instance of AccumulatedType value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public AccumulatedType() {
    }

    /**
     * Creates or finds a AccumulatedType from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding AccumulatedType.
     */
    public static AccumulatedType fromString(String name) {
        return fromString(name, AccumulatedType.class);
    }

    /**
     * Gets known AccumulatedType values.
     * 
     * @return known AccumulatedType values.
     */
    public static Collection<AccumulatedType> values() {
        return values(AccumulatedType.class);
    }
}
