// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.costmanagement.models;

import com.azure.resourcemanager.costmanagement.fluent.models.BenefitUtilizationSummariesOperationStatusInner;

/**
 * An immutable client-side representation of BenefitUtilizationSummariesOperationStatus.
 */
public interface BenefitUtilizationSummariesOperationStatus {
    /**
     * Gets the input property: Input given to create the benefit utilization summaries report.
     * 
     * @return the input value.
     */
    BenefitUtilizationSummariesRequest input();

    /**
     * Gets the status property: The status of the creation of the benefit utilization summaries report.
     * 
     * @return the status value.
     */
    OperationStatusType status();

    /**
     * Gets the properties property: Contains sas url to the async benefit utilization summaries report and a date that
     * the url is valid until. These values will be empty if the report is in a Running or Failed state.
     * 
     * @return the properties value.
     */
    AsyncOperationStatusProperties properties();

    /**
     * Gets the inner
     * com.azure.resourcemanager.costmanagement.fluent.models.BenefitUtilizationSummariesOperationStatusInner object.
     * 
     * @return the inner object.
     */
    BenefitUtilizationSummariesOperationStatusInner innerModel();
}
