// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.costmanagement.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * The status of the cost details operation.
 */
public final class CostDetailsStatusType extends ExpandableStringEnum<CostDetailsStatusType> {
    /**
     * Operation is Completed.
     */
    public static final CostDetailsStatusType COMPLETED_COST_DETAILS_STATUS_TYPE = fromString("Completed");

    /**
     * Operation is Completed and no cost data found.
     */
    public static final CostDetailsStatusType NO_DATA_FOUND_COST_DETAILS_STATUS_TYPE = fromString("NoDataFound");

    /**
     * Operation Failed.
     */
    public static final CostDetailsStatusType FAILED_COST_DETAILS_STATUS_TYPE = fromString("Failed");

    /**
     * Creates a new instance of CostDetailsStatusType value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public CostDetailsStatusType() {
    }

    /**
     * Creates or finds a CostDetailsStatusType from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding CostDetailsStatusType.
     */
    public static CostDetailsStatusType fromString(String name) {
        return fromString(name, CostDetailsStatusType.class);
    }

    /**
     * Gets known CostDetailsStatusType values.
     * 
     * @return known CostDetailsStatusType values.
     */
    public static Collection<CostDetailsStatusType> values() {
        return values(CostDetailsStatusType.class);
    }
}
