// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.costmanagement.models;

import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.Map;

/**
 * The Resource model definition.
 */
@Immutable
public class CostManagementResource implements JsonSerializable<CostManagementResource> {
    /*
     * Resource Id.
     */
    private String id;

    /*
     * Resource name.
     */
    private String name;

    /*
     * Resource type.
     */
    private String type;

    /*
     * Location of the resource.
     */
    private String location;

    /*
     * SKU of the resource.
     */
    private String sku;

    /*
     * ETag of the resource.
     */
    private String etag;

    /*
     * Resource tags.
     */
    private Map<String, String> tags;

    /**
     * Creates an instance of CostManagementResource class.
     */
    protected CostManagementResource() {
    }

    /**
     * Get the id property: Resource Id.
     * 
     * @return the id value.
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id property: Resource Id.
     * 
     * @param id the id value to set.
     * @return the CostManagementResource object itself.
     */
    CostManagementResource withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get the name property: Resource name.
     * 
     * @return the name value.
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name property: Resource name.
     * 
     * @param name the name value to set.
     * @return the CostManagementResource object itself.
     */
    CostManagementResource withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the type property: Resource type.
     * 
     * @return the type value.
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type property: Resource type.
     * 
     * @param type the type value to set.
     * @return the CostManagementResource object itself.
     */
    CostManagementResource withType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get the location property: Location of the resource.
     * 
     * @return the location value.
     */
    public String location() {
        return this.location;
    }

    /**
     * Set the location property: Location of the resource.
     * 
     * @param location the location value to set.
     * @return the CostManagementResource object itself.
     */
    CostManagementResource withLocation(String location) {
        this.location = location;
        return this;
    }

    /**
     * Get the sku property: SKU of the resource.
     * 
     * @return the sku value.
     */
    public String sku() {
        return this.sku;
    }

    /**
     * Set the sku property: SKU of the resource.
     * 
     * @param sku the sku value to set.
     * @return the CostManagementResource object itself.
     */
    CostManagementResource withSku(String sku) {
        this.sku = sku;
        return this;
    }

    /**
     * Get the etag property: ETag of the resource.
     * 
     * @return the etag value.
     */
    public String etag() {
        return this.etag;
    }

    /**
     * Set the etag property: ETag of the resource.
     * 
     * @param etag the etag value to set.
     * @return the CostManagementResource object itself.
     */
    CostManagementResource withEtag(String etag) {
        this.etag = etag;
        return this;
    }

    /**
     * Get the tags property: Resource tags.
     * 
     * @return the tags value.
     */
    public Map<String, String> tags() {
        return this.tags;
    }

    /**
     * Set the tags property: Resource tags.
     * 
     * @param tags the tags value to set.
     * @return the CostManagementResource object itself.
     */
    CostManagementResource withTags(Map<String, String> tags) {
        this.tags = tags;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of CostManagementResource from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of CostManagementResource if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IOException If an error occurs while reading the CostManagementResource.
     */
    public static CostManagementResource fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            CostManagementResource deserializedCostManagementResource = new CostManagementResource();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("id".equals(fieldName)) {
                    deserializedCostManagementResource.id = reader.getString();
                } else if ("name".equals(fieldName)) {
                    deserializedCostManagementResource.name = reader.getString();
                } else if ("type".equals(fieldName)) {
                    deserializedCostManagementResource.type = reader.getString();
                } else if ("location".equals(fieldName)) {
                    deserializedCostManagementResource.location = reader.getString();
                } else if ("sku".equals(fieldName)) {
                    deserializedCostManagementResource.sku = reader.getString();
                } else if ("eTag".equals(fieldName)) {
                    deserializedCostManagementResource.etag = reader.getString();
                } else if ("tags".equals(fieldName)) {
                    Map<String, String> tags = reader.readMap(reader1 -> reader1.getString());
                    deserializedCostManagementResource.tags = tags;
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedCostManagementResource;
        });
    }
}
