// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.costmanagement.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Frequency of a notification. Represents how long the notification will be silent after triggering an alert for a
 * threshold breach. If not specified, the frequency will be set by default based on the timeGrain (Weekly when
 * timeGrain: Last7Days, Monthly when timeGrain: Last30Days).
 * 
 * Supported for CategoryType(s): ReservationUtilization.
 */
public final class Frequency extends ExpandableStringEnum<Frequency> {
    /**
     * After the threshold breaches and an Alert is fired, no further alerts will be sent until the next calendar day.
     */
    public static final Frequency DAILY = fromString("Daily");

    /**
     * After the threshold breaches and an Alert is fired, no further alerts will be sent for 7 calendar days.
     */
    public static final Frequency WEEKLY = fromString("Weekly");

    /**
     * After the threshold breaches and an Alert is fired, no further alerts will be sent for 30 calendar days.
     */
    public static final Frequency MONTHLY = fromString("Monthly");

    /**
     * Creates a new instance of Frequency value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public Frequency() {
    }

    /**
     * Creates or finds a Frequency from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding Frequency.
     */
    public static Frequency fromString(String name) {
        return fromString(name, Frequency.class);
    }

    /**
     * Gets known Frequency values.
     * 
     * @return known Frequency values.
     */
    public static Collection<Frequency> values() {
        return values(Frequency.class);
    }
}
