// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.costmanagement.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * The notification associated with a budget.
 * 
 * Supported for CategoryType(s): Cost, ReservationUtilization.
 */
@Fluent
public final class Notification implements JsonSerializable<Notification> {
    /*
     * The notification is enabled or not.
     * 
     * Supported for CategoryType(s): Cost, ReservationUtilization.
     */
    private boolean enabled;

    /*
     * The comparison operator.
     * 
     * Supported for CategoryType(s): Cost, ReservationUtilization.
     * 
     * Supported operators for **CategoryType: Cost**
     * - GreaterThan
     * - GreaterThanOrEqualTo
     * 
     * Supported operators for **CategoryType: ReservationUtilization**
     * - LessThan
     */
    private BudgetNotificationOperatorType operator;

    /*
     * Threshold value associated with a notification. It is always percent with a maximum of 2 decimal places.
     * 
     * Supported for CategoryType(s): Cost, ReservationUtilization.
     * 
     * **CategoryType: Cost** - Must be between 0 and 1000. Notification is sent when the cost exceeded the threshold.
     * 
     * **CategoryType: ReservationUtilization** - Must be between 0 and 100. Notification is sent when a reservation has
     * a utilization percentage below the threshold.
     */
    private double threshold;

    /*
     * Frequency of a notification. Represents how long the notification will be silent after triggering an alert for a
     * threshold breach. If not specified, the frequency will be set by default based on the timeGrain (Weekly when
     * timeGrain: Last7Days, Monthly when timeGrain: Last30Days).
     * 
     * Supported for CategoryType(s): ReservationUtilization.
     */
    private Frequency frequency;

    /*
     * Email addresses to send the notification to when the threshold is breached. Must have at least one contact email
     * or contact group specified at the Subscription or Resource Group scopes. All other scopes must have at least one
     * contact email specified.
     * 
     * Supported for CategoryType(s): Cost, ReservationUtilization.
     */
    private List<String> contactEmails;

    /*
     * Subscription or Resource Group scopes only. Contact roles to send the notification to when the threshold is
     * breached.
     * 
     * Supported for CategoryType(s): Cost.
     */
    private List<String> contactRoles;

    /*
     * Subscription or Resource Group scopes only. Action groups to send the notification to when the threshold is
     * exceeded. Must be provided as a fully qualified Azure resource id.
     * 
     * Supported for CategoryType(s): Cost.
     */
    private List<String> contactGroups;

    /*
     * The type of threshold.
     * 
     * Supported for CategoryType(s): Cost.
     */
    private ThresholdType thresholdType;

    /*
     * Language in which the recipient will receive the notification,
     * 
     * Supported for CategoryType(s): Cost, ReservationUtilization.
     */
    private CultureCode locale;

    /**
     * Creates an instance of Notification class.
     */
    public Notification() {
    }

    /**
     * Get the enabled property: The notification is enabled or not.
     * 
     * Supported for CategoryType(s): Cost, ReservationUtilization.
     * 
     * @return the enabled value.
     */
    public boolean enabled() {
        return this.enabled;
    }

    /**
     * Set the enabled property: The notification is enabled or not.
     * 
     * Supported for CategoryType(s): Cost, ReservationUtilization.
     * 
     * @param enabled the enabled value to set.
     * @return the Notification object itself.
     */
    public Notification withEnabled(boolean enabled) {
        this.enabled = enabled;
        return this;
    }

    /**
     * Get the operator property: The comparison operator.
     * 
     * Supported for CategoryType(s): Cost, ReservationUtilization.
     * 
     * Supported operators for **CategoryType: Cost**
     * - GreaterThan
     * - GreaterThanOrEqualTo
     * 
     * Supported operators for **CategoryType: ReservationUtilization**
     * - LessThan.
     * 
     * @return the operator value.
     */
    public BudgetNotificationOperatorType operator() {
        return this.operator;
    }

    /**
     * Set the operator property: The comparison operator.
     * 
     * Supported for CategoryType(s): Cost, ReservationUtilization.
     * 
     * Supported operators for **CategoryType: Cost**
     * - GreaterThan
     * - GreaterThanOrEqualTo
     * 
     * Supported operators for **CategoryType: ReservationUtilization**
     * - LessThan.
     * 
     * @param operator the operator value to set.
     * @return the Notification object itself.
     */
    public Notification withOperator(BudgetNotificationOperatorType operator) {
        this.operator = operator;
        return this;
    }

    /**
     * Get the threshold property: Threshold value associated with a notification. It is always percent with a maximum
     * of 2 decimal places.
     * 
     * Supported for CategoryType(s): Cost, ReservationUtilization.
     * 
     * **CategoryType: Cost** - Must be between 0 and 1000. Notification is sent when the cost exceeded the threshold.
     * 
     * **CategoryType: ReservationUtilization** - Must be between 0 and 100. Notification is sent when a reservation has
     * a utilization percentage below the threshold.
     * 
     * @return the threshold value.
     */
    public double threshold() {
        return this.threshold;
    }

    /**
     * Set the threshold property: Threshold value associated with a notification. It is always percent with a maximum
     * of 2 decimal places.
     * 
     * Supported for CategoryType(s): Cost, ReservationUtilization.
     * 
     * **CategoryType: Cost** - Must be between 0 and 1000. Notification is sent when the cost exceeded the threshold.
     * 
     * **CategoryType: ReservationUtilization** - Must be between 0 and 100. Notification is sent when a reservation has
     * a utilization percentage below the threshold.
     * 
     * @param threshold the threshold value to set.
     * @return the Notification object itself.
     */
    public Notification withThreshold(double threshold) {
        this.threshold = threshold;
        return this;
    }

    /**
     * Get the frequency property: Frequency of a notification. Represents how long the notification will be silent
     * after triggering an alert for a threshold breach. If not specified, the frequency will be set by default based on
     * the timeGrain (Weekly when timeGrain: Last7Days, Monthly when timeGrain: Last30Days).
     * 
     * Supported for CategoryType(s): ReservationUtilization.
     * 
     * @return the frequency value.
     */
    public Frequency frequency() {
        return this.frequency;
    }

    /**
     * Set the frequency property: Frequency of a notification. Represents how long the notification will be silent
     * after triggering an alert for a threshold breach. If not specified, the frequency will be set by default based on
     * the timeGrain (Weekly when timeGrain: Last7Days, Monthly when timeGrain: Last30Days).
     * 
     * Supported for CategoryType(s): ReservationUtilization.
     * 
     * @param frequency the frequency value to set.
     * @return the Notification object itself.
     */
    public Notification withFrequency(Frequency frequency) {
        this.frequency = frequency;
        return this;
    }

    /**
     * Get the contactEmails property: Email addresses to send the notification to when the threshold is breached. Must
     * have at least one contact email or contact group specified at the Subscription or Resource Group scopes. All
     * other scopes must have at least one contact email specified.
     * 
     * Supported for CategoryType(s): Cost, ReservationUtilization.
     * 
     * @return the contactEmails value.
     */
    public List<String> contactEmails() {
        return this.contactEmails;
    }

    /**
     * Set the contactEmails property: Email addresses to send the notification to when the threshold is breached. Must
     * have at least one contact email or contact group specified at the Subscription or Resource Group scopes. All
     * other scopes must have at least one contact email specified.
     * 
     * Supported for CategoryType(s): Cost, ReservationUtilization.
     * 
     * @param contactEmails the contactEmails value to set.
     * @return the Notification object itself.
     */
    public Notification withContactEmails(List<String> contactEmails) {
        this.contactEmails = contactEmails;
        return this;
    }

    /**
     * Get the contactRoles property: Subscription or Resource Group scopes only. Contact roles to send the notification
     * to when the threshold is breached.
     * 
     * Supported for CategoryType(s): Cost.
     * 
     * @return the contactRoles value.
     */
    public List<String> contactRoles() {
        return this.contactRoles;
    }

    /**
     * Set the contactRoles property: Subscription or Resource Group scopes only. Contact roles to send the notification
     * to when the threshold is breached.
     * 
     * Supported for CategoryType(s): Cost.
     * 
     * @param contactRoles the contactRoles value to set.
     * @return the Notification object itself.
     */
    public Notification withContactRoles(List<String> contactRoles) {
        this.contactRoles = contactRoles;
        return this;
    }

    /**
     * Get the contactGroups property: Subscription or Resource Group scopes only. Action groups to send the
     * notification to when the threshold is exceeded. Must be provided as a fully qualified Azure resource id.
     * 
     * Supported for CategoryType(s): Cost.
     * 
     * @return the contactGroups value.
     */
    public List<String> contactGroups() {
        return this.contactGroups;
    }

    /**
     * Set the contactGroups property: Subscription or Resource Group scopes only. Action groups to send the
     * notification to when the threshold is exceeded. Must be provided as a fully qualified Azure resource id.
     * 
     * Supported for CategoryType(s): Cost.
     * 
     * @param contactGroups the contactGroups value to set.
     * @return the Notification object itself.
     */
    public Notification withContactGroups(List<String> contactGroups) {
        this.contactGroups = contactGroups;
        return this;
    }

    /**
     * Get the thresholdType property: The type of threshold.
     * 
     * Supported for CategoryType(s): Cost.
     * 
     * @return the thresholdType value.
     */
    public ThresholdType thresholdType() {
        return this.thresholdType;
    }

    /**
     * Set the thresholdType property: The type of threshold.
     * 
     * Supported for CategoryType(s): Cost.
     * 
     * @param thresholdType the thresholdType value to set.
     * @return the Notification object itself.
     */
    public Notification withThresholdType(ThresholdType thresholdType) {
        this.thresholdType = thresholdType;
        return this;
    }

    /**
     * Get the locale property: Language in which the recipient will receive the notification,
     * 
     * Supported for CategoryType(s): Cost, ReservationUtilization.
     * 
     * @return the locale value.
     */
    public CultureCode locale() {
        return this.locale;
    }

    /**
     * Set the locale property: Language in which the recipient will receive the notification,
     * 
     * Supported for CategoryType(s): Cost, ReservationUtilization.
     * 
     * @param locale the locale value to set.
     * @return the Notification object itself.
     */
    public Notification withLocale(CultureCode locale) {
        this.locale = locale;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeBooleanField("enabled", this.enabled);
        jsonWriter.writeStringField("operator", this.operator == null ? null : this.operator.toString());
        jsonWriter.writeDoubleField("threshold", this.threshold);
        jsonWriter.writeArrayField("contactEmails", this.contactEmails,
            (writer, element) -> writer.writeString(element));
        jsonWriter.writeStringField("frequency", this.frequency == null ? null : this.frequency.toString());
        jsonWriter.writeArrayField("contactRoles", this.contactRoles, (writer, element) -> writer.writeString(element));
        jsonWriter.writeArrayField("contactGroups", this.contactGroups,
            (writer, element) -> writer.writeString(element));
        jsonWriter.writeStringField("thresholdType", this.thresholdType == null ? null : this.thresholdType.toString());
        jsonWriter.writeStringField("locale", this.locale == null ? null : this.locale.toString());
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of Notification from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of Notification if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the Notification.
     */
    public static Notification fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            Notification deserializedNotification = new Notification();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("enabled".equals(fieldName)) {
                    deserializedNotification.enabled = reader.getBoolean();
                } else if ("operator".equals(fieldName)) {
                    deserializedNotification.operator = BudgetNotificationOperatorType.fromString(reader.getString());
                } else if ("threshold".equals(fieldName)) {
                    deserializedNotification.threshold = reader.getDouble();
                } else if ("contactEmails".equals(fieldName)) {
                    List<String> contactEmails = reader.readArray(reader1 -> reader1.getString());
                    deserializedNotification.contactEmails = contactEmails;
                } else if ("frequency".equals(fieldName)) {
                    deserializedNotification.frequency = Frequency.fromString(reader.getString());
                } else if ("contactRoles".equals(fieldName)) {
                    List<String> contactRoles = reader.readArray(reader1 -> reader1.getString());
                    deserializedNotification.contactRoles = contactRoles;
                } else if ("contactGroups".equals(fieldName)) {
                    List<String> contactGroups = reader.readArray(reader1 -> reader1.getString());
                    deserializedNotification.contactGroups = contactGroups;
                } else if ("thresholdType".equals(fieldName)) {
                    deserializedNotification.thresholdType = ThresholdType.fromString(reader.getString());
                } else if ("locale".equals(fieldName)) {
                    deserializedNotification.locale = CultureCode.fromString(reader.getString());
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedNotification;
        });
    }
}
