// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.costmanagement.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.CoreUtils;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;

/**
 * The start and end date for pulling data for the report.
 */
@Fluent
public final class ReportConfigTimePeriod implements JsonSerializable<ReportConfigTimePeriod> {
    /*
     * The start date to pull data from.
     */
    private OffsetDateTime from;

    /*
     * The end date to pull data to.
     */
    private OffsetDateTime to;

    /**
     * Creates an instance of ReportConfigTimePeriod class.
     */
    public ReportConfigTimePeriod() {
    }

    /**
     * Get the from property: The start date to pull data from.
     * 
     * @return the from value.
     */
    public OffsetDateTime from() {
        return this.from;
    }

    /**
     * Set the from property: The start date to pull data from.
     * 
     * @param from the from value to set.
     * @return the ReportConfigTimePeriod object itself.
     */
    public ReportConfigTimePeriod withFrom(OffsetDateTime from) {
        this.from = from;
        return this;
    }

    /**
     * Get the to property: The end date to pull data to.
     * 
     * @return the to value.
     */
    public OffsetDateTime to() {
        return this.to;
    }

    /**
     * Set the to property: The end date to pull data to.
     * 
     * @param to the to value to set.
     * @return the ReportConfigTimePeriod object itself.
     */
    public ReportConfigTimePeriod withTo(OffsetDateTime to) {
        this.to = to;
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("from",
            this.from == null ? null : DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(this.from));
        jsonWriter.writeStringField("to",
            this.to == null ? null : DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(this.to));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of ReportConfigTimePeriod from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of ReportConfigTimePeriod if the JsonReader was pointing to an instance of it, or null if it
     * was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the ReportConfigTimePeriod.
     */
    public static ReportConfigTimePeriod fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            ReportConfigTimePeriod deserializedReportConfigTimePeriod = new ReportConfigTimePeriod();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("from".equals(fieldName)) {
                    deserializedReportConfigTimePeriod.from = reader
                        .getNullable(nonNullReader -> CoreUtils.parseBestOffsetDateTime(nonNullReader.getString()));
                } else if ("to".equals(fieldName)) {
                    deserializedReportConfigTimePeriod.to = reader
                        .getNullable(nonNullReader -> CoreUtils.parseBestOffsetDateTime(nonNullReader.getString()));
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedReportConfigTimePeriod;
        });
    }
}
