versions:
  - version: 2026-10-01-preview
    source: typespec
    swagger-files:
      - preview/2026-10-01-preview/privateTrafficManager.json
  - version: 2026-02-09-preview
    source: typespec
    swagger-files:
      - preview/2026-02-09-preview/privateTrafficManager.json
