versions:
  - version: 2025-08-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.DBforPostgreSQL/stable/2025-08-01/openapi.json
  - version: 2026-01-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.DBforPostgreSQL/preview/2026-01-01-preview/openapi.json
  - version: 2026-04-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.DBforPostgreSQL/preview/2026-04-01-preview/openapi.json
