versions:
  - version: 2025-11-01
    source: typespec
    swagger-files:
      - stable/2025-11-01/containerregistry.json
  - version: 2026-03-01-preview
    source: typespec
    swagger-files:
      - preview/2026-03-01-preview/containerregistry.json
