versions:
  - version: 2020-04-01-preview
    source: swagger
    swagger-files:
      - preview/2020-04-01-preview/dnsresolver.json
  - version: 2022-07-01
    source: swagger
    swagger-files:
      - stable/2022-07-01/dnsresolver.json
  - version: 2023-07-01-preview
    source: swagger
    swagger-files:
      - preview/2023-07-01-preview/dnsresolver.json
      - preview/2023-07-01-preview/dnsresolverpolicy.json
  - version: 2025-05-01
    source: typespec
    swagger-files:
      - stable/2025-05-01/openapi.json
  - version: 2025-10-01-preview
    source: typespec
    swagger-files:
      - preview/2025-10-01-preview/openapi.json
