versions:
  - version: 2023-11-01-preview
    source: typespec
    swagger-files:
      - preview/2023-11-01-preview/azurefleet.json
  - version: 2024-05-01-preview
    source: typespec
    swagger-files:
      - preview/2024-05-01-preview/azurefleet.json
  - version: 2024-11-01
    source: typespec
    swagger-files:
      - stable/2024-11-01/azurefleet.json
  - version: 2026-04-01-preview
    source: typespec
    swagger-files:
      - preview/2026-04-01-preview/azurefleet.json
  - version: 2026-06-01-preview
    source: typespec
    swagger-files:
      - preview/2026-06-01-preview/azurefleet.json
