versions:
  - version: 2024-11-01-preview
    source: typespec
    swagger-files:
      - preview/2024-11-01-preview/servicefabricmanagedclusters.json
  - version: 2025-03-01-preview
    source: typespec
    swagger-files:
      - preview/2025-03-01-preview/servicefabricmanagedclusters.json
  - version: 2025-06-01-preview
    source: typespec
    swagger-files:
      - preview/2025-06-01-preview/servicefabricmanagedclusters.json
  - version: 2025-10-01-preview
    source: typespec
    swagger-files:
      - preview/2025-10-01-preview/servicefabricmanagedclusters.json
  - version: 2026-02-01
    source: typespec
    swagger-files:
      - stable/2026-02-01/servicefabricmanagedclusters.json
  - version: 2026-05-01-preview
    source: typespec
    swagger-files:
      - preview/2026-05-01-preview/servicefabricmanagedclusters.json
