versions:
  - version: 2017-12-01
    source: swagger
    swagger-files:
      - stable/2017-12-01/ServerSecurityAlertPolicies.json
      - stable/2017-12-01/postgresql.json
  - version: 2017-12-01-preview
    source: swagger
    swagger-files:
      - preview/2017-12-01-preview/postgresql.json
  - version: 2018-06-01
    source: swagger
    swagger-files:
      - stable/2018-06-01/PerformanceRecommendations.json
      - stable/2018-06-01/PrivateEndpointConnections.json
      - stable/2018-06-01/PrivateLinkResources.json
      - stable/2018-06-01/QueryPerformanceInsights.json
  - version: 2018-06-01-privatepreview
    source: swagger
    swagger-files:
      - preview/2018-06-01-privatepreview/PrivateEndpointConnections.json
      - preview/2018-06-01-privatepreview/PrivateLinkResources.json
  - version: 2020-01-01
    source: swagger
    swagger-files:
      - stable/2020-01-01/DataEncryptionKeys.json
  - version: 2020-01-01-privatepreview
    source: swagger
    swagger-files:
      - preview/2020-01-01-privatepreview/DataEncryptionKeys.json
  - version: 2020-02-14-preview
    source: swagger
    swagger-files:
      - preview/2020-02-14-preview/postgresql.json
  - version: 2020-02-14-privatepreview
    source: swagger
    swagger-files:
      - preview/2020-02-14-privatepreview/postgresql.json
  - version: 2020-11-05-preview
    source: swagger
    swagger-files:
      - preview/2020-11-05-preview/Databases.json
  - version: 2021-03-31-privatepreview
    source: swagger
    swagger-files:
      - preview/2021-03-31-privatepreview/PrivateDnsZone.json
  - version: 2021-04-10-privatepreview
    source: swagger
    swagger-files:
      - preview/2021-04-10-privatepreview/postgresql.json
  - version: 2021-06-01
    source: swagger
    swagger-files:
      - stable/2021-06-01/Databases.json
      - stable/2021-06-01/PrivateDnsZone.json
      - stable/2021-06-01/postgresql.json
  - version: 2021-06-01-preview
    source: swagger
    swagger-files:
      - preview/2021-06-01-preview/Databases.json
      - preview/2021-06-01-preview/IntelligentPerformance.json
      - preview/2021-06-01-preview/QueryPerformanceInsights.json
      - preview/2021-06-01-preview/postgresql.json
  - version: 2021-06-15-privatepreview
    source: swagger
    swagger-files:
      - preview/2021-06-15-privatepreview/Migrations.json
      - preview/2021-06-15-privatepreview/postgresql.json
  - version: 2022-01-20-preview
    source: swagger
    swagger-files:
      - preview/2022-01-20-preview/Databases.json
      - preview/2022-01-20-preview/PrivateDnsZone.json
      - preview/2022-01-20-preview/postgresql.json
  - version: 2022-03-08-preview
    source: swagger
    swagger-files:
      - preview/2022-03-08-preview/Administrators.json
      - preview/2022-03-08-preview/Backups.json
      - preview/2022-03-08-preview/Capabilities.json
      - preview/2022-03-08-preview/CheckNameAvailability.json
      - preview/2022-03-08-preview/Configuration.json
      - preview/2022-03-08-preview/Databases.json
      - preview/2022-03-08-preview/FirewallRules.json
      - preview/2022-03-08-preview/FlexibleServers.json
      - preview/2022-03-08-preview/Operations.json
      - preview/2022-03-08-preview/PrivateDnsZone.json
      - preview/2022-03-08-preview/Replicas.json
      - preview/2022-03-08-preview/ServerStartStopRestart.json
      - preview/2022-03-08-preview/VirtualNetwork.json
  - version: 2022-03-08-privatepreview
    source: swagger
    swagger-files:
      - preview/2022-03-08-privatepreview/getCachedServerName.json
  - version: 2022-05-01-preview
    source: swagger
    swagger-files:
      - preview/2022-05-01-preview/Migrations.json
      - preview/2022-05-01-preview/Operations.json
  - version: 2022-12-01
    source: swagger
    swagger-files:
      - stable/2022-12-01/Administrators.json
      - stable/2022-12-01/Backups.json
      - stable/2022-12-01/Capabilities.json
      - stable/2022-12-01/CheckNameAvailability.json
      - stable/2022-12-01/Configuration.json
      - stable/2022-12-01/Databases.json
      - stable/2022-12-01/FirewallRules.json
      - stable/2022-12-01/FlexibleServers.json
      - stable/2022-12-01/Operations.json
      - stable/2022-12-01/PrivateDnsZone.json
      - stable/2022-12-01/Replicas.json
      - stable/2022-12-01/ServerStartStopRestart.json
      - stable/2022-12-01/VirtualNetwork.json
  - version: 2023-03-01-preview
    source: swagger
    swagger-files:
      - preview/2023-03-01-preview/Administrators.json
      - preview/2023-03-01-preview/Backups.json
      - preview/2023-03-01-preview/Capabilities.json
      - preview/2023-03-01-preview/CheckNameAvailability.json
      - preview/2023-03-01-preview/Configuration.json
      - preview/2023-03-01-preview/Databases.json
      - preview/2023-03-01-preview/FirewallRules.json
      - preview/2023-03-01-preview/FlexibleServers.json
      - preview/2023-03-01-preview/LongTermRetentionOperation.json
      - preview/2023-03-01-preview/Migrations.json
      - preview/2023-03-01-preview/Operations.json
      - preview/2023-03-01-preview/PrivateDnsZone.json
      - preview/2023-03-01-preview/Replicas.json
      - preview/2023-03-01-preview/ServerLogs.json
      - preview/2023-03-01-preview/ServerStartStopRestart.json
      - preview/2023-03-01-preview/VirtualNetwork.json
  - version: 2023-06-01-preview
    source: swagger
    swagger-files:
      - preview/2023-06-01-preview/Administrators.json
      - preview/2023-06-01-preview/Backups.json
      - preview/2023-06-01-preview/Capabilities.json
      - preview/2023-06-01-preview/CheckNameAvailability.json
      - preview/2023-06-01-preview/Configuration.json
      - preview/2023-06-01-preview/Databases.json
      - preview/2023-06-01-preview/FirewallRules.json
      - preview/2023-06-01-preview/FlexibleServers.json
      - preview/2023-06-01-preview/LongTermRetentionOperation.json
      - preview/2023-06-01-preview/Migrations.json
      - preview/2023-06-01-preview/Operations.json
      - preview/2023-06-01-preview/PrivateDnsZone.json
      - preview/2023-06-01-preview/PrivateEndpointConnections.json
      - preview/2023-06-01-preview/PrivateLinkResources.json
      - preview/2023-06-01-preview/QuotaUsages.json
      - preview/2023-06-01-preview/Replicas.json
      - preview/2023-06-01-preview/ServerLogs.json
      - preview/2023-06-01-preview/ServerStartStopRestart.json
      - preview/2023-06-01-preview/ThreatProtection.json
      - preview/2023-06-01-preview/VirtualEndpoints.json
      - preview/2023-06-01-preview/VirtualNetwork.json
  - version: 2023-12-01-preview
    source: swagger
    swagger-files:
      - preview/2023-12-01-preview/Administrators.json
      - preview/2023-12-01-preview/Backups.json
      - preview/2023-12-01-preview/Capabilities.json
      - preview/2023-12-01-preview/CheckNameAvailability.json
      - preview/2023-12-01-preview/Configuration.json
      - preview/2023-12-01-preview/Databases.json
      - preview/2023-12-01-preview/FirewallRules.json
      - preview/2023-12-01-preview/FlexibleServers.json
      - preview/2023-12-01-preview/LongTermRetentionOperation.json
      - preview/2023-12-01-preview/Migrations.json
      - preview/2023-12-01-preview/Operations.json
      - preview/2023-12-01-preview/PrivateDnsZone.json
      - preview/2023-12-01-preview/PrivateEndpointConnections.json
      - preview/2023-12-01-preview/PrivateLinkResources.json
      - preview/2023-12-01-preview/QuotaUsages.json
      - preview/2023-12-01-preview/Replicas.json
      - preview/2023-12-01-preview/ServerLogs.json
      - preview/2023-12-01-preview/ServerStartStopRestart.json
      - preview/2023-12-01-preview/ThreatProtection.json
      - preview/2023-12-01-preview/VirtualEndpoints.json
      - preview/2023-12-01-preview/VirtualNetwork.json
  - version: 2024-03-01-preview
    source: swagger
    swagger-files:
      - preview/2024-03-01-preview/Administrators.json
      - preview/2024-03-01-preview/Backups.json
      - preview/2024-03-01-preview/Capabilities.json
      - preview/2024-03-01-preview/CheckNameAvailability.json
      - preview/2024-03-01-preview/Configuration.json
      - preview/2024-03-01-preview/Databases.json
      - preview/2024-03-01-preview/FirewallRules.json
      - preview/2024-03-01-preview/FlexibleServers.json
      - preview/2024-03-01-preview/LongTermRetentionOperation.json
      - preview/2024-03-01-preview/Migrations.json
      - preview/2024-03-01-preview/Operations.json
      - preview/2024-03-01-preview/PrivateDnsZone.json
      - preview/2024-03-01-preview/PrivateEndpointConnections.json
      - preview/2024-03-01-preview/PrivateLinkResources.json
      - preview/2024-03-01-preview/QuotaUsages.json
      - preview/2024-03-01-preview/Replicas.json
      - preview/2024-03-01-preview/ServerLogs.json
      - preview/2024-03-01-preview/ServerStartStopRestart.json
      - preview/2024-03-01-preview/ThreatProtection.json
      - preview/2024-03-01-preview/VirtualEndpoints.json
      - preview/2024-03-01-preview/VirtualNetwork.json
  - version: 2024-08-01
    source: swagger
    swagger-files:
      - stable/2024-08-01/Administrators.json
      - stable/2024-08-01/Backups.json
      - stable/2024-08-01/Capabilities.json
      - stable/2024-08-01/CheckNameAvailability.json
      - stable/2024-08-01/Configuration.json
      - stable/2024-08-01/Databases.json
      - stable/2024-08-01/FirewallRules.json
      - stable/2024-08-01/FlexibleServers.json
      - stable/2024-08-01/LongTermRetentionOperation.json
      - stable/2024-08-01/Migrations.json
      - stable/2024-08-01/Operations.json
      - stable/2024-08-01/PrivateDnsZone.json
      - stable/2024-08-01/PrivateEndpointConnections.json
      - stable/2024-08-01/PrivateLinkResources.json
      - stable/2024-08-01/Replicas.json
      - stable/2024-08-01/ServerLogs.json
      - stable/2024-08-01/ServerStartStopRestart.json
      - stable/2024-08-01/ThreatProtection.json
      - stable/2024-08-01/VirtualEndpoints.json
      - stable/2024-08-01/VirtualNetwork.json
  - version: 2024-11-01-preview
    source: swagger
    swagger-files:
      - preview/2024-11-01-preview/Administrators.json
      - preview/2024-11-01-preview/Backups.json
      - preview/2024-11-01-preview/Capabilities.json
      - preview/2024-11-01-preview/CheckNameAvailability.json
      - preview/2024-11-01-preview/Configuration.json
      - preview/2024-11-01-preview/Databases.json
      - preview/2024-11-01-preview/FirewallRules.json
      - preview/2024-11-01-preview/FlexibleServers.json
      - preview/2024-11-01-preview/LongTermRetentionOperation.json
      - preview/2024-11-01-preview/Migrations.json
      - preview/2024-11-01-preview/Operations.json
      - preview/2024-11-01-preview/PrivateDnsZone.json
      - preview/2024-11-01-preview/PrivateEndpointConnections.json
      - preview/2024-11-01-preview/PrivateLinkResources.json
      - preview/2024-11-01-preview/QuotaUsages.json
      - preview/2024-11-01-preview/Replicas.json
      - preview/2024-11-01-preview/ServerLogs.json
      - preview/2024-11-01-preview/ServerStartStopRestart.json
      - preview/2024-11-01-preview/ThreatProtection.json
      - preview/2024-11-01-preview/TuningOptions.json
      - preview/2024-11-01-preview/VirtualEndpoints.json
      - preview/2024-11-01-preview/VirtualNetwork.json
  - version: 2025-01-01-preview
    source: swagger
    swagger-files:
      - preview/2025-01-01-preview/Administrators.json
      - preview/2025-01-01-preview/Backups.json
      - preview/2025-01-01-preview/Capabilities.json
      - preview/2025-01-01-preview/CheckNameAvailability.json
      - preview/2025-01-01-preview/Configuration.json
      - preview/2025-01-01-preview/Databases.json
      - preview/2025-01-01-preview/FirewallRules.json
      - preview/2025-01-01-preview/FlexibleServers.json
      - preview/2025-01-01-preview/LongTermRetentionOperation.json
      - preview/2025-01-01-preview/Migrations.json
      - preview/2025-01-01-preview/Operations.json
      - preview/2025-01-01-preview/PrivateDnsZone.json
      - preview/2025-01-01-preview/PrivateEndpointConnections.json
      - preview/2025-01-01-preview/PrivateLinkResources.json
      - preview/2025-01-01-preview/QuotaUsages.json
      - preview/2025-01-01-preview/Replicas.json
      - preview/2025-01-01-preview/ServerLogs.json
      - preview/2025-01-01-preview/ServerStartStopRestart.json
      - preview/2025-01-01-preview/ThreatProtection.json
      - preview/2025-01-01-preview/TuningOptions.json
      - preview/2025-01-01-preview/VirtualEndpoints.json
      - preview/2025-01-01-preview/VirtualNetwork.json
  - version: 2025-06-01-preview
    source: swagger
    swagger-files:
      - preview/2025-06-01-preview/AdministratorsMicrosoftEntra.json
      - preview/2025-06-01-preview/AdvancedThreatProtectionSettings.json
      - preview/2025-06-01-preview/BackupsAutomaticAndOnDemand.json
      - preview/2025-06-01-preview/BackupsLongTermRetention.json
      - preview/2025-06-01-preview/Capabilities.json
      - preview/2025-06-01-preview/CapturedLogs.json
      - preview/2025-06-01-preview/Configurations.json
      - preview/2025-06-01-preview/Databases.json
      - preview/2025-06-01-preview/FirewallRules.json
      - preview/2025-06-01-preview/Migrations.json
      - preview/2025-06-01-preview/NameAvailability.json
      - preview/2025-06-01-preview/Operations.json
      - preview/2025-06-01-preview/PrivateDnsZoneSuffix.json
      - preview/2025-06-01-preview/PrivateEndpointConnections.json
      - preview/2025-06-01-preview/PrivateLinkResources.json
      - preview/2025-06-01-preview/QuotaUsages.json
      - preview/2025-06-01-preview/Replicas.json
      - preview/2025-06-01-preview/Servers.json
      - preview/2025-06-01-preview/TuningOptions.json
      - preview/2025-06-01-preview/VirtualEndpoints.json
      - preview/2025-06-01-preview/VirtualNetworkSubnetUsage.json
  - version: 2025-08-01
    source: typespec
    swagger-files:
      - stable/2025-08-01/openapi.json
  - version: 2026-01-01-preview
    source: typespec
    swagger-files:
      - preview/2026-01-01-preview/openapi.json
  - version: 2026-04-01-preview
    source: typespec
    swagger-files:
      - preview/2026-04-01-preview/openapi.json
