versions:
  - version: 2019-02-01-preview
    source: swagger
    swagger-files:
      - preview/2019-02-01-preview/appconfiguration.json
  - version: 2019-10-01
    source: swagger
    swagger-files:
      - stable/2019-10-01/appconfiguration.json
  - version: 2019-11-01-preview
    source: swagger
    swagger-files:
      - preview/2019-11-01-preview/appconfiguration.json
  - version: 2020-06-01
    source: swagger
    swagger-files:
      - stable/2020-06-01/appconfiguration.json
  - version: 2020-07-01-preview
    source: swagger
    swagger-files:
      - preview/2020-07-01-preview/appconfiguration.json
  - version: 2021-03-01-preview
    source: swagger
    swagger-files:
      - preview/2021-03-01-preview/appconfiguration.json
  - version: 2021-10-01-preview
    source: swagger
    swagger-files:
      - preview/2021-10-01-preview/appconfiguration.json
  - version: 2022-03-01-preview
    source: swagger
    swagger-files:
      - preview/2022-03-01-preview/appconfiguration.json
  - version: 2022-05-01
    source: swagger
    swagger-files:
      - stable/2022-05-01/appconfiguration.json
  - version: 2023-03-01
    source: swagger
    swagger-files:
      - stable/2023-03-01/appconfiguration.json
  - version: 2023-08-01-preview
    source: swagger
    swagger-files:
      - preview/2023-08-01-preview/appconfiguration.json
  - version: 2023-09-01-preview
    source: swagger
    swagger-files:
      - preview/2023-09-01-preview/appconfiguration.json
  - version: 2024-05-01
    source: swagger
    swagger-files:
      - stable/2024-05-01/appconfiguration.json
  - version: 2024-06-01
    source: swagger
    swagger-files:
      - stable/2024-06-01/appconfiguration.json
  - version: 2024-06-15-preview
    source: swagger
    swagger-files:
      - preview/2024-06-15-preview/appconfiguration.json
  - version: 2025-02-01-preview
    source: typespec
    swagger-files:
      - preview/2025-02-01-preview/appconfiguration.json
  - version: 2025-06-01-preview
    source: typespec
    swagger-files:
      - preview/2025-06-01-preview/appconfiguration.json
  - version: 2025-08-01-preview
    source: typespec
    swagger-files:
      - preview/2025-08-01-preview/appconfiguration.json
