versions:
  - version: 2025-02-01-preview
    source: typespec
    swagger-files:
      - preview/2025-02-01-preview/appconfiguration.json
  - version: 2025-06-01-preview
    source: typespec
    swagger-files:
      - preview/2025-06-01-preview/appconfiguration.json
  - version: 2025-08-01-preview
    source: typespec
    swagger-files:
      - preview/2025-08-01-preview/appconfiguration.json
