versions:
  - version: 2022-12-01
    source: typespec
    swagger-files:
      - stable/2022-12-01/loadtestservice.json
  - version: 2023-12-01-preview
    source: typespec
    swagger-files:
      - preview/2023-12-01-preview/loadtestservice.json
  - version: 2024-12-01-preview
    source: typespec
    swagger-files:
      - preview/2024-12-01-preview/loadtestservice.json
