versions:
  - version: 2025-05-31-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.OnlineExperimentation/preview/2025-05-31-preview/OnlineExperimentationWorkspace.json
  - version: 2025-08-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.OnlineExperimentation/preview/2025-08-01-preview/OnlineExperimentationWorkspace.json
