parameters:
  "service-dir":
    default: "sdk/cognitiveservices"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/cognitiveservices.json"
    emit-lro-options: "all"
    use-read-only-status-schema: true
    examples-dir: "{project-root}/examples"
  "@azure-typespec/http-client-csharp-mgmt":
    namespace: "Azure.ResourceManager.CognitiveServices"
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-cognitiveservices"
    namespace: "azure.mgmt.cognitiveservices"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-cognitiveservices"
    namespace: "com.azure.resourcemanager.cognitiveservices"
    service-name: "CognitiveServices"
    flavor: azure
    use-object-for-unknown: true
    float32-as-double: false
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/arm-cognitiveservices"
    flavor: azure
    compatibility-lro: true
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-cognitiveservices"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/cognitiveservices"
    emitter-output-dir: "{output-dir}/{service-dir}/armcognitiveservices"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armcognitiveservices"
    fix-const-stuttering: false
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
