lease:
  resource-provider: Microsoft.TestRP
  startdate: 2026-07-15        # ISO 8601 format (YYYY-MM-DD)
  duration-days: P180D           # ISO 8601 duration (maximum P180D)
  reviewer: Tejaswi Salaigari
