versions:
  - version: 2015-05-04-preview
    source: swagger
    swagger-files:
      - preview/2015-05-04-preview/dns.json
  - version: 2016-04-01
    source: swagger
    swagger-files:
      - stable/2016-04-01/dns.json
  - version: 2017-09-01
    source: swagger
    swagger-files:
      - stable/2017-09-01/dns.json
  - version: 2017-10-01
    source: swagger
    swagger-files:
      - stable/2017-10-01/dns.json
  - version: 2018-03-01-preview
    source: swagger
    swagger-files:
      - preview/2018-03-01-preview/dns.json
  - version: 2018-05-01
    source: swagger
    swagger-files:
      - stable/2018-05-01/dns.json
  - version: 2023-07-01-preview
    source: typespec
    swagger-files:
      - preview/2023-07-01-preview/dns.json
