// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

/**
 * Package containing the implementations for DataMigration.
 * The SQL Migration management API provides a RESTful set of web APIs that allow users to migrate their SQL Server
 * databases to Azure SQL.
 */
package com.azure.resourcemanager.datamigration.implementation;
