versions:
  - version: 2025-03-30-preview
    source: typespec
    swagger-files:
      - preview/2025-03-30-preview/waves.json
  - version: 2025-12-01-preview
    source: typespec
    swagger-files:
      - preview/2025-12-01-preview/waves.json
  - version: 2026-02-01-preview
    source: typespec
    swagger-files:
      - preview/2026-02-01-preview/waves.json
