parameters:
  service-dir:
    default: "/^(\\{output-dir\\}\\/)?sdk\\/[^\\/]*$/"
emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "resource-manager"
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/hardware.json"
  "@azure-tools/typespec-java":
    emitter-output-dir: "{service-dir}/azure-hardware"
    namespace: "com.azure.hardware"
    flavor: "azure"
  "@azure-tools/typespec-ts":
    experimental-extensible-enums: true
    flavor: "azure"
    emitter-output-dir: "{service-dir}/azure-hardware"
    package-details:
      name: "@azure-rest/azure-hardware-rest"
      description: "azure.Hardware ResourceProvider`"
  "@azure-tools/typespec-go":
    emitter-output-dir: "{service-dir}/armhardware"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armhardware"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-tools/typespec-python":
    emitter-output-dir: "{service-dir}/azure-hardware"
    namespace: "azure.hardware"
    generate-sample: true
    generate-test: true
    flavor: "azure"
  "@azure-tools/typespec-csharp":
    namespace: "Azure.Hardware"
    flavor: "azure"
    clear-output-folder: true
    emitter-output-dir: "{service-dir}/{namespace}"