parameters:
  service-dir:
    default: "sdk/hardware"
emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "resource-manager"
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}/.."
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/hardware.json"
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-hardware"
    namespace: "com.azure.resourcemanager.hardware"
    flavor: "azure"
  "@azure-tools/typespec-ts":
    experimental-extensible-enums: true
    flavor: "azure"
    emitter-output-dir: "{output-dir}/{service-dir}/arm-hardware"
    package-details:
      name: "@azure/arm-hardware"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/hardware"
    emitter-output-dir: "{output-dir}/{service-dir}/armhardware"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armhardware"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-hardware"
    namespace: "azure.mgmt.hardware"
    generate-sample: true
    generate-test: true
    flavor: "azure"
  "@azure-tools/typespec-csharp":
    namespace: "Azure.ResourceManager.Hardware"
    flavor: "azure"
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
