versions:
  - version: 2023-07-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AzureTerraform/preview/2023-07-01-preview/export.json
  - version: 2025-06-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AzureTerraform/preview/2025-06-01-preview/export.json
  - version: 2025-09-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.AzureTerraform/preview/2025-09-01-preview/export.json
