versions:
  - version: 2024-11-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.IoTOperations/stable/2024-11-01/iotoperations.json
  - version: 2025-04-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.IoTOperations/stable/2025-04-01/iotoperations.json
  - version: 2025-07-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.IoTOperations/preview/2025-07-01-preview/iotoperations.json
  - version: 2025-10-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.IoTOperations/stable/2025-10-01/iotoperations.json
  - version: 2026-03-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.IoTOperations/stable/2026-03-01/iotoperations.json
  - version: 2026-07-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.IoTOperations/stable/2026-07-01/iotoperations.json
