versions:
  - version: 2026-01-20-preview
    source: typespec
    swagger-files:
      - preview/2026-01-20-preview/openapi.json
  - version: 2026-05-01-preview
    source: typespec
    swagger-files:
      - preview/2026-05-01-preview/openapi.json
  - version: 2026-10-01
    source: typespec
    swagger-files:
      - stable/2026-10-01/openapi.json
  - version: 2027-03-01-preview
    source: typespec
    swagger-files:
      - preview/2027-03-01-preview/openapi.json
