versions:
  - version: 2026-01-20-preview
    source: typespec
    swagger-files:
      - preview/2026-01-20-preview/openapi.json
  - version: 2026-05-01-preview
    source: typespec
    swagger-files:
      - preview/2026-05-01-preview/openapi.json
