versions:
  - version: 2024-04-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/copilotSettings/stable/2024-04-01/copilotSettings.json
  - version: 2024-04-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.PortalServices/copilotSettings/preview/2024-04-01-preview/copilotSettings.json
