versions:
  - version: 2023-09-01
    source: typespec
    swagger-files:
      - stable/2023-09-01/vmware.json
  - version: 2024-09-01
    source: typespec
    swagger-files:
      - stable/2024-09-01/vmware.json
  - version: 2025-09-01
    source: typespec
    swagger-files:
      - stable/2025-09-01/vmware.json
