versions:
  - version: 2020-09-15_Preview
    source: swagger
    swagger-files:
      - preview/2020-09-15_Preview/swagger.json
  - version: v2.1
    source: typespec
    swagger-files:
      - preview/v2.1/swagger.json
