versions:
  - version: 2023-03-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Informatica.DataManagement/preview/2023-03-01-preview/openapi.json
  - version: 2023-08-20-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Informatica.DataManagement/preview/2023-08-20-preview/openapi.json
  - version: 2024-05-08
    source: typespec
    swagger-files:
      - ../resource-manager/Informatica.DataManagement/stable/2024-05-08/openapi.json
  - version: 2024-07-22-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Informatica.DataManagement/preview/2024-07-22-preview/openapi.json
  - version: 2024-11-29-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Informatica.DataManagement/preview/2024-11-29-preview/openapi.json
  - version: 2025-11-27
    source: typespec
    swagger-files:
      - ../resource-manager/Informatica.DataManagement/stable/2025-11-27/openapi.json
