emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "resource-manager"
    emitter-output-dir: "{output-dir}/{azure-resource-provider-folder}"
    arm-types-dir: "{project-root}/../../common-types/resource-management"
