// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.datamigration.implementation.models;

import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import com.azure.resourcemanager.datamigration.fluent.models.DatabaseMigrationInner;
import java.io.IOException;
import java.util.List;

/**
 * The response of a DatabaseMigration list operation.
 */
@Immutable
public final class DatabaseMigrationListResult implements JsonSerializable<DatabaseMigrationListResult> {
    /*
     * The DatabaseMigration items on this page
     */
    private List<DatabaseMigrationInner> value;

    /*
     * The link to the next page of items
     */
    private String nextLink;

    /**
     * Creates an instance of DatabaseMigrationListResult class.
     */
    private DatabaseMigrationListResult() {
    }

    /**
     * Get the value property: The DatabaseMigration items on this page.
     * 
     * @return the value value.
     */
    public List<DatabaseMigrationInner> value() {
        return this.value;
    }

    /**
     * Get the nextLink property: The link to the next page of items.
     * 
     * @return the nextLink value.
     */
    public String nextLink() {
        return this.nextLink;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("nextLink", this.nextLink);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of DatabaseMigrationListResult from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of DatabaseMigrationListResult if the JsonReader was pointing to an instance of it, or null
     * if it was pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the DatabaseMigrationListResult.
     */
    public static DatabaseMigrationListResult fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            DatabaseMigrationListResult deserializedDatabaseMigrationListResult = new DatabaseMigrationListResult();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("value".equals(fieldName)) {
                    List<DatabaseMigrationInner> value
                        = reader.readArray(reader1 -> DatabaseMigrationInner.fromJson(reader1));
                    deserializedDatabaseMigrationListResult.value = value;
                } else if ("nextLink".equals(fieldName)) {
                    deserializedDatabaseMigrationListResult.nextLink = reader.getString();
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedDatabaseMigrationListResult;
        });
    }
}
