versions:
  - version: 2021-09-01
    source: swagger
    swagger-files:
      - stable/2021-09-01/dynatrace.json
  - version: 2021-09-01-preview
    source: swagger
    swagger-files:
      - preview/2021-09-01-preview/dynatrace.json
  - version: 2023-04-27
    source: swagger
    swagger-files:
      - stable/2023-04-27/dynatrace.json
  - version: 2024-04-24
    source: typespec
    swagger-files:
      - stable/2024-04-24/dynatrace.json
