versions:
  - version: 2023-09-01-preview
    source: swagger
    swagger-files:
      - ../preview/2023-09-01-preview/securityConnectorsDevOps.json
  - version: 2024-04-01
    source: swagger
    swagger-files:
      - ../stable/2024-04-01/securityConnectorsDevOps.json
  - version: 2024-05-15-preview
    source: swagger
    swagger-files:
      - ../preview/2024-05-15-preview/securityConnectorsDevOps.json
  - version: 2025-03-01
    source: swagger
    swagger-files:
      - ../stable/2025-03-01/securityConnectorsDevOps.json
  - version: 2025-11-01-preview
    source: typespec
    swagger-files:
      - ../preview/2025-11-01-preview/securityConnectorsDevOps.json
