emit:
- '@azure-tools/typespec-autorest'
linter:
  extends:
  - '@azure-tools/typespec-azure-rulesets/resource-manager'
options:
  '@azure-tools/typespec-autorest':
    arm-types-dir: '{project-root}/../../../../common-types/resource-management'
    emit-lro-options: all
    emitter-output-dir: '{project-root}'
    examples-dir: '{project-root}/examples'
    omit-unreachable-types: true
    output-file: '{version-status}/{version}/management.json'
  '@azure-tools/typespec-csharp':
    clear-output-folder: true
    emitter-output-dir: '{output-dir}/{service-dir}/Azure.ResourceManager.ManagementGroups'
    flavor: azure
    model-namespace: true
    namespace: Azure.ResourceManager.ManagementGroups
  '@azure-tools/typespec-go':
    emitter-output-dir: '{output-dir}/{service-dir}/armmanagementgroups'
    fix-const-stuttering: true
    flavor: azure
    generate-fakes: true
    generate-samples: true
    head-as-boolean: true
    inject-spans: true
    module: github.com/Azure/azure-sdk-for-go/{service-dir}/armmanagementgroups
    service-dir: sdk/resourcemanager/managementgroups
  '@azure-tools/typespec-java':
    add-inner: HierarchySettingsInfo
    emitter-output-dir: '{output-dir}/{service-dir}/azure-resourcemanager-managementgroups'
    flavor: azure
    namespace: com.azure.resourcemanager.managementgroups
    rename-model:
      CheckNameAvailabilityRequestType: Type
    service-name: ManagementGroups
  '@azure-tools/typespec-python':
    api-version: '2023-04-01'
    emitter-output-dir: '{output-dir}/{service-dir}/azure-mgmt-managementgroups'
    flavor: azure
    generate-sample: true
    generate-test: true
    namespace: azure.mgmt.managementgroups
  '@azure-tools/typespec-ts':
    emitter-output-dir: '{output-dir}/{service-dir}/arm-managementgroups'
    experimental-extensible-enums: true
    flavor: azure
    package-details:
      name: '@azure/arm-managementgroups'
    typespec-title-map:
      ManagementClient: ManagementGroupsAPI
parameters:
  service-dir:
    default: sdk/managementgroups
