name: "Package Name Approval - Set Status"

on:
  workflow_run:
    workflows: ["Package Name Approval - Analyze Code"]
    types: [completed]
    branches:
      - main

permissions:
  actions: read
  contents: read
  pull-requests: write
  statuses: write

jobs:
  post-results:
    name: Post Package Name Results
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github/

      - name: Install dependencies for github-script actions
        uses: ./.github/actions/install-deps-github-script

      - name: Post package name review comment
        uses: actions/github-script@v8
        with:
          script: |
            const { default: postResults } =
              await import('${{ github.workspace }}/.github/workflows/src/namespace-approval/post-results.js');
            await postResults({ github, context, core });

      - name: Set package name approval status
        uses: actions/github-script@v8
        with:
          script: |
            const { default: statusCheck } =
              await import('${{ github.workspace }}/.github/workflows/src/namespace-approval/status-check.js');
            await statusCheck({ github, context, core });
