name: Update Labels

on:
  # TODO: If a pull request is manually labeled or unlabeled, get all artifacts associated with PR, and update labels
  # pull_request:
  #   types: [labeled, unlabeled]
  # If an upstream workflow if completed, get only the artifacts from that workflow, and update labels
  workflow_run:
    workflows:
      [
        "ARM Auto SignOff - Set Status",
        "ARM Universal Auto SignOff",
        "ARM Modeling Review",
        "SDK Breaking Change Labels",
        "SDK Suppressions",
        "TypeSpec Requirement",
        "Breaking Change - Add Label Artifacts",
      ]
    types: [completed]

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  update-labels:
    name: Update Labels

    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v7
        with:
          sparse-checkout: |
            .github

      - uses: ./.github/actions/install-workflow-deps

      - name: Update Labels
        id: update-labels
        run: node "${{ github.workspace }}/.github/workflows/cmd/update-labels.ts"
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - if: ${{ always() && steps.update-labels.outputs.head_sha }}
        name: Upload artifact with head SHA
        uses: ./.github/actions/add-empty-artifact
        with:
          name: head-sha
          value: ${{ steps.update-labels.outputs.head_sha }}

      - if: ${{ always() && steps.update-labels.outputs.issue_number }}
        name: Upload artifact with issue number
        uses: ./.github/actions/add-empty-artifact
        with:
          name: issue-number
          value: ${{ steps.update-labels.outputs.issue_number }}
