name: Validate ARM Leases

on:
  pull_request:
    types:
      # default
      - opened
      - synchronize
      - reopened
      # re-run if base branch is changed, since previous merge commit may generate incorrect diff
      - edited
    paths:
      # Only trigger if PR includes at least one changed ARM lease file
      - ".github/arm-leases/**"
      # Also trigger on own sources
      - ".github/workflows/validate-arm-leases.yaml"
      - ".github/workflows/src/validate-arm-leases.js"

permissions:
  contents: read

jobs:
  validate-arm-leases:
    name: Validate ARM Leases
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 2
          sparse-checkout: |
            .github

      - name: Install dependencies for github-script actions
        uses: ./.github/actions/install-deps-github-script

      - name: Validate ARM leases
        uses: actions/github-script@v8
        with:
          script: |
            const { default: validateArmLeases } =
              await import('${{ github.workspace }}/.github/workflows/src/validate-arm-leases.js');
            return await validateArmLeases(core);