versions:
  - version: 2023-11-13-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Quantum/preview/2023-11-13-preview/quantum.json
  - version: 2025-01-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Quantum/preview/2025-01-01-preview/quantum.json
  - version: 2025-08-11-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Quantum/preview/2025-08-11-preview/quantum.json
  - version: 2025-11-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Quantum/preview/2025-11-01-preview/quantum.json
  - version: 2025-12-15-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Quantum/preview/2025-12-15-preview/quantum.json
  - version: 2026-06-15-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Quantum/preview/2026-06-15-preview/quantum.json
