versions:
  - version: 2024-10-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.EdgeMarketplace/stable/2024-10-01/edgemarketplace.json
  - version: 2025-10-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.EdgeMarketplace/preview/2025-10-01-preview/edgemarketplace.json
