versions:
  - version: 2023-08-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.EdgeMarketplace/stable/2023-08-01/offers.json
      - ../resource-manager/Microsoft.EdgeMarketplace/stable/2023-08-01/operations.json
      - ../resource-manager/Microsoft.EdgeMarketplace/stable/2023-08-01/publishers.json
  - version: 2023-08-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.EdgeMarketplace/preview/2023-08-01-preview/offers.json
      - ../resource-manager/Microsoft.EdgeMarketplace/preview/2023-08-01-preview/operations.json
      - ../resource-manager/Microsoft.EdgeMarketplace/preview/2023-08-01-preview/publishers.json
  - version: 2024-10-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.EdgeMarketplace/stable/2024-10-01/edgemarketplace.json
  - version: 2025-10-01-preview
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.EdgeMarketplace/preview/2025-10-01-preview/edgemarketplace.json
