versions:
  - version: 2024-02-15-preview
    source: typespec
    swagger-files:
      - ../data-plane/OpenAI.Assistants/OpenApiV2/preview/2024-02-15-preview/assistants_generated.json
  - version: 2024-05-01-preview
    source: typespec
    swagger-files:
      - ../data-plane/OpenAI.Assistants/OpenApiV2/preview/2024-05-01-preview/assistants_generated.json
  - version: 2024-07-01-preview
    source: typespec
    swagger-files:
      - ../data-plane/OpenAI.Assistants/OpenApiV2/preview/2024-07-01-preview/assistants_generated.json
  - version: 2024-09-01-preview
    source: typespec
    swagger-files:
      - ../data-plane/OpenAI.Assistants/OpenApiV2/preview/2024-09-01-preview/assistants_generated.json
  - version: 2024-10-01-preview
    source: typespec
    swagger-files:
      - ../data-plane/OpenAI.Assistants/OpenApiV2/preview/2024-10-01-preview/assistants_generated.json
  - version: 2025-01-01-preview
    source: typespec
    swagger-files:
      - ../data-plane/OpenAI.Assistants/OpenApiV2/preview/2025-01-01-preview/assistants_generated.json
