versions:
  - version: 2015-05-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/preview/2015-05-01-preview/storage.json
  - version: 2015-06-15
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2015-06-15/storage.json
  - version: 2016-01-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2016-01-01/storage.json
  - version: 2016-05-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2016-05-01/storage.json
  - version: 2016-12-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2016-12-01/storage.json
  - version: 2017-06-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2017-06-01/storage.json
  - version: 2017-10-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2017-10-01/storage.json
  - version: 2018-02-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2018-02-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2018-02-01/storage.json
  - version: 2018-03-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/preview/2018-03-01-preview/blob.json
      - ../resource-manager/Microsoft.Storage/preview/2018-03-01-preview/managementpolicy.json
      - ../resource-manager/Microsoft.Storage/preview/2018-03-01-preview/storage.json
  - version: 2018-07-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2018-07-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2018-07-01/storage.json
  - version: 2018-11-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2018-11-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2018-11-01/storage.json
  - version: 2019-04-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2019-04-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2019-04-01/file.json
      - ../resource-manager/Microsoft.Storage/stable/2019-04-01/storage.json
  - version: 2019-06-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2019-06-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2019-06-01/file.json
      - ../resource-manager/Microsoft.Storage/stable/2019-06-01/queue.json
      - ../resource-manager/Microsoft.Storage/stable/2019-06-01/storage.json
      - ../resource-manager/Microsoft.Storage/stable/2019-06-01/table.json
  - version: 2020-08-01-preview
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/preview/2020-08-01-preview/blob.json
      - ../resource-manager/Microsoft.Storage/preview/2020-08-01-preview/file.json
      - ../resource-manager/Microsoft.Storage/preview/2020-08-01-preview/queue.json
      - ../resource-manager/Microsoft.Storage/preview/2020-08-01-preview/storage.json
      - ../resource-manager/Microsoft.Storage/preview/2020-08-01-preview/table.json
  - version: 2021-01-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2021-01-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2021-01-01/file.json
      - ../resource-manager/Microsoft.Storage/stable/2021-01-01/queue.json
      - ../resource-manager/Microsoft.Storage/stable/2021-01-01/storage.json
      - ../resource-manager/Microsoft.Storage/stable/2021-01-01/table.json
  - version: 2021-02-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2021-02-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2021-02-01/file.json
      - ../resource-manager/Microsoft.Storage/stable/2021-02-01/queue.json
      - ../resource-manager/Microsoft.Storage/stable/2021-02-01/storage.json
      - ../resource-manager/Microsoft.Storage/stable/2021-02-01/table.json
  - version: 2021-04-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2021-04-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2021-04-01/file.json
      - ../resource-manager/Microsoft.Storage/stable/2021-04-01/queue.json
      - ../resource-manager/Microsoft.Storage/stable/2021-04-01/storage.json
      - ../resource-manager/Microsoft.Storage/stable/2021-04-01/table.json
  - version: 2021-06-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2021-06-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2021-06-01/file.json
      - ../resource-manager/Microsoft.Storage/stable/2021-06-01/queue.json
      - ../resource-manager/Microsoft.Storage/stable/2021-06-01/storage.json
      - ../resource-manager/Microsoft.Storage/stable/2021-06-01/table.json
  - version: 2021-08-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2021-08-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2021-08-01/file.json
      - ../resource-manager/Microsoft.Storage/stable/2021-08-01/queue.json
      - ../resource-manager/Microsoft.Storage/stable/2021-08-01/storage.json
      - ../resource-manager/Microsoft.Storage/stable/2021-08-01/table.json
  - version: 2021-09-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2021-09-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2021-09-01/file.json
      - ../resource-manager/Microsoft.Storage/stable/2021-09-01/queue.json
      - ../resource-manager/Microsoft.Storage/stable/2021-09-01/storage.json
      - ../resource-manager/Microsoft.Storage/stable/2021-09-01/table.json
  - version: 2022-05-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2022-05-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2022-05-01/file.json
      - ../resource-manager/Microsoft.Storage/stable/2022-05-01/queue.json
      - ../resource-manager/Microsoft.Storage/stable/2022-05-01/storage.json
      - ../resource-manager/Microsoft.Storage/stable/2022-05-01/table.json
  - version: 2022-09-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2022-09-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2022-09-01/file.json
      - ../resource-manager/Microsoft.Storage/stable/2022-09-01/queue.json
      - ../resource-manager/Microsoft.Storage/stable/2022-09-01/storage.json
      - ../resource-manager/Microsoft.Storage/stable/2022-09-01/table.json
  - version: 2023-01-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2023-01-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2023-01-01/file.json
      - ../resource-manager/Microsoft.Storage/stable/2023-01-01/queue.json
      - ../resource-manager/Microsoft.Storage/stable/2023-01-01/storage.json
      - ../resource-manager/Microsoft.Storage/stable/2023-01-01/table.json
  - version: 2023-04-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2023-04-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2023-04-01/common.json
      - ../resource-manager/Microsoft.Storage/stable/2023-04-01/file.json
      - ../resource-manager/Microsoft.Storage/stable/2023-04-01/networkSecurityPerimeter.json
      - ../resource-manager/Microsoft.Storage/stable/2023-04-01/privatelinks.json
      - ../resource-manager/Microsoft.Storage/stable/2023-04-01/queue.json
      - ../resource-manager/Microsoft.Storage/stable/2023-04-01/storage.json
      - ../resource-manager/Microsoft.Storage/stable/2023-04-01/table.json
  - version: 2023-05-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2023-05-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2023-05-01/common.json
      - ../resource-manager/Microsoft.Storage/stable/2023-05-01/file.json
      - ../resource-manager/Microsoft.Storage/stable/2023-05-01/networkSecurityPerimeter.json
      - ../resource-manager/Microsoft.Storage/stable/2023-05-01/privatelinks.json
      - ../resource-manager/Microsoft.Storage/stable/2023-05-01/queue.json
      - ../resource-manager/Microsoft.Storage/stable/2023-05-01/storage.json
      - ../resource-manager/Microsoft.Storage/stable/2023-05-01/storageTaskAssignments.json
      - ../resource-manager/Microsoft.Storage/stable/2023-05-01/table.json
  - version: 2024-01-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2024-01-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2024-01-01/common.json
      - ../resource-manager/Microsoft.Storage/stable/2024-01-01/file.json
      - ../resource-manager/Microsoft.Storage/stable/2024-01-01/networkSecurityPerimeter.json
      - ../resource-manager/Microsoft.Storage/stable/2024-01-01/privatelinks.json
      - ../resource-manager/Microsoft.Storage/stable/2024-01-01/queue.json
      - ../resource-manager/Microsoft.Storage/stable/2024-01-01/storage.json
      - ../resource-manager/Microsoft.Storage/stable/2024-01-01/storageTaskAssignments.json
      - ../resource-manager/Microsoft.Storage/stable/2024-01-01/table.json
  - version: 2025-01-01
    source: swagger
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2025-01-01/blob.json
      - ../resource-manager/Microsoft.Storage/stable/2025-01-01/common.json
      - ../resource-manager/Microsoft.Storage/stable/2025-01-01/file.json
      - ../resource-manager/Microsoft.Storage/stable/2025-01-01/networkSecurityPerimeter.json
      - ../resource-manager/Microsoft.Storage/stable/2025-01-01/privatelinks.json
      - ../resource-manager/Microsoft.Storage/stable/2025-01-01/queue.json
      - ../resource-manager/Microsoft.Storage/stable/2025-01-01/storage.json
      - ../resource-manager/Microsoft.Storage/stable/2025-01-01/storageTaskAssignments.json
      - ../resource-manager/Microsoft.Storage/stable/2025-01-01/table.json
  - version: 2025-06-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2025-06-01/openapi.json
  - version: 2025-08-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2025-08-01/openapi.json
  - version: 2026-04-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2026-04-01/openapi.json
