versions:
  - version: 2025-06-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2025-06-01/openapi.json
  - version: 2025-08-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2025-08-01/openapi.json
  - version: 2026-04-01
    source: typespec
    swagger-files:
      - ../resource-manager/Microsoft.Storage/stable/2026-04-01/openapi.json
