parameters:
  "service-dir":
    default: "sdk/contoso"
  "dependencies":
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emit-lro-options: "none"
    emitter-output-dir: "{project-root}"
    output-file: "{version-status}/{version}/contosodocprocessor.json"
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-contoso-docprocessor"
    namespace: "azure.contoso.docprocessor"
    package-version: "1.0.0b1"
    generate-test: true
    generate-sample: true
    flavor: azure
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/sdk/contoso/contoso-docprocessor"
    package-details:
      name: "@azure/contoso-docprocessor"
    is-modular-library: true
    experimental-extensible-enums: true
    flavor: azure
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-contoso-docprocessor"
    namespace: com.azure.contoso.docprocessor
    flavor: azure
