parameters:
  "service-dir":
    default: "sdk/privilegedaccess-prototype"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    omit-unreachable-types: true
    emitter-output-dir: "{project-root}"
    output-file: "{version-status}/{version}/authorization-PrivilegedAccess.json"
    emit-lro-options: "none"
    arm-types-dir: "{project-root}/../../../../common-types/resource-management"
    examples-dir: "{project-root}/examples"
  "@azure-tools/typespec-python":
    service-dir: "sdk/privilegedaccess-prototype"
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-privilegedaccess-prototype"
    namespace: "azure.mgmt.privilegedaccess.prototype"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-privilegedaccess-prototype"
    service-dir: "sdk/privilegedaccess-prototype"
    namespace: "com.azure.resourcemanager.privilegedaccess"
    service-name: "Authorization"
    flavor: azure
    premium: true
    generate-tests: false
    client-side-validations: true
    enable-sync-stack: false
    float32-as-double: false
    use-object-for-unknown: true
    generate-samples: false
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/arm-privilegedaccess-prototype"
    service-dir: "sdk/privilegedaccess-prototype"
    flavor: "azure"
    compatibility-lro: true
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-privilegedaccess-prototype"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/privilegedaccess-prototype"
    emitter-output-dir: "{output-dir}/{service-dir}/armprivilegedaccessprototype"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armprivilegedaccessprototype"
    fix-const-stuttering: false
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-typespec/http-client-csharp-mgmt":
    namespace: "Azure.ResourceManager.PrivilegedAccess"
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
    enable-wire-path-attribute: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
    - "@azure-tools/typespec-azure-rulesets/client-sdk"
