versions:
  - version: 2015-07-01
    source: swagger
    swagger-files:
      - ../stable/2015-07-01/authorization-ProviderOperationsCalls.json
  - version: 2018-01-01-preview
    source: swagger
    swagger-files:
      - ../preview/2018-01-01-preview/authorization-ProviderOperationsCalls.json
  - version: 2022-04-01
    source: typespec
    swagger-files:
      - ../stable/2022-04-01/authorization-ProviderOperationsCalls.json
